src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsUsingMPP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Accout using MPP as Payment Provider?</description>
        <inlineHelpText>Is this Accout using MPP as Payment Provider?</inlineHelpText>
        <label>Is Using MPP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MPP_CurrentPayScheduleEndDate__c</fullName>
        <label>MPP Current Pay Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Taken_By_Company__c</fullName>
        <label>Order Taken By (Company)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_By_User_Department__c</fullName>
        <label>Order Taken By (User/Department)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_Method__c</fullName>
        <label>Order Taken Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Using_MPP__c</fullName>
        <formula>IF( Subscriber__r.IsUsingMPP__c == TRUE, &quot;True&quot;, &quot;False&quot;)</formula>
        <label>Is Using MPP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_CC_First_Payment_Amount__c</fullName>
        <label>MPP CC First Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MPP_CC_Frequency__c</fullName>
        <label>MPP CC Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_DD_Frequency__c</fullName>
        <label>MPP DD Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_Scheduled_First_Payment_Date__c</fullName>
        <description>Plane 1.2. To Track First payment date setup for continious Subscriptions, when setting up payment Schedule on MPP.</description>
        <label>MPP Scheduled First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutAttemptCount__c</fullName>
        <label>MppDDCalloutAttemptCount</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutStage__c</fullName>
        <label>MppDDCalloutStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>UserManage</fullName>
                </value>
                <value>
                <fullName>UserManage-Failed</fullName>
                </value>
                <value>
                <fullName>DirectDebit</fullName>
                </value>
                <value>
                <fullName>DirectDebit-Failed</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule-Failed</fullName>
                </value>
                <value>
                <fullName>Failed</fullName>
                </value>
                <value>
                <fullName>GetPayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MppDDLastCalloutDateTime__c</fullName>
        <label>MppDDLastCalloutDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Taken_By_Company__c</fullName>
        <defaultValue>&quot;Chatham&quot;</defaultValue>
        <description>Company that takes a new sub order - populated by Synthesis</description>
        <inlineHelpText>Company that takes a new sub order - populated by Synthesis</inlineHelpText>
        <label>Order Taken By (Company)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_By_User_Department__c</fullName>
        <defaultValue>$User.FirstName  &amp; &quot; &quot; &amp;  $User.LastName</defaultValue>
        <description>User (for Chatham) or Department (for 3rd party) that takes a new sub order - populated by Synthesis</description>
        <inlineHelpText>User (for Chatham) or Department (for 3rd party) that takes a new sub order - populated by Synthesis</inlineHelpText>
        <label>Order Taken By (User/Department)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_Method__c</fullName>
        <description>Method of order - populated from Synthesis</description>
        <inlineHelpText>Method of order - populated from Synthesis</inlineHelpText>
        <label>Order Taken Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Outbound</fullName>
                </value>
                <value>
                <fullName>Inbound</fullName>
                </value>
                <value>
                <fullName>Coupon</fullName>
                </value>
                <value>
                <fullName>Auto Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <description>1 or 15 of each month</description>
        <label>Payment Date</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Number__c</fullName>
        <formula>IF(Subscription_Duration_Number_Override__c = 0, CASE(Subscription_Duration_Picklist__c, &quot;6&quot;, 6, &quot;10&quot;, 10, &quot;12&quot;, 12, &quot;13&quot;, 13, &quot;24&quot;, 24, &quot;26&quot;, 26, &quot;36&quot;, 36, &quot;39&quot;, 39, &quot;40&quot;, 40, &quot;44&quot;, 44, &quot;48&quot;, 48, &quot;52&quot;, 52, &quot;96&quot;, 96, &quot;156&quot;, 156, 0), Subscription_Duration_Number_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Duration (Weeks) - Hidden</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Picklist__c</fullName>
        <label>Subscription Duration (Weeks)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>26</fullName>
                </value>
                <value>
                <fullName>52</fullName>
                <default>true</default>
                    <label>52</label>
                </value>
                <value>
                <fullName>13</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reltionship to the Tcode object</description>
        <label>TCodeManagement</label>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total price for the subscription.</description>
        <formula>IF(
   Subscription_Duration_Number__c == 13, 
   IF(
      TCode_Product__r.X13_Week_Price__c == 0, 
      Weekly_Price__c * 13,
      TCode_Product__r.X13_Week_Price__c
   ),
   (Subscription_Duration_Number__c * Weekly_Price__c  - IF(
                                                            NOT(ISNULL(Low_Start_Weekly_Price__c)),
                                                            Low_Start_Period__c * (Weekly_Price__c - Low_Start_Weekly_Price__c),
                                                            0
                                                           )
   )
   )*MAX(Quantity__c, 1)
</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total price for the subscription.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TCodeManagement__c.object
<CustomObject>
    <description>This details the t-code, description, price, if the t-code is still valid and incentive related to the t-code</description>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Allow One Off 13 Week</fullName>
                </value>
                <value>
                <fullName>Allow One Off 26 Week</fullName>
                </value>
                <value>
                <fullName>Allow One Off 52 Week</fullName>
                </value>
                <value>
                <fullName>Allow 13 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 13 Week CCA</fullName>
                </value>
                <value>
                <fullName>Allow 26 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 26 Week CCA</fullName>
                </value>
                <value>
                <fullName>Allow 52 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 52 Week CCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <label>TCode</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>TCodeManagement</label>
    <nameField>
        <label>TCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCodesManagement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MPPBulkPaymentScheduleScheduler.cls
/**
* @author MIrfan@Appirio, Plane 1.2; . 
* @date 09/05/2012
* @description Schedules a batch job that creates payment schedule in MPP for print continuous subscription renewal
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         10/07/2015  //clean-up
**/
global class MPPBulkPaymentScheduleScheduler implements Schedulable {

      global String query = 'select Name,start_date__c, '+
                    ' Previous_Subscription__c, '+
                    ' total_price__c, '+
                    ' TCode__c, '+
                    ' TCode__r.Name, '+
                    ' Order_Taken_By_Company__c, '+
                    ' Order_Taken_By_User_Department__c, '+
                    ' Order_Taken_Method__c, '+
                    ' PaymentDate__c, '+
                    ' Subscription_Duration_Number__c, '+
                    ' Previous_Subscription__r.End_Date__c, '+
                    ' Subscriber__r.Subscriber_Number__c, '+
                    ' Subscriber__r.IsUsingMPP__c, '+
                    ' Subscriber__r.Subscriber_Digital_Status__c, '+
                    ' Subscriber__r.MPP_CurrentPayScheduleEndDate__c,' + 
                    ' Previous_Subscription__r.Is_Using_MPP__c,' + 
                    ' Previous_Subscription__r.isContinuous__c,' + 
                    ' Previous_Subscription__r.Subscription_Status__c,' +
                    ' Previous_Subscription__r.MPP_Scheduled_First_Payment_Date__c, ' +
                    ' Previous_Subscription__r.Subscription_Duration_Picklist__c, ' +
                    ' Previous_Subscription__r.MPP_DD_Frequency__c, '+
                    ' Previous_Subscription__r.MPP_CC_Frequency__c, '+
                    ' Previous_Subscription__r.Payment_Type__c, '+
                    ' Previous_Subscription__r.PaymentDate__c, '+
                    ' MppDDCalloutAttemptCount__c,MppDDCalloutStage__c,MppDDLastCalloutDateTime__c,MPP_CC_First_Payment_Amount__c ' +
                ' from Subscription__c  '+
                ' where Subscription_Status__c=\''+DDSetupOnMPPBatch.SUBSCRIPTION_STATUS_OFFERED+'\' AND  '+
                ' Previous_Subscription__c!=null AND  '+
                ' Previous_Subscription__r.isContinuous__c = true '+ 
                ' AND  '+
                ' (  '+
                '   ( '+
                '       MppDDCalloutAttemptCount__c<4 AND '+ 
                '       MppDDCalloutAttemptCount__c !=null AND '+ 
                '       Payment_Type__c=\''+DDSetupOnMPPBatch.SUBSCRIPTION_PAYMENT_TYPE_DD+'\' AND  '+
                '       Subscriber__r.IsUsingMPP__c=false AND  '+
                '       (MppDDCalloutStage__c =\''+DDSetupOnMPPBatch.MppDDCalloutStage_STAGE_2+'\'  or MppDDCalloutStage__c =\''+DDSetupOnMPPBatch.MppDDCalloutStage_STAGE_3_FAILED+'\') '+ 
                '   )  '+
                '   OR  '+
                '   ( '+
                '       (MppDDCalloutAttemptCount__c<4 OR MppDDCalloutAttemptCount__c = null) AND '+ 
                '       Subscriber__r.IsUsingMPP__c=true AND  '+
                '       (MppDDCalloutStage__c = null or MppDDCalloutStage__c =\''+DDSetupOnMPPBatch.MppDDCalloutStage_STAGE_3_FAILED+'\') '+ 
                '   )  '+
                ' )  '+
                ' order by Name ';                                
                
    //this method creates the query string and executes the batch
    global void execute(SchedulableContext sc) {
        try {
            DDSetupOnMPPBatch batchable = new DDSetupOnMPPBatch(query, 'PaymentSchedule');          
            Id accountUpdateBatchId = Database.executeBatch(batchable,Integer.valueOf(Label.MppDDCalloutBatchSize));
        } catch(Exception ex) { //If unable to queue the Batch Class then Schedule self  to run after few seconds (configured in Custom Label).
            Datetime sysTime = System.now();
            sysTime = sysTime.addSeconds(Integer.valueOf(Label.JobSchedulerRetryFailureInSeconds));
            String chron_exp = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
            System.debug('############chron_exp#######'+chron_exp);
            MPPBulkPaymentScheduleScheduler  p = new MPPBulkPaymentScheduleScheduler();
            System.schedule('MPPBulkPaymentScheduleScheduler:' + sysTime.getTime(),chron_exp,p);          
        }
    }     
}