src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_of_Offered_Subscriptions__c</fullName>
        <label>Number of Offered Subscriptions</label>
        <summaryFilterItems>
            <field>Subscription__c.Subscription_Status__c</field>
            <operation>equals</operation>
            <value>Offered</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription__c.Subscriber__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Pending_Subscriptions__c</fullName>
        <label>Number of Pending Subscriptions</label>
        <summaryFilterItems>
            <field>Subscription__c.Subscription_Status__c</field>
            <operation>equals</operation>
            <value>Pending</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription__c.Subscriber__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status_calc__c</fullName>
        <label>Subscription Status calc</label>
        <summaryFilterItems>
            <field>Subscription__c.Subscription_Status__c</field>
            <operation>equals</operation>
            <value>Active, In Renewal</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription__c.Subscriber__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>

    
    <fields>
        <fullName>Print_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Subscription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subscription__c.Subscriber__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Zuora Subscription</description>
        <inlineHelpText>Lookup field to Zuora Subscription</inlineHelpText>
        <label>Zuora Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>




</CustomObject>

src/objects/Outbound_Call_Batch_Setting__c.object
<CustomObject>
    <description>Configuration object for batch jobs generating Cases for Outbound Calling</description>
    <fields>
        <fullName>Outbound_Call_Setting__c</fullName>
        <description>Related Outbound Call Setting</description>
        <inlineHelpText>Define Outbound Call Setting Master</inlineHelpText>
        <label>Outbound Call Setting</label>
        <referenceTo>Outbound_Call_Setting__c</referenceTo>
        <relationshipLabel>Outbound Call Batch Settings</relationshipLabel>
        <relationshipName>Outbound_Call_Batch_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>Scope of records</description>
        <inlineHelpText>Define the scope of records to be picked up</inlineHelpText>
        <label>Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Batch Setting</label>
    <nameField>
        <label>Outbound Call Batch Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Batch Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Call_Setting__c.object
<CustomObject>
    <description>Configuration object for Outbound Calling</description>
    <fields>
        <fullName>Default_Queue_Name__c</fullName>
        <description>Default queue name</description>
        <inlineHelpText>Define default queue name</inlineHelpText>
        <label>Default Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outbound Call Setting</label>
    <nameField>
        <label>Outbound Call Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Outbound_Calling_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DD Cancellation</fullName>
                    <default>true</default>
                    <label>DD Cancellation</label>
                </value>
                <value>
                    <fullName>DD Winback</fullName>
                </value>
                <value>
                    <fullName>Outbound Calling (DD Cancellation)</fullName>
                </value>
                <value>
                    <fullName>Outbound Calling (DD Winback)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Outbound Calling Configuration</label>
    <pluralLabel>Outbound Calling Configuration</pluralLabel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Status_Change__c</fullName>
        <label>Last Status Change</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Subscription_Expiry__c</fullName>
        <label>Previous Subscription Expiry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscriptionIncentiveAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MGM Scheme</fullName>
                </value>
                <value>
                    <fullName>Staff Offer</fullName>
                </value>
                <value>
                    <fullName>Renewal Incentive</fullName>
                </value>
                <value>
                    <fullName>Acquisition Incentive</fullName>
                </value>
                <value>
                    <fullName>Goodwill</fullName>
                </value>
                <value>
                    <fullName>TMG Error</fullName>
                </value>
                <value>
                    <fullName>Winback Incentive</fullName>
                </value>
                <value>
                    <fullName>Renewal for TL1</fullName>
                </value>
                <value>
                    <fullName>Renewal for TL2</fullName>
                </value>
                <value>
                    <fullName>Renewal for T2</fullName>
                </value>
                <value>
                    <fullName>Renewal for T2 Catch Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriber Incentives</relationshipLabel>
        <relationshipName>Subscription_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>SubscriptionIncentiveAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Incentive</label>
    <nameField>
        <displayFormat>SIA-{0000000000}</displayFormat>
        <label>SubscriptionIncentiveAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OutboundCallingDDWinbackBatch.cls
/**
* Developer - Vishant Shah
* Date - 05/05/2017
* Description:  Batch to generate DD Winback cases from subscriptions .
*
* ******************* Change Log *******************
* Modified by   Change Date
**/

global class OutboundCallingDDWinbackBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    
    public static final String BATCH_NAME   = OutboundCallingDDWinbackBatch.class.getName();
    public static final Integer ERROR_LIMIT = 20;

    public String errorString = '';

    private Outbound_Call_Batch_Setting__c configRecord;
    private Id recordTypeId;
    private Id schoolRecordTypeId;
    private Id ownerId;
    private Set<String> statusToExclude;
    private Integer errorCount = 0;

    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.1
    Function - Constructor
    #############Change Log#############
    Modified by     Change Date 
    ****************************************************************************************/
    global OutboundCallingDDWinbackBatch() {
        recordTypeId       = RecordTypeUtility.getRecordTypeId(Case.SObjectType, Constants.OC_DD_WINBACK_RECORD_TYPE_NAME, Case.class.getName());
        schoolRecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_SCHOOLS, Subscription__c.class.getName());
        statusToExclude    = new Set<String>();
    }

    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.1
    Function - Batch execution for Schedule. 
    #############Change Log#############
    Modified by     Change Date 
    ****************************************************************************************/
    global void execute(SchedulableContext schedulableContext){
        Database.executeBatch(new OutboundCallingDDWinbackBatch());
    }

    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.1
    Function - Define scope for execute, get query from config record if scope set.
    #############Change Log#############
    Modified by     Change Date 
    ****************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        configRecord = OutboundCallingBatchUtils.fetchConfigRecord(BATCH_NAME);
        ownerId      = OutboundCallingBatchUtils.getQueueId(configRecord.Outbound_Call_Setting__r.Default_Queue_Name__c);

        for (Outbound_Calling_Configuration__mdt exclusionReasons : [SELECT Reason__c FROM Outbound_Calling_Configuration__mdt WHERE Project__c = :Constants.OC_DD_WINBACK_RECORD_TYPE_NAME]){
            statusToExclude.add(exclusionReasons.Reason__c);
        }

        if(configRecord.Scope__c != null) {
            return Database.getQueryLocator(configRecord.Scope__c);
        } else {
            return Database.getQueryLocator([SELECT Previous_Subscription_Expiry__c, Subscriber__c,
                                                    (SELECT Id FROM Cases__r WHERE RecordTypeId = :recordTypeId), 
                                                    (SELECT Subscription__c FROM SubscriptionIncentiveAssociations__r) 
                                               FROM Subscription__c
                                              WHERE Subscription_Status__c = :Constants.SUBSCRIPTION_PENDING_CANCELLATION_STATUS
                                                AND Last_Status_Change__c = LAST_WEEK
                                                AND Subscriber__r.Subscription_Status_calc__c = 0               // NO Active OR InRenewal Subs 
                                                AND Subscriber__r.Number_of_Offered_Subscriptions__c = 0        // NO Offered Subs
                                                AND Subscriber__r.Number_of_Pending_Subscriptions__c = 0        // NO Pending Subs
                                                AND RecordTypeId != :schoolRecordTypeId
                                                AND Cancellation_Method__c != 'Phone'
                                                AND Cancellation_Reason__c NOT IN :statusToExclude
                                                AND (Subscriber__r.Phone != null OR 
                                                     Subscriber__r.PersonMobilePhone != null OR 
                                                     Subscriber__r.PersonHomePhone != null)] );
        }
    }

    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.1
    Function - Execute scope for batch
    #############Change Log#############
    Modified by     Change Date 
    ****************************************************************************************/
    global void execute(Database.BatchableContext BC, List<sObject> subscriptions) {
        List<Case> casesToInsert = new List<Case>();

        Case basicCaseRecord = OutboundCallingBatchUtils.populateCaseValues(configRecord.Parameters__c);

        for (Subscription__c sub : (List<Subscription__c>)subscriptions){

            if(sub.Cases__r.size() == 0){
                Case insertCase = OutboundCallingBatchUtils.createCaseRecord(basicCaseRecord, sub, recordTypeId, ownerId);
                casesToInsert.add(insertCase); 
            }
        }

        if(!casesToInsert.isEmpty()){

            configRecord.Last_Execution_Error__c = false;

            List<Database.SaveResult> insertResults = Database.insert(casesToInsert, false);
            
            for(Integer i = 0; i < insertResults.size(); i++){
                if(!insertResults[i].success){
                    configRecord.Last_Execution_Error__c = true;

                    if(errorCount <= ERROR_LIMIT){
                        errorString += 'Failed to Insert Case, ' + String.valueOf(insertResults[i].errors) + '/n';
                        errorCount++;
                    }
                }
            }
        }
    }
    
    
    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.1
    Function - log errors in finish method against the batch record.
    #############Change Log#############
    Modified by     Change Date 
    ****************************************************************************************/
    global void finish(Database.BatchableContext BC) {
        try {
            if(configRecord.Executions__c == null){
                configRecord.Executions__c = 1;
            } else {
                configRecord.Executions__c = configRecord.Executions__c + 1;
            }

            if(configRecord.Last_Execution_Error__c != null && configRecord.Last_Execution_Error__c) {
                configRecord.Batch_Job_Notifications__c = errorString;
            }
            
            update configRecord;
        } catch (Exception e) {
            throw new TelegraphApplicationException('OutboundCallingDDWinbackBatch error : ' + e.getMessage());
        }
    }
    
}