src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Home_Delivery_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Delivery Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POC__c</fullName>
        <externalId>true</externalId>
        <label>POC</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Plan__c</fullName>
        <label>Price Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan 0</fullName>
                </value>
                <value>
                    <fullName>Plan 1</fullName>
                    <default>true</default>
                    <label>Plan 1</label>
                </value>
                <value>
                    <fullName>Plan 2</fullName>
                </value>
                <value>
                    <fullName>Plan 3</fullName>
                </value>
                <value>
                    <fullName>Plan 4</fullName>
                </value>
                <value>
                    <fullName>Plan 5</fullName>
                </value>
                <value>
                    <fullName>Plan S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RET_ID__c</fullName>
        <externalId>true</externalId>
        <label>RET ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer_Active_Sub_Count__c</fullName>
        <label>Retailer Active Sub Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>This is the Vanity title field. (Lord, Lady, Sir etc.)</inlineHelpText>
        <label>Given Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POC__c.object
<CustomObject>
    <description>This contains the POC weekly data provided by Sub Management team</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpiryDate__c</fullName>
        <description>Date that the POC offer expires</description>
        <label>ExpiryDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HiddenPOCPrice__c</fullName>
        <description>The data entered is in the form of text ie: £4.23, with the £. So need to enter the data in as text and then in the trigger remove £ and enter in the decimal field POC_Price__c</description>
        <label>HiddenPOCPrice</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POC_ID__c</fullName>
        <description>The POC unique identifier code</description>
        <label>POC_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>POC and post code are minimum details used to sign in so both are required</description>
        <label>PostalCode</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_Line_2__c</fullName>
        <description>This field is not shown at front end and is concatonated to Street field</description>
        <label>Street Address Line 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <label>Subscriber Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>POC</label>
    <nameField>
        <label>POC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Plan__c.object
<CustomObject>
    <description>Defines upgrade/downgrade options for products and pricing. Used for both old print world renewals and Zuora world flexible pricing.</description>
    <fields>
        <fullName>Price_Plan__c</fullName>
        <label>Price Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Plan 0</fullName>
                </value>
                <value>
                <fullName>Plan 1</fullName>
                </value>
                <value>
                <fullName>Plan 2</fullName>
                </value>
                <value>
                <fullName>Plan 3</fullName>
                </value>
                <value>
                <fullName>Plan 4</fullName>
                </value>
                <value>
                <fullName>Plan 5</fullName>
                </value>
                <value>
                <fullName>Plan S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Plan</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Price Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Asset_Calc__c</fullName>
        <description>Trigger calculated value of the deferred asset value for this subscription</description>
        <label>Asset Calculation Value (Hidden)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>HND</fullName>
                </value>
                <value>
                <fullName>OTC</fullName>
                <default>true</default>
                    <label>OTC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Liab_Calc__c</fullName>
        <description>Trigger calculated value of the deferred liability for this subscription</description>
        <label>Liability Calculation Value (Hidden)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Details_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Details Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Plan__c</fullName>
        <formula>Case(Subscriber__r.Price_Plan__c,

&quot;Plan 0&quot;,&quot;Plan 0&quot;,
&quot;Plan 1&quot;,&quot;Plan 1&quot;,
&quot;Plan 2&quot;,&quot;Plan 2&quot;,
&quot;Plan 3&quot;,&quot;Plan 3&quot;,
&quot;Plan 4&quot;,&quot;Plan 4&quot;,
&quot;Plan 5&quot;,&quot;Plan 5&quot;,
&quot;Plan 6&quot;,&quot;Plan 6&quot;,
&quot;Plan 7&quot;,&quot;Plan 7&quot;,
&quot;Plan 8&quot;,&quot;Plan 8&quot;,
&quot;Plan 9&quot;,&quot;Plan 9&quot;,
&quot;Plan S&quot;,&quot;Plan S&quot;,
&quot;Plan 1&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pricing Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Please select a retailer that has not closed.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Retailer Account</value>
            </filterItems>
            <filterItems>
                <field>Account.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, TMG System</value>
            </filterItems>
            <infoMessage>Closed retailers are still valid accounts for System Administrator and TMG System profiles.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Picklist__c</fullName>
        <label>Subscription Duration (Weeks)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>26</fullName>
                </value>
                <value>
                <fullName>52</fullName>
                <default>true</default>
                    <label>52</label>
                </value>
                <value>
                <fullName>13</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Voucher_Pack_Duration__c</fullName>
        <defaultValue>13</defaultValue>
        <description>Used to record if the subscription has 12 or 13 week voucher packs</description>
        <label>Voucher Pack Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weekly_Price__c</fullName>
        <label>Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UtilitiesForSubscriptionsTest.cls
/**
* @author Unknown
* @date Unknown
* @description test class for UtilitiesForSubscriptions
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         04/11/2016  //cleaned-up a bit, uncommented assertions, added one method
**/
@isTest(SeeAllData=false)
private class UtilitiesForSubscriptionsTest {

    private static testmethod void testcreateEmailAttachment(){
        List<Messaging.Emailfileattachment> testattach = UtilitiesForSubscriptions.createEmailAttachment('this is a test','test.csv');
        System.assertNotEquals(null,testattach.size());
        System.assertEquals(null,UtilitiesForSubscriptions.createEmailAttachment(null,'test.csv'));
    }

    private static testmethod void testgenerateUniqueFileName(){
        String fl = UtilitiesForSubscriptions.generateUniqueFileName('test','csv');
        System.assertEquals(true,fl.contains('test'));
        System.assertEquals(true,fl.contains('csv'));
    }

    private static testmethod void testUtilitiesForSubscriptions(){
        String secureVal = UtilitiesForSubscriptions.CreateSecureValue('abcdefg');
        System.assertEquals('abcdefg',UtilitiesForSubscriptions.GetSecureValue(secureVal));
        System.assertEquals('',UtilitiesForSubscriptions.GetSecureValue(null));
        System.assertEquals('',UtilitiesForSubscriptions.CreateSecureValue(null));
    }

    private static testmethod void testGetRetailer(){
        Id retailerID = UtilityLookupSubscriptionVariables.getRecordType('Retailer Account');
        Account testPersonAccount = new Account(Home_Delivery_Accepted__c = true,Name='testPersonAccount',Price_Plan__c='B');    
        Account testRetailAccount = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount',BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RFXX',RecordTypeID=retailerID, Retailer_Active_Sub_Count__c=1);
        Account [] testAccounts = new Account []{testPersonAccount, testRetailAccount};
        try{ 
            insert testAccounts;
        }catch(Exception ex){}
        Date stDate = UtilitySelectOptionsSubscriptions.getFirstStartDate(5);//didnt use SubscriptionPaymentUtils because it requires to send a created subscription to the constructor which then creates a DD attached to the Sub
        
        Subscription__c testSubFullDD = new Subscription__c(Subscriber__c=testPersonAccount.ID, Retailer__c=testRetailAccount.ID,  Weekly_Price__c=219.11, Subscription_Status__c='Offered', Subscription_Duration_Picklist__c='52', Start_Date__c=stDate, Pricing_Error__c=false, Delivery_Type__c='HND', Payment_Details_Received__c=true, Payment_Type__c='Direct Debit', Voucher_Pack_Duration__c=13, Asset_Calc__c=0, Liab_Calc__c = 0);
        try{ 
            insert testSubFullDD;
        }catch(Exception ex){}
        
        testSubFullDD.Subscription_Status__c='Active';
        update testSubFullDD;
            
        UtilitiesForSubscriptions subUtils = new UtilitiesForSubscriptions();
        subUtils.getRetailer('SW23 4RFX',true);
        System.assertEquals(1,subUtils.activeRetailerAccounts.size());
        System.assertEquals('1 TEST RD',subUtils.activeRetailerAccounts[0].BillingStreet);
        
        subUtils.activeRetailerAccounts.clear();
        subUtils.RetrieveRetailers('SW23 4RFX',true);
        System.assertEquals(1,subUtils.allActiveRetailers.size());
        System.assertEquals('1 TEST RD',subUtils.activeRetailerAccounts[0].BillingStreet);
        
        subUtils.activeRetailerAccounts.clear();
        subUtils.getRetailer('',true);
        System.assertEquals(0,subUtils.activeRetailerAccounts.size());

        subUtils.activeRetailerAccounts.clear();
        subUtils.getRetailer(null,true);
        System.assertEquals(0,subUtils.activeRetailerAccounts.size());

        subUtils.getRetailer('SW23 4RFX',false);
    }  
        
    private static testmethod void testQualifyAgency(){
        List<SubManagementDefaults__c> subs1 = [Select ID__c,DefaultValue__c From SubManagementDefaults__c where ID__c='Agencies'];
        if (subs1.size() == 0){
            SubManagementDefaults__c newSubManagementDefaults = new SubManagementDefaults__c(ID__c='Agencies',DefaultValue__c='TMG,BPS');
            try{ 
                insert newSubManagementDefaults;
            }catch(Exception ex){}
        }
        else{
            subs1[0].DefaultValue__c ='TMG,BPS';
            update subs1;
        }
        System.assertEquals(TRUE,UtilitiesForSubscriptions.qualifyAgency('TMG'));
        System.assertEquals(FALSE,UtilitiesForSubscriptions.qualifyAgency('XYZ'));          
    }

    private static testmethod void testFormatPostCode(){
        System.assertEquals('SW12 3ED',UtilitiesForSubscriptions.formatPostCode('SW123ED'));
        System.assertEquals('SW1 3ED',UtilitiesForSubscriptions.formatPostCode('SW13ED'));
        System.assertEquals('SW12 3ED',UtilitiesForSubscriptions.formatPostCode('S W 1 2 3 E D'));
        System.assertEquals('SW1A 3ED',UtilitiesForSubscriptions.formatPostCode('SW1A3ED'));
        System.assertEquals('',UtilitiesForSubscriptions.formatPostCode(''));
    }

    private static testmethod void testConvertBooleanToInteger(){
        System.assertEquals(1,UtilitiesForSubscriptions.convertBooleanToInteger(true)); 
        System.assertEquals(0,UtilitiesForSubscriptions.convertBooleanToInteger(false));
    }

    private static testmethod void TestgetPositionInList(){
        Id retailerID = UtilityLookupSubscriptionVariables.getRecordType('Retailer Account');
        Account testPersonAccount = new Account(Home_Delivery_Accepted__c = true,Salutation='Mr', FirstName='test',LastName='test this',PersonMailingStreet='1 test street',Price_Plan__c='B');    
        Account testPersonAccount2 = new Account(Home_Delivery_Accepted__c = true,Salutation='Mr', FirstName='test',LastName='test this',PersonMailingStreet='1 test street',Price_Plan__c='B');    
        Account testRetailAccount1 = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount1', BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RF',RecordTypeID=retailerID, Retailer_Active_Sub_Count__c=1);
        Account testRetailAccount2 = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount2', BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 9RF',RecordTypeID=retailerID, Retailer_Active_Sub_Count__c=1);
        Account [] testAccounts = new Account []{testPersonAccount, testPersonAccount2, testRetailAccount1, testRetailAccount2};
        try{ insert testAccounts;
        }catch(Exception ex){}
        Date stDate = UtilitySelectOptionsSubscriptions.getFirstStartDate(5);//didnt use SubscriptionPaymentUtils because it requires to send a created subscription to the constructor which then creates a DD attached to the Sub
            
        Subscription__c testSubFullDD = new Subscription__c(Subscriber__c=testPersonAccount.ID, Retailer__c=testRetailAccount1.ID,  Weekly_Price__c=219.11, Subscription_Status__c='Offered', Subscription_Duration_Picklist__c='52', Start_Date__c=stDate, Pricing_Error__c=false, Delivery_Type__c='HND', Payment_Details_Received__c=true, Payment_Type__c='Direct Debit', Voucher_Pack_Duration__c=13, Asset_Calc__c=0, Liab_Calc__c = 0);
        try{ 
            insert testSubFullDD;
        }catch(Exception ex){}
            
        Subscription__c testSubFullDD2 = new Subscription__c(Subscriber__c=testPersonAccount2.ID, Retailer__c=testRetailAccount2.ID,  Weekly_Price__c=219.11, Subscription_Status__c='Offered', Subscription_Duration_Picklist__c='52', Start_Date__c=stDate, Pricing_Error__c=false, Delivery_Type__c='HND', Payment_Details_Received__c=true, Payment_Type__c='Direct Debit', Voucher_Pack_Duration__c=13, Asset_Calc__c=0, Liab_Calc__c = 0);
        try{ 
            insert testSubFullDD2;
        }catch(Exception ex){}
            
        testSubFullDD.Subscription_Status__c='Active';
        update testSubFullDD;
            
        testSubFullDD2.Subscription_Status__c='Active';
        update testSubFullDD2;
            
        UtilitiesForSubscriptions subUtils = new UtilitiesForSubscriptions();
        subutils.retrieveRetailers('SW23',true);
        integer pos = subUtils.getPositionInList('SW23 4RF');
        System.assertEquals(0,pos);
        pos = subUtils.getPositionInList('SW23 9RF');
        System.assertEquals(1,pos);
        
    }

    private static void setUpRetailerAccountsAndSubs(){ 
        Account testPersonAccount = new Account(Home_Delivery_Accepted__c = true,LastName='testPersonAccount',Price_Plan__c='B');  
        try{ insert testPersonAccount;
        }catch(Exception ex){}
 
        Id retailerID = UtilityLookupSubscriptionVariables.getRecordType('Retailer Account');
        Account testRetailAccount = new Account(Home_Delivery_Accepted__c = true,name='testRetailAccount',RET_ID__c='99999999',BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RF',Retailer_Active_Sub_Count__c=1,RecordTypeID=retailerID);
        try{ insert testRetailAccount;
        }catch(Exception ex){}
        Date stDate = UtilitySelectOptionsSubscriptions.getFirstStartDate(5);//didnt use SubscriptionPaymentUtils because it requires to send a created subscription to the constructor which then creates a DD attached to the Sub
        Subscription__c testSubFullDD = new Subscription__c(Subscriber__c=testPersonAccount.ID, Retailer__c=testRetailAccount.ID,  Weekly_Price__c=219.11, Subscription_Status__c='Offered',Subscription_Duration_Picklist__c='52', Start_Date__c=stDate, Pricing_Error__c=false, Delivery_Type__c='HND', Payment_Details_Received__c=true, Payment_Type__c='Direct Debit', Voucher_Pack_Duration__c=13, Asset_Calc__c=0, Liab_Calc__c = 0);
        try{ insert testSubFullDD;
        }catch(Exception ex){}
        testSubFullDD.Subscription_Status__c='Active';
        update testSubFullDD;
    }  

    private static testmethod void testfastRetrieveRetailers(){
        setUpRetailerAccountsAndSubs();
        UtilitiesForSubscriptions subUtils = new UtilitiesForSubscriptions();
        subUtils.fastRetrieveRetailers(null,true);  
        subUtils.fastRetrieveRetailers('SW23',true);
        setUpRetailerAccountsAndSubs();
        subUtils.fastRetrieveRetailers('SW23',false);
    }

    private static testmethod void testRetrieveRetailers(){
        setUpRetailerAccountsAndSubs();
        UtilitiesForSubscriptions subUtils = new UtilitiesForSubscriptions();
        
        subUtils.retrieveRetailers(null,true);
        UtilitiesForSubscriptions subUtils2 = new UtilitiesForSubscriptions();
        subUtils2.retrieveRetailers('SW23',true);
        System.assertEquals(1,subUtils2.allActiveRetailers.size());
        System.assertEquals(true,subUtils2.displayRetailers);
        System.assertEquals('1 TEST RD',subUtils2.activeRetailerAccounts[0].BillingStreet);
    }

    private static testmethod void testGetRetailerFromRETID(){
        Account testRetailAccount = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount',BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RF',ret_id__c='11122');
        try{ insert testRetailAccount;
        }catch(Exception ex){}
        Account accRet = UtilitiesForSubscriptions.getRetailerFromRETID(testRetailAccount.RET_ID__c);
        System.assertEquals('testRetailAccount',accRet.Name);
        accRet = UtilitiesForSubscriptions.getRetailerFromRETID('xxxs');
        System.assertEquals(null, accRet);
    }

    private static testmethod void testReturnSelectedRetailerID(){
        Account testRetailAccount = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount',BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RF',ret_id__c='11122');
        try{ insert testRetailAccount;
    }catch(Exception ex){}
        Account retName = UtilitiesForSubscriptions.returnSelectedRetailerWithoutError('11122');
        list<Account> retailerAccs = [select Name From Account where ret_id__c='44442256']; 
        if (retailerAccs.size() >0)
            delete retailerAccs;
        retName = UtilitiesForSubscriptions.returnSelectedRetailerWithoutError('44442256');
        System.assertEquals(null,retName);
    }

    private static testmethod void testGetRetailerAcc(){
        Account testRetailAccount = new Account(Home_Delivery_Accepted__c = true,Name='testRetailAccount',BillingStreet='1 TEST RD',BillingCity='TEST CITY',BillingPostalCode='SW23 4RF',ret_id__c='11122');
        try{ insert testRetailAccount;
        }catch(Exception ex){}

        Account NameOfAcc = UtilitiesForSubscriptions.getRetailerAcc(String.valueof(testRetailAccount.id));
        System.assertEquals(testRetailAccount.Name,NameOfAcc.Name);
        
        NameOfAcc = UtilitiesForSubscriptions.getRetailerAcc(null);
        System.assertEquals(null,NameOfAcc);
        
    }

    private static testmethod void testCreateSecureValue(){
        String encryptVal = UtilitiesForSubscriptions.createSecureValue('4.00');
        System.assertEquals('4.00',UtilitiesForSubscriptions.getSecureValue(encryptVal));
    }

    private static testmethod void testCopyPOCToAccount(){
        Date EnterDate =  date.today().toStartofWeek().addDays(21);
        POC__c POCTEST1 = new POC__c(POC_ID__c='7013112124',Country__c='UK',State__c='',Street_Address_Line_2__c='Tottenham',HiddenPOCPrice__c='£4.00',City__c='london',Street__c='36 Conyers',title__c='Mr',PostalCode__c = 'SW17 7KQ', FirstName__c ='Steve S', LastName__c = 'Fouracre', ExpiryDate__c=EnterDate);

        Account newAcc = UtilitiesForSubscriptions.copyPOCToAccount(POCTEST1);
        System.assertEquals('7013112124',newAcc.POC__c);    
        System.assertEquals('36 Conyers',newAcc.PersonMailingStreet);   
    }

    private static testmethod void testCopyLapsedAccountToNewAccount(){
        Account testPersonAccount = new Account(Home_Delivery_Accepted__c = true,Salutation='Mr',FirstName='test',LastName='test this',PersonMailingStreet='1 test street',Price_Plan__c='B');    
        try{ insert testPersonAccount;
        }catch(Exception ex){}
        
        Account acc = [Select Salutation,FirstName,LastName,PersonMailingStreet,Subscriber_Number_static__c From Account where FirstName='test' and LastName='test this' limit 1];
        
        Account newAcc = UtilitiesForSubscriptions.copyLapsedAccountToNewAccount(acc.Subscriber_Number_static__c);
        System.assertEquals('1 test street',newAcc.PersonMailingStreet);    
        System.assertEquals('test this',newAcc.LastName);
        System.assertEquals(null,UtilitiesForSubscriptions.copyLapsedAccountToNewAccount('78667768'));  

    }

    private static testmethod void testConvertToTwoDecimalPlaces(){
        String retval = UtilitiesForSubscriptions.convertToTwoDecimalPlaces(4);
        System.assertEquals('4.00',UtilitiesForSubscriptions.convertToTwoDecimalPlaces(4)); 
        Double sentval = 4.002;
        System.assertEquals('4.00',UtilitiesForSubscriptions.convertToTwoDecimalPlaces(sentval));   
        sentval=4.0022;
        System.assertEquals('4.00',UtilitiesForSubscriptions.convertToTwoDecimalPlaces(sentval));   
        sentval=4.00;
        System.assertEquals('4.00',UtilitiesForSubscriptions.convertToTwoDecimalPlaces(sentval));   
        sentval=4.20;
        System.assertEquals('4.20',UtilitiesForSubscriptions.convertToTwoDecimalPlaces(sentval));   
    }

    /***************************************************************************************
    Developer - Wiktor Czykin
    Date - 04/11/2016
    Version - 1.0
    Function - test poc mapping onto account instance where existing account is found based on tsnumber
    #############Change Log#############
    Modified by    Version   Change Date
    ****************************************************************************************/
    private static testMethod void testCopyPOCToAccountBasedOnTsNumber(){
        TestDataUtility td = new TestDataUtility(1);
        td.createIndividualSubscribers();
        td.createPocs(1);
        List<Account> lstAcc = [select Id, Subscriber_Number__c from Account where Id in :td.lstIndividualSubscribers];
        System.assert(!lstAcc.isEmpty());
        POC__c p = td.mapTCodeManagementToPOCs.get(td.lstTCodeManagement[0].Id)[0];
        p.Subscriber_Number__c = lstAcc[0].Subscriber_Number__c;
        update p;
        Test.startTest();
            Account acc = UtilitiesForSubscriptions.copyPOCToAccount(p);
            System.assertEquals(td.lstIndividualSubscribers[0].PersonEmail, acc.PersonEmail);
            System.assertEquals(lstAcc[0].Subscriber_Number__c, acc.Subscriber_Number_static__c);
            System.assertEquals(p.PostalCode__c, acc.PersonMailingPostalCode);
        Test.stopTest();
    }

    /***************************************************************************************
    Developer - Wiktor Czykin
    Date - 04/11/2016
    Version - 1.0
    Function - test poc mapping onto account instance where existing account is found based on email
    #############Change Log#############
    Modified by    Version   Change Date
    ****************************************************************************************/
    private static testMethod void testCopyPOCToAccountBasedOnEmail(){
        TestDataUtility td = new TestDataUtility(1);
        td.createIndividualSubscribers();
        td.createPocs(1);
        List<Account> lstAcc = [select Id, PersonEmail, Subscriber_Number__c from Account where Id in :td.lstIndividualSubscribers];
        System.assert(!lstAcc.isEmpty());
        POC__c p = td.mapTCodeManagementToPOCs.get(td.lstTCodeManagement[0].Id)[0];
        p.Email__c = lstAcc[0].PersonEmail;
        update p;
        Test.startTest();
            Account acc = UtilitiesForSubscriptions.copyPOCToAccount(p);
            System.assertEquals(td.lstIndividualSubscribers[0].PersonEmail, acc.PersonEmail);
            System.assertEquals(lstAcc[0].Subscriber_Number__c, acc.Subscriber_Number_static__c);
            System.assertEquals(p.PostalCode__c, acc.PersonMailingPostalCode);
        Test.stopTest();
    }
}