src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsUsingMPP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Accout using MPP as Payment Provider?</description>
        <inlineHelpText>Is this Accout using MPP as Payment Provider?</inlineHelpText>
        <label>Is Using MPP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Is_MPP_DDCCA_Letter_Extracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is used by batch apex to determine whether the MPP_DDCCA letter is sent to the customer or not. This flag is only editable by the apex job.</description>
        <inlineHelpText>If this flag is checked, then the automated batch process has added this letter to the MPP_DDCCA csv file sent to the fulfillment team for the creation of DD/CCA letters.</inlineHelpText>
        <label>Is MPP DDCCA Letter Extracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MPP_CC_Frequency__c</fullName>
        <label>MPP CC Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_Premium_Subscription_ID__c</fullName>
        <description>External ID for premium subscriptions stored in MPP.</description>
        <externalId>true</externalId>
        <label>MPP Premium Subscription ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MPPLetterExtractDDCCABatchTest.cls
/**
* @author Unknown
* @date Unknown
* @description Test class for MPPLetterExtractDDCCABatch class
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin	1.1			18/11/2015	//rewritten
Wiktor Czykin	1.2			09/02/2016	//modified testBatchPositiveFlow()
**/
@isTest
private class MPPLetterExtractDDCCABatchTest {
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 18/11/2015
    Version - 1.1
    Function - Positive flow test
    #############Change Log#############
    Modified by     Version     Change Date
    Wiktor Czykin	1.1			09/02/2016	//added matching TSNumber to the xml response
    ****************************************************************************************/
	private static testMethod void testBatchPositiveFlow(){
		TestDataUtility td = new TestDataUtility(1);
		td.createSubscriptions();
		for(Account acc : td.lstIndividualSubscribers){
			acc.IsUsingMPP__c = true;
		}
		update td.lstIndividualSubscribers;
		
		for(Subscription__c sub : td.lstSubscriptions){
			sub.Subscription_Status__c = Constants.SSTATUS_OFFERED;
			sub.Is_MPP_DDCCA_Letter_Extracted__c = false;
			sub.isContinuous__c = true;
	   		sub.MPP_CC_Frequency__c = Constants.DD_COL_FREQ_MONTHLY;
	   		sub.Payment_Type__c = Constants.SUB_PMETHOD_CC;
			sub.MPP_Premium_Subscription_ID__c = '174764';//this has to match whatever is set in MPPWebserviceMocks response
		}
		update td.lstSubscriptions;
		List<Account> lstAccount = [select Id, Subscriber_Number__c from Account where Id = :td.lstIndividualSubscribers[0].Id];
		System.assert(!lstAccount.isEmpty() && lstAccount[0].Subscriber_Number__c != null);

		
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mock = new MPPWebserviceMocks.MPPHttpResponseGenerator(	td.lstPlaneURL[0].baseURL__c, 
																												new Map<String,String>{MPPWebserviceMocks.PARAM_TS1 => lstAccount[0].Subscriber_Number__c
																													});
            MPPInterfaceHTTP.bRunTest = true;
            Test.setMock(HttpCalloutMock.class, mock); 
			MPPLetterExtractDDCCABatch batch = new MPPLetterExtractDDCCABatch(	Constants.SUB_ACQUISITION_PAYMENT_CC, 
																				'CC_CSV', 
																				MPPLetterExtractDDCCABatch.FILTERTYPE_RECORDTYPE,
										 										MPPLetterExtractData.getMPP_CCA_BatchQuery(), 
										 										'amir.hafeez@telegraph.co.uk', 
										 										'amir.hafeez@telegraph.co.uk', 
										 										'amir.hafeez@telegraph.co.uk');
			Id batchId = Database.executeBatch(batch, td.iCounter);
		Test.stopTest();
		
		System.assertNotEquals(batchId, null);
		List<Subscription__c> subList = [SELECT Id, Is_MPP_DDCCA_Letter_Extracted__c FROM Subscription__c WHERE Id IN :td.lstSubscriptions];
		for(Subscription__c s :subList){
			System.assertEquals(true, s.Is_MPP_DDCCA_Letter_Extracted__c);
		}
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 18/11/2015
    Version - 1.0
    Function - Negative flow test - mpp error returned
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testBatchNegativeFlowMPPError(){
		TestDataUtility td = new TestDataUtility(1);
		td.createSubscriptions();
		for(Account acc : td.lstIndividualSubscribers){
			acc.IsUsingMPP__c = true;
		}
		update td.lstIndividualSubscribers;
		
		for(Subscription__c sub : td.lstSubscriptions){
			sub.Subscription_Status__c = Constants.SSTATUS_OFFERED;
			sub.Is_MPP_DDCCA_Letter_Extracted__c = false;
			sub.isContinuous__c = true;
	   		sub.MPP_CC_Frequency__c = Constants.DD_COL_FREQ_MONTHLY;
	   		sub.Payment_Type__c = Constants.SUB_PMETHOD_CC;
			sub.MPP_Premium_Subscription_ID__c = '174764';//this has to match whatever is set in MPPWebserviceMocks response
		}
		update td.lstSubscriptions;
		
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mock = new MPPWebserviceMocks.MPPHttpResponseGenerator(td.lstPlaneURL[0].baseURL__c, new Map<String,String>{MPPWebserviceMocks.PARAM_ISFAILURE=>''});
            MPPInterfaceHTTP.bRunTest = true;
            Test.setMock(HttpCalloutMock.class, mock); 
			MPPLetterExtractDDCCABatch batch = new MPPLetterExtractDDCCABatch(	Constants.SUB_ACQUISITION_PAYMENT_CC, 
																				'CC_CSV', 
																				MPPLetterExtractDDCCABatch.FILTERTYPE_RECORDTYPE,
										 										MPPLetterExtractData.getMPP_CCA_BatchQuery(), 
										 										'amir.hafeez@telegraph.co.uk', 
										 										'amir.hafeez@telegraph.co.uk', 
										 										'amir.hafeez@telegraph.co.uk');
			Id batchId = Database.executeBatch(batch, td.iCounter);
			
			batch.updateQueue(null);//unrelated line just to add coverage for one if
		Test.stopTest();
		
		System.assertNotEquals(batchId, null);
		List<Subscription__c> subList = [SELECT Id, Is_MPP_DDCCA_Letter_Extracted__c FROM Subscription__c WHERE Id IN :td.lstSubscriptions];
		for(Subscription__c s :subList){
			System.assertEquals(false, s.Is_MPP_DDCCA_Letter_Extracted__c);
		}
	}
}