src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <pluralLabel>Products</pluralLabel>    
</CustomObject>

src/classes/SubscriptionProductViewController.cls
/**
* Author:       Wiktor Czykin
* Date:         26/10/2016
* Description:  this class is the constructor for the redirection for Account Payment Management flow
* ******************* Change Log *******************
* Modified by       Change Date
**/
public with sharing class SubscriptionProductViewController {

	private Account acc;
	public Subscription__c oldProduct{get;set;}
	public Subscription__c newestProduct{get;set;}

	/***************************************************************************************
    Developer   Wiktor Czykin
    Date        26/10/2016
    Function    Constructor - retrieve last 2 subscriptions and assign to view variables
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
	public SubscriptionProductViewController(ApexPages.StandardController std){
		Id accId = std.getId();
		if(accId == null){
			throw new TelegraphApplicationException(Label.Account_Product_View_No_id_specified_error);
		}
		List<Account> lstAcc = [select Id from Account where  Id =: accId];
		if(lstAcc.isEmpty()){
			throw new TelegraphApplicationException(Label.Account_Product_View_No_account_for_specified_id_error);
		}
		this.acc = lstAcc[0];

		List<Subscription__c> lstSub = [select 	Id, 
												Name, 
												Subscription_Status__c, 
												Product__c, 
												Product__r.Name  
											from Subscription__c 
											where Subscriber__c = : accId 
											order by End_Date__c desc 
											limit 2];
		if(!lstSub.isEmpty()){
			if(lstSub.size() == 2){
				this.oldProduct =  lstSub[1];
			}
			if(lstSub.size() >= 1){
				this.newestProduct = lstSub[0];
			}
		}
	}
}