src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Within 14 days</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Serious illness</fullName>
                </value>
                <value>
                <fullName>Poor eyesight</fullName>
                </value>
                <value>
                <fullName>Gone Away</fullName>
                </value>
                <value>
                <fullName>Review of personal finances/cannot afford</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Editorial Issues</fullName>
                </value>
                <value>
                <fullName>Too much to read.</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Unpaid Cheque</fullName>
                </value>
                <value>
                <fullName>Duplicate File</fullName>
                </value>
                <value>
                <fullName>Dislike Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Fears Commitment</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved to Care Home</fullName>
                </value>
                <value>
                <fullName>Moving House (UK)</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
                <value>
                <fullName>Unknown</fullName>
                </value>
                <value>
                <fullName>Prefers online content</fullName>
                </value>
                <value>
                <fullName>Independent i</fullName>
                </value>
                <value>
                <fullName>DD Refer to Payer</fullName>
                </value>
                <value>
                <fullName>DD Cancelled by Payer</fullName>
                </value>
                <value>
                <fullName>DD No Instruction</fullName>
                </value>
                <value>
                <fullName>DD Account Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <pluralLabel>Quotes</pluralLabel>
</CustomObject>

src/classes/ZuoraQuoteFlowNextActionOverrideTest.cls
/**
* Author:       Wiktor Czykin
* Date:         10/03/2016
* Description:  test class for ZuoraQuoteFlowNextActionOverride
* ******************* Change Log *******************
* Modified by       Change Date
* Lynette Lim         27-04-2016   Added testOldPrintInRenewalDateValidation()
**/
@isTest
private class ZuoraQuoteFlowNextActionOverrideTest {

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test validation for non registrants
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testErrorForNonRegistrant(){
		TestDataUtility td = new TestDataUtility(1);
		td.createIndividualSubscribers();

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraQuoteFlowNextActionOverride updateController = new ZuoraQuoteFlowNextActionOverride();
			PageReference pr = updateController.doUpdate(new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id), null);
			System.assertEquals(null, pr);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_Non_registrant_account_error));
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test validation for ative old digital subscription
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testErrorForActiveOldDigital(){
		TestDataUtility td = new TestDataUtility(1);
		td.createRegistrants();
		td.lstRegistrants[0].Subscriber_Digital_Status__c = Constants.DIGITAL_SUBSCRIBER_STATUS_ACTIVE;
		update td.lstRegistrants;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstRegistrants[0].Id);
			ZuoraQuoteFlowNextActionOverride updateController = new ZuoraQuoteFlowNextActionOverride();
			PageReference pr = updateController.doUpdate(new zqu__Quote__c(zqu__Account__c = td.lstRegistrants[0].Id), null);
			System.assertEquals(null, pr);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_Active_subscription_error));
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test no error
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testNoError(){
		TestDataUtility td = new TestDataUtility(1);
		td.createRegistrants();
		td.lstRegistrants[0].Subscriber_Digital_Status__c = Constants.DIGITAL_SUBSCRIBER_STATUS_INACTIVE;
		update td.lstRegistrants;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstRegistrants[0].Id);
			ZuoraQuoteFlowNextActionOverride updateController = new ZuoraQuoteFlowNextActionOverride();
			PageReference pr = updateController.doUpdate(new zqu__Quote__c(zqu__Account__c = td.lstRegistrants[0].Id), null);
			System.assertEquals(null, pr);
		Test.stopTest();
	}
	
	
	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test validation activation date has to be at least +1 day cancellation date
	******************* Change Log *******************
	Modified by         Version     Change Date
	*******************************************************************************************/
	private static testMethod void testOldPrintPendingCancellationDateValidation(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkRegistrantAccountDependencies();
		td.createSubscriptions();
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING_CANX;
		td.lstSubscriptions[0].Cancellation_Date__c = td.lstSubscriptions[0].Start_Date__c.addDays(10);
		td.lstSubscriptions[0].Cancellation_Reason__c = 'test';
		td.lstSubscriptions[0].Cancellation_Method__c = 'test';
		update td.lstSubscriptions;
		td.lstIndividualSubscribers[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.ACCOUNT_REGISTRANT_RECORD_TYPE_NAME, Account.class.getName());
		update td.lstIndividualSubscribers;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraQuoteFlowNextActionOverride updateController = new ZuoraQuoteFlowNextActionOverride();
			zqu__Quote__c quote = new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id, zqu__Service_Activation_Date__c = td.lstSubscriptions[0].Cancellation_Date__c );
			PageReference pr = updateController.doUpdate(quote, null);
			System.assertEquals(null, pr);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_Pending_cancellation_print_subscription_to_digital_wrong_date));
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Lynette Lim
	Date        27/04/2016
	Function    Test validation activation date has to be at least +1 day end date
	******************* Change Log *******************
	Modified by         Version     Change Date
	*******************************************************************************************/
	private static testMethod void testOldPrintInRenewalDateValidation(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkRegistrantAccountDependencies();
		td.checkSubscriptionDependencies();
		Subscription__c sub = TestDataUtility.newSubscripiton(0, td.lstIndividualSubscribers[0].Id, td.lstRetailers[0].Id,  UtilitySelectOptionsSubscriptions.getFirstStartDate(5));
		sub.Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
		insert sub;

		sub = [select Id, Start_Date__c, End_Date__c from Subscription__c where Id =:sub.id];

		td.lstIndividualSubscribers[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.ACCOUNT_REGISTRANT_RECORD_TYPE_NAME, Account.class.getName());
		update td.lstIndividualSubscribers;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraQuoteFlowNextActionOverride updateController = new ZuoraQuoteFlowNextActionOverride();
			zqu__Quote__c quote = new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id, zqu__Service_Activation_Date__c = sub.End_Date__c );
			PageReference pr = updateController.doUpdate(quote, null);
			System.assertEquals(null, pr);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_InRenewal_print_subscription_to_digital_wrong_date));
		Test.stopTest();
	}
	
}