src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Order_Taken_Method__c</fullName>
        <label>Order Taken Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RET_ID__c</fullName>
        <externalId>true</externalId>
        <label>RET ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incentive__c.object
<CustomObject>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Low_Start_Amendment_TCode_Helper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to TCode management that is never persisted. Just used as a helper field to find different active low start tcode in the Amend Subscription flow for low start.</description>
        <inlineHelpText>Lookup field to TCode management that is never persisted. Just used as a helper field to find different active low start tcode in the Amend Subscription flow for low start.</inlineHelpText>
        <label>Low Start Amendment TCode Helper</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected tcode is either not Low Start or not a valid one.</errorMessage>
            <filterItems>
                <field>TCodeManagement__c.Type__c</field>
                <operation>equals</operation>
                <value>Low Start</value>
            </filterItems>
            <filterItems>
                <field>TCodeManagement__c.Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions (Low Start Amendment TCode Helper)</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MPP_CC_Frequency__c</fullName>
        <label>MPP CC Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_DD_Frequency__c</fullName>
        <label>MPP DD Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_Premium_Subscription_ID__c</fullName>
        <description>External ID for premium subscriptions stored in MPP.</description>
        <externalId>true</externalId>
        <label>MPP Premium Subscription ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_Method__c</fullName>
        <description>Method of order - populated from Synthesis</description>
        <inlineHelpText>Method of order - populated from Synthesis</inlineHelpText>
        <label>Order Taken Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Outbound</fullName>
                </value>
                <value>
                <fullName>Inbound</fullName>
                </value>
                <value>
                <fullName>Coupon</fullName>
                </value>
                <value>
                <fullName>Auto Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <description>1 or 15 of each month</description>
        <label>Payment Date</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Please select a retailer that has not closed.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Retailer Account</value>
            </filterItems>
            <filterItems>
                <field>Account.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, TMG System</value>
            </filterItems>
            <infoMessage>Closed retailers are still valid accounts for System Administrator and TMG System profiles.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Number__c</fullName>
        <formula>IF(Subscription_Duration_Number_Override__c = 0, CASE(Subscription_Duration_Picklist__c, &quot;6&quot;, 6, &quot;10&quot;, 10, &quot;12&quot;, 12, &quot;13&quot;, 13, &quot;24&quot;, 24, &quot;26&quot;, 26, &quot;36&quot;, 36, &quot;39&quot;, 39, &quot;40&quot;, 40, &quot;44&quot;, 44, &quot;48&quot;, 48, &quot;52&quot;, 52, &quot;96&quot;, 96, &quot;156&quot;, 156, 0), Subscription_Duration_Number_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Duration (Weeks) - Hidden</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reltionship to the Tcode object</description>
        <label>TCodeManagement</label>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscriptionIncentiveAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Incentive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select only valid incentives.</errorMessage>
            <filterItems>
                <field>Incentive__c.Validity_Status__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incentive__c</referenceTo>
        <relationshipLabel>Subscription Incentives</relationshipLabel>
        <relationshipName>SubscriptionIncentiveAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriber Incentives</relationshipLabel>
        <relationshipName>Subscription_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>SubscriptionIncentiveAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Incentive</label>
    <nameField>
        <displayFormat>SIA-{0000000000}</displayFormat>
        <label>SubscriptionIncentiveAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TCodeManagement__c.object
<CustomObject>
    <description>This details the t-code, description, price, if the t-code is still valid and incentive related to the t-code</description>
    <fields>
        <fullName>Incentive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive</label>
        <referenceTo>Incentive__c</referenceTo>
        <relationshipLabel>TCodesManagement</relationshipLabel>
        <relationshipName>TCodesManagement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Allow One Off 13 Week</fullName>
                </value>
                <value>
                <fullName>Allow One Off 26 Week</fullName>
                </value>
                <value>
                <fullName>Allow One Off 52 Week</fullName>
                </value>
                <value>
                <fullName>Allow 13 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 13 Week CCA</fullName>
                </value>
                <value>
                <fullName>Allow 26 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 26 Week CCA</fullName>
                </value>
                <value>
                <fullName>Allow 52 Week DD</fullName>
                </value>
                <value>
                <fullName>Allow 52 Week CCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <label>TCode</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>TCodeManagement</label>
    <nameField>
        <label>TCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCodesManagement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LowStartSubscriptionRestartController.cls
/**
* @author Wiktor Czykin
* @date 27/10/2015
* @description Controller for low start subscription button - subscription restart - the only way to modify the start date
#############Change Log#############
Modified by     Version     Change Date
**/
public with sharing class LowStartSubscriptionRestartController {
	
	@TestVisible private Boolean bTestFail = false;
	@TestVisible private Subscription__c subscription{get;set;}
	public Subscription__c subscriptionTemp{get;set;}
	public Boolean bPastSubscriptionWarning{get;set;}
	public String sError{get;set;}
	public Boolean bChangeOffer{get;set;}
	public Boolean bShowFeature{get;set;}
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 27/10/2015
    Version - 1.0
    Function - Constructor - just fetch the record 
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public LowStartSubscriptionRestartController(ApexPages.StandardController ctrl){
		Id subscriptionId = ctrl.getId();
		if(subscriptionId == null) throw new TelegraphApplicationException(Label.Low_Start_Restart_feature_missing_subscription_id);
		this.subscriptionTemp = new Subscription__c();
		this.bChangeOffer = false;
		this.bPastSubscriptionWarning = false;
		this.bShowFeature = true;
		Set<String> setExtraFields = new Set<String>{	'TCode__r.Name',
														'Retailer__r.RET_ID__c',
														'Subscriber__r.Subscriber_Number__c'};
		String sQuery = 'select ' + GlobalQueries.generateFieldsListForQuery(Subscription__c.class.getName(), setExtraFields, null) + ' from Subscription__c where Id =:subscriptionId';
		List<Subscription__c> lstSubscription = Database.query(sQuery);
		if(lstSubscription.isEmpty()) throw new TelegraphApplicationException(Label.Low_Start_Restart_feature_no_subscription_based_on_id);
		
		this.subscription = lstSubscription[0];
		//hacky way to validate extraction date - without code duplication. Basically we are simulating attempt to change the start date. If it turn out that 
		Subscription__c cloneToValidate = this.subscription.clone(true, true);
		cloneToValidate.Start_Date__c = Date.today().addYears(-10);
		SubscriptionTriggerHandler.getInstance().startDateValidation(new List<Subscription__c>{cloneToValidate}, new Map<Id, Subscription__c>{this.subscription.Id => this.subscription});
		if(ApexPages.hasMessages()){
			bPastSubscriptionWarning = true;
		}
		
		if(RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName()) != this.subscription.RecordTypeId 
		|| this.subscription.Subscription_Status__c != Constants.SSTATUS_PENDING 
		|| !this.subscription.isContinuous__c 
		|| this.subscription.Previous_Subscription__c != null){
			this.bShowFeature = false;
			this.sError = Label.Low_Start_Feature_validation_required_status;
			
		}else if(String.isBlank(this.subscription.MPP_Premium_Subscription_ID__c)){
			this.bShowFeature = false;
			this.sError = Label.Low_Start_Feature_validation_MPP_Subscription_Id_mandatory;
		}
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 27/10/2015
    Version - 1.0
    Function - method that does the actual redirection
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public PageReference processRestart(){
		PageReference pr = null;
		try{
			MPPInterfaceHTTP mppInterface = new MPPInterfaceHTTP();
			mppInterface.cancelPaymentSchedule(this.subscription.MPP_Premium_Subscription_ID__c);
		}catch(Exception e){
			this.sError = Label.Low_Start_Restart_feature_MPP_call_failure +' '+ e.getMessage();
			return pr;
		}
		
		Savepoint sp = Database.setSavepoint();
		try{
			this.subscription.Subscription_Status__c = Constants.SSTATUS_OFFERED;
			update this.subscription;
				
			//fetch subscription incentives records and delete them afterwars
			List<SubscriptionIncentiveAssociation__c> lstSubscriptionIncentives = [select Id, Incentive__c from SubscriptionIncentiveAssociation__c where Subscription__c =:this.subscription.Id];
			Id incentiveId = null;
			if(!lstSubscriptionIncentives.isEmpty()){
				incentiveId = lstSubscriptionIncentives[0].Incentive__c;
			}
			delete lstSubscriptionIncentives;
			
			String sPaymentMethod = Constants.SUB_ACQUISITION_PAYMENT_DD;
			if(this.subscription.Payment_Type__c == Constants.SUB_PMETHOD_CC){
				sPaymentMethod = Constants.SUB_ACQUISITION_PAYMENT_CC;
			}
			//build url parameters
			pr = Page.OapSubscriptionTMG;
			Map<String, String> mapParams = pr.getParameters();
			mapParams.put('restart', 'true');
			mapParams.put('hasBack', 'true');
			mapParams.put('subscriptionType', this.subscription.Subscription_Duration_Number__c + Constants.KEY_CONTINUOUS);
			mapParams.put('tcode', this.subscription.TCode__r.Name);
			if(this.bChangeOffer && this.subscriptionTemp != null && this.subscriptionTemp.Low_Start_Amendment_TCode_Helper__c != null){
				List<TCodeManagement__c> lstTCode = [select Id, Name from TCodeManagement__c where Id = :this.subscriptionTemp.Low_Start_Amendment_TCode_Helper__c];
				if(!lstTCode.isEmpty()){
					mapParams.put('tcode', lstTCode[0].Name);
				}
			}
			mapParams.put('orderMethod', String.isBlank(this.subscription.Order_Taken_Method__c)?Constants.DIRECTION_INBOUND:this.subscription.Order_Taken_Method__c);
			mapParams.put('selectedOffer', Constants.OFFER_LOWSTART);
			mapParams.put('selectedProduct', Constants.PRODUCT_PREMIUM);
			mapParams.put('tsnumber', this.subscription.Subscriber__r.Subscriber_Number__c);
			mapParams.put('paymentType', sPaymentMethod);
			mapParams.put('paymentFrequency', (sPaymentMethod == Constants.SUB_ACQUISITION_PAYMENT_DD?this.subscription.MPP_DD_Frequency__c:this.subscription.MPP_CC_Frequency__c));
			mapParams.put('paymentStartDate', this.subscription.PaymentDate__c);
			if(this.subscription.Retailer__c != null){
				mapParams.put('retailerid', this.subscription.Retailer__r.RET_ID__c);
			}
			if(incentiveId != null){
				mapParams.put('incentiveId', incentiveId);
			}
			if(bTestFail && Test.isRunningTest()){
				throw new TelegraphApplicationException('test fail');
			}
		}catch(Exception e){
			Database.rollback(sp);
			this.sError = Label.Low_Start_Restart_feature_MPP_call_failure + ' ' + e.getMessage();
			pr = null;
		}
		return pr;
	}
}