src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsUsingMPP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Accout using MPP as Payment Provider?</description>
        <inlineHelpText>Is this Accout using MPP as Payment Provider?</inlineHelpText>
        <label>Is Using MPP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>MPP_CC_First_Payment_Amount__c</fullName>
        <label>MPP CC First Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutAttemptCount__c</fullName>
        <label>MppDDCalloutAttemptCount</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutStage__c</fullName>
        <label>MppDDCalloutStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>UserManage</fullName>
                </value>
                <value>
                <fullName>UserManage-Failed</fullName>
                </value>
                <value>
                <fullName>DirectDebit</fullName>
                </value>
                <value>
                <fullName>DirectDebit-Failed</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule-Failed</fullName>
                </value>
                <value>
                <fullName>Failed</fullName>
                </value>
                <value>
                <fullName>GetPayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MppDDLastCalloutDateTime__c</fullName>
        <label>MppDDLastCalloutDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MPPBulkUserManageScheduler.cls
/*
* MIrfan@Appirio, Plane 1.2; 090512. 
* Apex batch job to   
*/  
global class MPPBulkUserManageScheduler implements Schedulable {
/*
     global String query = 'Select Name,Subscriber__r.PersonBirthdate, '+
                    ' Subscriber__r.FirstName, '+
                    ' Subscriber__r.LastName, '+
                    ' Subscriber__r.Gender__pc, '+
                    ' Subscriber__r.PersonMailingCountry, '+
                    ' Subscriber__r.PersonMailingState, '+
                    ' Subscriber__r.PersonMailingStreet, '+
                    ' Subscriber__r.PersonMailingCity, '+
                    ' Subscriber__r.PersonMailingPostalCode, '+
                    ' Subscriber__r.PersonHomePhone, '+
                    ' Subscriber__r.PersonMobilePhone, '+
                    ' Subscriber__r.Subscriber_Number__c, '+
                    ' Subscriber__r.Guid__c, '+
                    ' Subscriber__r.PersonEmail, '+
                    ' MppDDCalloutAttemptCount__c,MppDDCalloutStage__c,MppDDLastCalloutDateTime__c,MPP_CC_First_Payment_Amount__c ' +
                ' from Subscription__c  '+
                ' where Subscription_Status__c=\'Offered\' '+
                ' and Payment_Type__c=\'Direct Debit\' and Subscriber__r.IsUsingMPP__c=false '+
                ' and (MppDDCalloutAttemptCount__c<4 or MppDDCalloutAttemptCount__c=null) '+
                ' and (MppDDCalloutStage__c =null or MppDDCalloutStage__c =\'UserManage-Failed\') '+
                ' and Previous_Subscription__c!=null and Previous_Subscription__r.isContinuous__c = true order by Name';
*/

     global String query = 'Select Name,Subscriber__r.PersonBirthdate, '+
                    ' Subscriber__r.FirstName, '+
                    ' Subscriber__r.LastName, '+
                    ' Subscriber__r.Gender__pc, '+
                    ' Subscriber__r.PersonMailingCountry, '+
                    ' Subscriber__r.PersonMailingState, '+
                    ' Subscriber__r.PersonMailingStreet, '+
                    ' Subscriber__r.PersonMailingCity, '+
                    ' Subscriber__r.PersonMailingPostalCode, '+
                    ' Subscriber__r.PersonHomePhone, '+
                    ' Subscriber__r.PersonMobilePhone, '+
                    ' Subscriber__r.Subscriber_Number__c, '+
                    ' Subscriber__r.Guid__c, '+
                    ' Subscriber__r.PersonEmail, '+
                    ' MppDDCalloutAttemptCount__c,MppDDCalloutStage__c,MppDDLastCalloutDateTime__c,MPP_CC_First_Payment_Amount__c ' +
                ' from Subscription__c  '+
                ' where Subscription_Status__c=\''+DDSetupOnMPPBatch.SUBSCRIPTION_STATUS_OFFERED+'\' '+
                ' and Payment_Type__c=\''+DDSetupOnMPPBatch.SUBSCRIPTION_PAYMENT_TYPE_DD+'\' and Subscriber__r.IsUsingMPP__c=false '+
                ' and (MppDDCalloutAttemptCount__c<4 or MppDDCalloutAttemptCount__c=null) '+
                ' and (MppDDCalloutStage__c =null or MppDDCalloutStage__c =\''+DDSetupOnMPPBatch.MppDDCalloutStage_STAGE_1_FAILED+'\') '+
                ' and Previous_Subscription__c!=null and Previous_Subscription__r.isContinuous__c = true order by Name';


//this method creates the query string and executes the batch
    global void execute(SchedulableContext sc) {

//If required in future uncomment and try implementing using Custom setting to clear the previous Jobs from cronTrigger
/*
for(CronTrigger CT:[select Id from CronTrigger where State = 'DELETED']){
        System.abortjob(CT.Id);        
    }
*/  
        try {
            //create the batch and execute it
            DDSetupOnMPPBatch batchable = new DDSetupOnMPPBatch(query, 'UserManage');           
            Id accountUpdateBatchId = Database.executeBatch(batchable,Integer.valueOf(Label.MppDDCalloutBatchSize));
        } catch(Exception ex) { //If unable to queue the Batch Class then Schedule self  to run after few seconds (configured in Custom Label).
                Datetime sysTime = System.now();
                sysTime = sysTime.addSeconds(Integer.valueOf(Label.JobSchedulerRetryFailureInSeconds));
                String chron_exp = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
                system.debug('############chron_exp#######'+chron_exp);
                MPPBulkUserManageScheduler  p = new MPPBulkUserManageScheduler();
                System.schedule('MPPBulkUserManageScheduler:' + sysTime.getTime(),chron_exp,p);          
        }
    }     
}