src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SRN__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>SRN</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountUpdateScheduler.cls
/**
* @author Unknown
* @date Unknown
* @description Scheduled for AccountUpdateBatch
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         14/10/2015  //moved test method to AccountUpdateBatchTest
**/
global class AccountUpdateScheduler implements Schedulable {
	global void execute(SchedulableContext sc) {
		
		String query = 'Select Id, SRN__c, Subscriber_Number__c, Subscriber_Number_Static__c from Account where SRN__c != null and Subscriber_Number_Static__c = null';
		String toAddress = 'anup.jadhav@telegraph.co.uk';
		String replyToAddress = 'anup.jadhav@telegraph.co.uk';
		
		
		AccountUpdateBatch batchable = new AccountUpdateBatch(query, toAddress, replyToAddress);
		try {
			Id accountUpdateBatchId = Database.executeBatch(batchable);
		} catch(Exception ex) {
			
			List<String> toAddresses = new List<String> {'anup.jadhav@telegraph.co.uk'};
			//use the new util class to send an email
			TMGUtil.EmailUtil emailUtil = new TMGUtil.EmailUtil(toAddresses);
			emailUtil.plainTextBody('The scheduled job has been fubar\'ed.')
					 .senderDisplayName('Anup Jadhav')
					 .subject('Error Error: Don\'t Panic')
					 .replyTo(replyToAddress).build().sendEmail();
		
		}
	}
}