src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>

    
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Zuora Subscription</description>
        <inlineHelpText>Lookup field to Zuora Subscription</inlineHelpText>
        <label>Zuora Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Cancellation</fullName>
        <active>false</active>
        <businessProcess>TMG Support Process</businessProcess>
        <label>Cancellation</label>
    </recordTypes>




</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Within 14 days</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Serious illness</fullName>
                </value>
                <value>
                <fullName>Poor eyesight</fullName>
                </value>
                <value>
                <fullName>Gone Away</fullName>
                </value>
                <value>
                <fullName>Review of personal finances/cannot afford</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Editorial Issues</fullName>
                </value>
                <value>
                <fullName>Too much to read.</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Unpaid Cheque</fullName>
                </value>
                <value>
                <fullName>Duplicate File</fullName>
                </value>
                <value>
                <fullName>Dislike Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Fears Commitment</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved to Care Home</fullName>
                </value>
                <value>
                <fullName>Moving House (UK)</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
                <value>
                <fullName>Unknown</fullName>
                </value>
                <value>
                <fullName>Prefers online content</fullName>
                </value>
                <value>
                <fullName>Independent i</fullName>
                </value>
                <value>
                <fullName>DD Refer to Payer</fullName>
                </value>
                <value>
                <fullName>DD Cancelled by Payer</fullName>
                </value>
                <value>
                <fullName>DD No Instruction</fullName>
                </value>
                <value>
                <fullName>DD Account Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>For normal subscriptions.</description>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <fields>
        <fullName>Master_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Amendments</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Rate_Plan_Term_Type__c</fullName>
        <label>Subscription Rate Plan Term Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <pluralLabel>Quotes</pluralLabel>
</CustomObject>

src/classes/ZuoraSubscriptionDefaultValuesTest.cls
/**
* Author:       Sally ElGhoul (Tquila)
* Date:         23/04/2015
* Description:  this class for testing ZuoraSubscriptionDefaultValues
*
* ******************* Change Log *******************
* Modified by       Change Date
* Michal Kwika      15/09/2015
* Wiktor Czykin		14/03/2016	//added test coverage for added functionality
* Lynette Lim       27-04-2016   Added testOldPrintInRenewalDateValidation()
**/
@isTest
private class ZuoraSubscriptionDefaultValuesTest {

	private  static testMethod void testDefaultValues() {
		TestDataUtility td = new TestDataUtility(1);
		td.createZquotes();
		td.lstZQuotes[0].Subscription_Rate_Plan_Term_Type__c = Constants.QUOTE_SUBSCRIPTION_TERM_TYPE_FIELD;
		update td.lstZQuotes[0];
		//create another subscription and assign
		td.createBillingAccountToRegistrant(td.lstRegistrants[0].Id, Constants.PAYMENT_METHOD_CREDIT_CARD_TYPE);
		td.createZuoraSubscriptionToRegistrant(td.lstRegistrants[0].Id);
		td.lstZuoraSubscriptions[0].Related_Quote__c = td.lstZQuotes[0].Id;
		td.lstZuoraSubscriptions[0].Zuora__Zuora_Id__c = td.lstZuoraSubscriptions[0].Id;
		td.lstZuoraSubscriptions[0].Zuora__NextChargeDate__c = Date.today().addDays(1);
		update td.lstZuoraSubscriptions[0];

		ApexPages.currentPage().getParameters().put('subscriptionId', td.lstZuoraSubscriptions[0].Id);

		//set the quote to be new subscritpion
		td.lstZQuotes[0].zqu__SubscriptionType__c = Constants.QUOTE_SUBSCRIPTION_TYPE_NEW_VALUE;
		update td.lstZQuotes[0];

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);

			//Controller of the default value we created to extend zuora
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			//call the function that will set the default values
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.INITIAL_TERM_FIELD), Constants.INITIAL_TERM_VALUE_DEFAULT);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.RENEWAL_TERM_FIELD), Constants.RENEWAL_TERM_VALUE_DEFAULT);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.START_DATE_FIELD), Date.today());
			System.AssertEquals(td.lstZQuotes[0].get(Constants.VALID_UNTI_DATE_FIELD), Date.today());

			//quote amendment type
			td.lstZQuotes[0].zqu__SubscriptionType__c = Constants.QUOTE_SUBSCRIPTION_TYPE_AMEND_VALUE;
			update td.lstZQuotes[0];
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);

			td.createBillingAccountToRegistrant(td.lstRegistrants[0].id, Constants.PAYMENT_METHOD_CREDIT_CARD_TYPE);
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);

			td.lstZuoraPaymentMethods[0].Zuora__Type__c = Constants.PAYMENT_METHOD_DIRECT_DEBIT_TYPE;
			update td.lstZuoraPaymentMethods[0];
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);
		Test.stopTest();
	}

	//test this case with Direct Debit
	private static testMethod void testDefaultValuesDirectDebit() {
		TestDataUtility td = new TestDataUtility(1);
		td.createZquotes();
		td.lstZQuotes[0].Subscription_Rate_Plan_Term_Type__c = Constants.QUOTE_SUBSCRIPTION_TERM_TYPE_FIELD;
		update td.lstZQuotes[0];
		//create another subscription and assign
		td.createBillingAccountToRegistrant(td.lstRegistrants[0].id, Constants.PAYMENT_METHOD_DIRECT_DEBIT_TYPE);
		td.createZuoraSubscriptionToRegistrant(td.lstRegistrants[0].id);
		td.lstZuoraSubscriptions[0].Related_Quote__c = td.lstZQuotes[0].Id;
		td.lstZuoraSubscriptions[0].Zuora__Zuora_Id__c = td.lstZuoraSubscriptions[0].Id;
		td.lstZuoraSubscriptions[0].Zuora__NextChargeDate__c = Date.today().addDays(1);
		td.lstZuoraSubscriptions[0].Master_Quote__c = td.lstZQuotes[0].Id;
		update td.lstZuoraSubscriptions[0];

		ApexPages.currentPage().getParameters().put('subscriptionId', td.lstZuoraSubscriptions[0].Id);

		//set the quote to be new subscritpion
		td.lstZQuotes[0].zqu__SubscriptionType__c = Constants.QUOTE_SUBSCRIPTION_TYPE_NEW_VALUE;
		update td.lstZQuotes[0];

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);

			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			//call the function that will set the default values
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.INITIAL_TERM_FIELD), Constants.INITIAL_TERM_VALUE_DEFAULT);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.RENEWAL_TERM_FIELD), Constants.RENEWAL_TERM_VALUE_DEFAULT);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.START_DATE_FIELD), Date.today());
			//System.AssertEquals(td.lstZQuotes[0].get(Constants.PAYMENT_METHOD_FIELD),Constants.CREDIT_CARD_PAYMENT_METHOD);
			System.AssertEquals(td.lstZQuotes[0].get(Constants.VALID_UNTI_DATE_FIELD), Date.today());

			//quote amendment type
			td.lstZQuotes[0].zqu__SubscriptionType__c = Constants.QUOTE_SUBSCRIPTION_TYPE_AMEND_VALUE;
			update td.lstZQuotes[0];
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);

			td.createBillingAccountToRegistrant(td.lstRegistrants[0].id, Constants.PAYMENT_METHOD_CREDIT_CARD_TYPE);
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);

			td.lstZuoraPaymentMethods[0].Zuora__Type__c = Constants.PAYMENT_METHOD_DIRECT_DEBIT_TYPE;
			update td.lstZuoraPaymentMethods[0];
			defaultValuesController.populateDefaultFieldValue(td.lstZQuotes[0], null);

		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test validation for non registrants
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testErrorForNonRegistrant(){
		TestDataUtility td = new TestDataUtility(1);
		td.createIndividualSubscribers();

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			defaultValuesController.populateDefaultFieldValue(new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id), null);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_Non_registrant_account_error));
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test validation for ative old digital subscription
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testErrorForActiveOldDigital(){
		TestDataUtility td = new TestDataUtility(1);
		td.createRegistrants();
		td.lstRegistrants[0].Subscriber_Digital_Status__c = Constants.DIGITAL_SUBSCRIBER_STATUS_ACTIVE;
		update td.lstRegistrants;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstRegistrants[0].Id);
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			defaultValuesController.populateDefaultFieldValue(new zqu__Quote__c(zqu__Account__c = td.lstRegistrants[0].Id), null);
			System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.Quote_Flow_Active_subscription_error));
		Test.stopTest();
	}
	
	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test activation date is +1 day cancellation date
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testOldPrintPendingCancellationDateAsDefault(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkRegistrantAccountDependencies();
		td.createSubscriptions();
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING_CANX;
		td.lstSubscriptions[0].Cancellation_Date__c = td.lstSubscriptions[0].Start_Date__c.addDays(10);
		td.lstSubscriptions[0].Cancellation_Reason__c = 'test';
		td.lstSubscriptions[0].Cancellation_Method__c = 'test';
		update td.lstSubscriptions;
		td.lstIndividualSubscribers[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.ACCOUNT_REGISTRANT_RECORD_TYPE_NAME, Account.class.getName());
		update td.lstIndividualSubscribers;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			zqu__Quote__c quote = new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id);
			defaultValuesController.populateDefaultFieldValue(quote, null);
			System.assertEquals(td.lstSubscriptions[0].Cancellation_Date__c.addDays(1), quote.zqu__Service_Activation_Date__c);
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Wiktor Czykin
	Date        14/03/2016
	Function    Test activation date is +1 day cancellation date
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testOldPrintPendingCancellationDateAsNotDefaultWhenOverriden(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkRegistrantAccountDependencies();
		td.createSubscriptions();
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING_CANX;
		td.lstSubscriptions[0].Cancellation_Date__c = td.lstSubscriptions[0].Start_Date__c.addDays(10);
		td.lstSubscriptions[0].Cancellation_Reason__c = 'test';
		td.lstSubscriptions[0].Cancellation_Method__c = 'test';
		update td.lstSubscriptions;
		td.lstIndividualSubscribers[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.ACCOUNT_REGISTRANT_RECORD_TYPE_NAME, Account.class.getName());
		update td.lstIndividualSubscribers;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			Date dToCheck = td.lstSubscriptions[0].Cancellation_Date__c.addDays(100);
			zqu__Quote__c quote = TestDataUtility.newZquote(td.lstIndividualSubscribers[0].Id);
			quote.zqu__Service_Activation_Date__c = dToCheck;
			insert quote;
			
			defaultValuesController.populateDefaultFieldValue(quote, null);
			System.assertEquals(dToCheck, quote.zqu__Service_Activation_Date__c);
		Test.stopTest();
	}

	/*************************************************************************************** 
	Developer   Lynette Lim
	Date        14/03/2016
	Function    Test activation date is +1 day end date
	******************* Change Log *******************
	Modified by         Version     Change Date
	****************************************************************************************/
	private static testMethod void testOldPrintInRenewalDateAsDefault(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkRegistrantAccountDependencies();
		td.checkSubscriptionDependencies();
		Subscription__c sub = TestDataUtility.newSubscripiton(0, td.lstIndividualSubscribers[0].Id, td.lstRetailers[0].Id,  UtilitySelectOptionsSubscriptions.getFirstStartDate(5));
		sub.Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
		insert sub;

		sub = [select Id, Start_Date__c, End_Date__c from Subscription__c where Id =:sub.id];

		td.lstIndividualSubscribers[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.ACCOUNT_REGISTRANT_RECORD_TYPE_NAME, Account.class.getName());
		update td.lstIndividualSubscribers;

		Test.startTest();
			PageReference pageRef = Page.Zuora_PaymentStep;
			Test.setCurrentPage(pageRef);
			ApexPages.currentPage().getParameters().put('crmAccountId', td.lstIndividualSubscribers[0].Id);
			ZuoraSubscriptionDefaultValues defaultValuesController = new ZuoraSubscriptionDefaultValues();
			zqu__Quote__c quote = new zqu__Quote__c(zqu__Account__c = td.lstIndividualSubscribers[0].Id);
			defaultValuesController.populateDefaultFieldValue(quote, null);
			
			System.assertEquals(sub.End_Date__c.addDays(1), quote.zqu__Service_Activation_Date__c);
		Test.stopTest();
	}
}