src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Card_Expiry_Date__c</fullName>
        <label>Credit Card Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>

    <fields>
        <fullName>OC_Call_Stage__c</fullName>
        <description>Outbound call stage name</description>
        <inlineHelpText>Outbound call stage name</inlineHelpText>
        <label>Call Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>T2</fullName>
                </value>
                <value>
                    <fullName>T2 Catch Up</fullName>
                </value>
                <value>
                    <fullName>TL1</fullName>
                </value>
                <value>
                    <fullName>TL2</fullName>
                </value>
                <value>
                    <fullName>BR1</fullName>
                </value>
                <value>
                    <fullName>CCEX1</fullName>
                </value>
                <value>
                    <fullName>DD Winback</fullName>
                </value>
                <value>
                    <fullName>DDCX</fullName>
                </value>
                <value>
                    <fullName>T2 28Days</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    




</CustomObject>

src/objects/Outbound_Call_Batch_Setting__c.object
<CustomObject>
    <description>Configuration object for batch jobs generating Cases for Outbound Calling</description>
    <fields>
        <fullName>Batch_Job_Notifications__c</fullName>
        <description>Batch job errors and notifications</description>
        <inlineHelpText>Stores batch job errors and notifications from last 2 executions</inlineHelpText>
        <label>Batch Job Notifications</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Executions__c</fullName>
        <description>Number of executions</description>
        <inlineHelpText>Stores the number of executions</inlineHelpText>
        <label>Executions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Execution_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Last Execution Error</description>
        <inlineHelpText>Stores information whether last execution had an error</inlineHelpText>
        <label>Last Execution Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outbound_Call_Setting__c</fullName>
        <description>Related Outbound Call Setting</description>
        <inlineHelpText>Define Outbound Call Setting Master</inlineHelpText>
        <label>Outbound Call Setting</label>
        <referenceTo>Outbound_Call_Setting__c</referenceTo>
        <relationshipLabel>Outbound Call Batch Settings</relationshipLabel>
        <relationshipName>Outbound_Call_Batch_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>Scope of records</description>
        <inlineHelpText>Define the scope of records to be picked up</inlineHelpText>
        <label>Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Batch Setting</label>
    <nameField>
        <label>Outbound Call Batch Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Batch Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Call_Setting__c.object
<CustomObject>
    <description>Configuration object for Outbound Calling</description>
    <fields>
        <fullName>Default_Queue_Name__c</fullName>
        <description>Default queue name</description>
        <inlineHelpText>Define default queue name</inlineHelpText>
        <label>Default Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Setting</label>
    <nameField>
        <label>Outbound Call Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OutboundCallingCCBatch.cls
/**
* Author:       Michal Szewczyk
* Date:			22/07/2016
* Description:  Get all accounts with CC Expiry Date ends next month and create cases for them
*
* ******************* Change Log *******************
* Modified by       Change Date
**/
public class OutboundCallingCCBatch implements Database.Batchable<sObject>,Database.Stateful, Schedulable  {

	public static String BATCH_NAME = 'OutboundCallingCCBatch';
	public String errorString = '';

	private Outbound_Call_Batch_Setting__c configRecord;
	private List<OutboundCallingBean.CallStageMapping> params;
	private Id recordTypeId;

    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 12/07/2016
    Version - 1.0
    Function - batch class constructor
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public OutboundCallingCCBatch(){
   		configRecord = OutboundCallingBatchUtils.fetchConfigRecord(BATCH_NAME);
   		params = OutboundCallingUtils.getCallStageParametersByOCsettingId(configRecord.Outbound_Call_Setting__c);
   		recordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, Constants.OC_CREDIT_CARD_EXPIRY_RECORD_TYPE_NAME, Case.class.getName());
	}

    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 12/07/2016
    Version - 1.0
    Function - start method of batch - scope definition
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public Database.QueryLocator start(Database.BatchableContext batchContext) {
		Integer timeframe = 0;

		if(params.size() >0 && params[0].offset != null) {
			timeframe = params[0].offset;
		}

		if(configRecord.Scope__c != null) {
			return Database.getQueryLocator(configRecord.Scope__c);
		}else {
			return Database.getQueryLocator('SELECT Id, Subscriber_Number_Static__c, Credit_Card_Expiry_Date__c, (SELECT Id,CreatedDate FROM Cases WHERE RecordTypeId =\'' + recordTypeId + '\') FROM Account WHERE Credit_Card_Expiry_Date__c != null	AND Credit_Card_Expiry_Date__c = NEXT_N_MONTHS:' + timeframe);
		}
	}
    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 12/07/2016
    Version - 1.0
    Function - batch execution for schedule
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public void execute(SchedulableContext scheduleContext) {
		Database.executeBatch(new OutboundCallingCCBatch());
	}
    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 12/07/2016
    Version - 1.0
    Function - batch logic that takes accounts with Credit_Card_Expiry_Date set for specific month and creates cases for them
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
   	public void execute(Database.BatchableContext batchContext, List<sObject> accounts) {
   		List<Case> caseToInsert = new List<Case>();

   		try{
   			Case templateCase = OutboundCallingBatchUtils.populateCaseValues(configRecord.Parameters__c);
			for(Account acc : (List<Account>) accounts){
				if(acc.Cases.size() > 0  && acc.Cases[0].CreatedDate.month() == Date.today().month()) {
					continue;
				}
				Case tmpCase = templateCase.clone();
				tmpCase.OwnerId = OutboundCallingBatchUtils.getQueueId(configRecord.Outbound_Call_Setting__r.Default_Queue_Name__c);
				tmpCase.AccountId = acc.Id;
				tmpCase.CreatedDate =  Datetime.now();
				tmpCase.RecordTypeId = recordTypeId;
				if(params != null && params.size() > 0) {
					tmpCase.OC_Call_Stage__c = params[0].stagename;
					tmpCase.put(params[0].calldatetime, Datetime.now().addDays(params[0].offset));
				}

				caseToInsert.add(tmpCase);
			}
			insert caseToInsert;
			configRecord.Last_Execution_Error__c = false;

		} catch (Exception e) {
			errorString += e.getMessage() + '/n';
			configRecord.Last_Execution_Error__c = true;
		}
	}

    /**
	* @author Michal Szewczyk
	* @date 07/2016
	* @description required finish method, no implimentation yet...
	*#############Change Log#############
	*Modified by     Version     Change Date
	**/
	public void finish(Database.BatchableContext batchContext) {
		try {
            if(configRecord.Executions__c == null){
                configRecord.Executions__c = 1;
            }else{
                configRecord.Executions__c = configRecord.Executions__c + 1;
            }
			if(configRecord.Last_Execution_Error__c) {
				configRecord.Batch_Job_Notifications__c = errorString;
			}
			update configRecord;

		} catch (Exception e) {
            throw new TelegraphApplicationException('OutboundCallingCCBatch error : ' + e.getMessage());
		}
	}

}