src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DD_Cancellation_Call_Date_Time__c</fullName>
        <label>DD Cancellation Call Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DD_Cancellation_Outcome__c</fullName>
        <label>DD Cancellation Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Cheque Sales</fullName>
                </value>
                <value>
                    <fullName>NATC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <fields>
        <fullName>OC_Outcome__c</fullName>
        <description>The outcome of the outbound call</description>
        <inlineHelpText>Please specify the outcome of the outbound call</inlineHelpText>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Cheque Sales</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>NATC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Zuora Subscription</description>
        <inlineHelpText>Lookup field to Zuora Subscription</inlineHelpText>
        <label>Zuora Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Cancellation</fullName>
        <active>false</active>
        <businessProcess>TMG Support Process</businessProcess>
        <label>Cancellation</label>
    </recordTypes>




</CustomObject>

src/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The custom setting object to hold all TMG Application static settings</description>
    <label>Application Configurations</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Within 14 days</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Serious illness</fullName>
                </value>
                <value>
                <fullName>Poor eyesight</fullName>
                </value>
                <value>
                <fullName>Gone Away</fullName>
                </value>
                <value>
                <fullName>Review of personal finances/cannot afford</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Editorial Issues</fullName>
                </value>
                <value>
                <fullName>Too much to read.</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Unpaid Cheque</fullName>
                </value>
                <value>
                <fullName>Duplicate File</fullName>
                </value>
                <value>
                <fullName>Dislike Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Fears Commitment</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved to Care Home</fullName>
                </value>
                <value>
                <fullName>Moving House (UK)</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
                <value>
                <fullName>Unknown</fullName>
                </value>
                <value>
                <fullName>Prefers online content</fullName>
                </value>
                <value>
                <fullName>Independent i</fullName>
                </value>
                <value>
                <fullName>DD Refer to Payer</fullName>
                </value>
                <value>
                <fullName>DD Cancelled by Payer</fullName>
                </value>
                <value>
                <fullName>DD No Instruction</fullName>
                </value>
                <value>
                <fullName>DD Account Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OutboundCallingDDCXBatchTest.cls
/**
* Developer - Mantas Grigaliunas
* Date - 24/05/2017
* Description:  Test class for OutboundCallingDDWinbackBatch
*
* ******************* Change Log *******************
* Modified by   Change Date
**/

@isTest
public class OutboundCallingDDCXBatchTest {
	private static final String SUBS_CREATED = 'There should be 10 subs created.';
	private static final Integer COUNTER = 10;

	@TestSetup
	private static void testSetup(){
		TestDataUtility testUtility = new TestDataUtility();
   		testUtility.loadCountryCodes();

		testUtility.iCounter = 1;
		testUtility.createOutboundCallBatchSetting(OutboundCallingDDCXBatch.BATCH_NAME);
		testUtility.lstOutboundCallBatchSetting[0].Parameters__c = '{ "attributes": { "type": "Case" }, "Status": "Not Started", "Priority": "Normal", "Reason": "Outbound DD Cancellation", "Origin": "Internal Records", "Type": "Outbound Calling DD Cancellation", "Subject": "Outbound DD Cancellation", "DD_Cancellation_Outcome__c": "Not Started", "OC_Outcome__c": "Not Started"}';
		update testUtility.lstOutboundCallBatchSetting;
		
		testUtility.lstOutboundCallSetting[0].Parameters__c = '{ "callStageParameters" : [ { "stagename" : "DD Cancellation", "outcome" : "DD_Cancellation_Outcome__c", "calldatetime" : "DD_Cancellation_Call_Date_Time__c", "offset" : 0 , "tcode" : "", "nosalereason":""} ]}';
		update testUtility.lstOutboundCallSetting;

		testUtility.iCounter = 10;
       	testUtility.loadGeneral();
       	testUtility.createSubscriptions();

        insert Configuration__c.getOrgDefaults();

        User usr = [SELECT Id FROM User WHERE ProfileId = :Constants.getSystemAdministratorProfileId() AND IsActive = TRUE LIMIT 1];

        System.runAs(usr){
			Group g = new Group(Type='Queue', Name='QueueName0');
			insert g;

			QueueSObject q = new QueueSObject(SobjectType='Case', QueueId=g.Id);
			insert q;
		}

	}

	/***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - check if cases are created for pending cancellation subs
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
	private static testMethod void caseCreated() {

		List<Subscription__c> subs = [SELECT Id FROM Subscription__c];
		List<Account> subscribers  = [SELECT Id FROM Account WHERE RecordType.Name = :Constants.ACCOUNT_INDIVIDUAL_RECORD_TYPE_NAME];

       	setAccountValues(subscribers, '123242354');

       	System.assertEquals(COUNTER, subs.size(), SUBS_CREATED);
		
		setSubscriptionValues(subs, true, Constants.SUB_PMETHOD_DD);

        Test.startTest();
	    	OutboundCallingDDCXBatch ddcxBatch = new OutboundCallingDDCXBatch();
	    	Database.executeBatch(ddcxBatch, 200);
    	Test.stopTest();

		List<Case> cases = [SELECT Id FROM Case];
	    System.assertEquals(10, cases.size(), 'There should be 10 cases created');
    }

    /***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - cases should not be created if the last status change is in past
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
    private static testMethod void caseNOTCreatedIfNotContinuos() {
		List<Subscription__c> subs = [SELECT Id FROM Subscription__c];
		List<Account> subscribers  = [SELECT Id FROM Account WHERE RecordType.Name = :Constants.ACCOUNT_INDIVIDUAL_RECORD_TYPE_NAME];

       	setAccountValues(subscribers, '123242354');

       	System.assertEquals(COUNTER, subs.size(), SUBS_CREATED);

		setSubscriptionValues(subs, false, Constants.SUB_PMETHOD_DD);

        Test.startTest();
	    	OutboundCallingDDCXBatch ddwinbackBatch = new OutboundCallingDDCXBatch();
	    	Database.executeBatch(ddwinbackBatch, 200);
    	Test.stopTest();

		List<Case> cases = [SELECT Id FROM Case];
	    System.assertEquals(0, cases.size(), 'There should be NO cases created');
    }
    
    /***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - cases should not be created if the cancellation method is Phone
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
    private static testMethod void caseNOTCreatedIfPaymentNotDD() {
		List<Subscription__c> subs = [SELECT Id FROM Subscription__c];
		List<Account> subscribers  = [SELECT Id FROM Account WHERE RecordType.Name = :Constants.ACCOUNT_INDIVIDUAL_RECORD_TYPE_NAME];

		setAccountValues(subscribers, '123242354');

       	System.assertEquals(COUNTER, subs.size(), SUBS_CREATED);

		setSubscriptionValues(subs, true, Constants.SUB_PMETHOD_CC);

        Test.startTest();
	    	OutboundCallingDDCXBatch ddwinbackBatch = new OutboundCallingDDCXBatch();
	    	Database.executeBatch(ddwinbackBatch, 200);
    	Test.stopTest();

		List<Case> cases = [SELECT Id FROM Case];
	    System.assertEquals(0, cases.size(), 'There should be NO cases created');
    }
    
    /***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - cases should not be created if the cancellation method is email but no account phone
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
    private static testMethod void caseNOTCreatedIFNoAccountPhone() {
		List<Subscription__c> subs = [SELECT Id FROM Subscription__c];
		List<Account> subscribers  = [SELECT Id FROM Account WHERE RecordType.Name = :Constants.ACCOUNT_INDIVIDUAL_RECORD_TYPE_NAME];

       	setAccountValues(subscribers, null);

       	System.assertEquals(COUNTER, subs.size(), SUBS_CREATED);

		setSubscriptionValues(subs, true, Constants.SUB_PMETHOD_DD);
        
        Test.startTest();
	    	OutboundCallingDDCXBatch ddwinbackBatch = new OutboundCallingDDCXBatch();
	    	Database.executeBatch(ddwinbackBatch, 200);
    	Test.stopTest();

		List<Case> cases = [SELECT Id FROM Case];
	    System.assertEquals(0, cases.size(), 'There should be NO cases created');
    }

    /***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - set subscription values and last status change
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
    private static void setSubscriptionValues(List<Subscription__c> subs, Boolean isContinuous, String paymentType){

        Date subStartDate = Date.today().addMonths(-9).toStartOfWeek();
        Datetime myDate = datetime.newInstance(subStartDate.year(), subStartDate.month(), subStartDate.day());
        String day = myDate.format('EEEE');
        System.assertEquals('Monday', day, 'Sub should always start on a Monday');

    	for(Subscription__c sub : subs){
       		sub.Subscription_Status__c = Constants.SUBSCRIPTION_PENDING_CANCELLATION_STATUS;
			sub.Start_Date__c          = subStartDate;
            sub.Cancellation_Date__c   = Date.today().addDays(-7);
			sub.Cancellation_Method__c = 'Phone';
			sub.Cancellation_Reason__c = 'Unknown';
            sub.isContinuous__c        = isContinuous;
            sub.Payment_Type__c        = paymentType;
       	}
		update subs;
    }

    /***************************************************************************************
    Developer - Mantas Grigaliunas
    Date - 24/05/2017
    Function - set account phone values
    #############Change Log#############
    Modified by  Change Date 
    ****************************************************************************************/
    private static void setAccountValues(List<Account> accounts, string phone){
    	for(Account acc : accounts){
       		acc.PersonHomePhone = phone;
            acc.PersonMobilePhone = phone;
            acc.Phone = phone;
       	}
       	update accounts;
    }
}