src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClearDigitalEntitlementsBatch.cls
/** This batch will purge the webservice logs that are more than a certain number of weeks old
	The number of weeks must be specified in the constructor
*/
global class ClearDigitalEntitlementsBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

	global final string query;
	global final List<string> guids;
		
	global ClearDigitalEntitlementsBatch(List<string> guidsToClear) {
		guids = guidsToClear;
		query = 'Select Id, Subscriber_Digital_Status__c From Account Where Guid__c IN :guids';
	}
	
	global Database.QueryLocator start(Database.BatchableContext bc) {		
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext bc, List<Account> scope) {
		
		for(Account a : scope){
			a.Subscriber_Digital_Status__c = 'Inactive';
			
		}
		update scope;
	}
	
	
	global void finish(Database.BatchableContext bc) {

	}

}