src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DefaultNewlettersQueueableTest.cls
@isTest
private class DefaultNewlettersQueueableTest {
	
	@TestSetup private static void setupData(){
		//Creating only 5 accounts as we hit AsyncException.
        TestDataUtility tdu = new TestDataUtility(5);
        tdu.CreateCoreApiEndPointSettings();
        tdu.createMyNewslettersEndPointSettings();
        tdu.loadCountryCodes();
        tdu.createIndividualSubscribers();
        tdu.createNewslettersEndPointSettings();
    }

	@isTest static void testAddNewsletterQueue() {
        
		List<Account> accounts = [SELECT Id, Name, Subscriber_Number__c, PersonMailingPostalCode, Guid__c FROM Account];

		Test.startTest();

		DefaultNewlettersQueueable defaultNewsletters = new DefaultNewlettersQueueable(accounts, null, null);
		System.enqueueJob(defaultNewsletters);
        
        Test.stopTest();
	}
	
	@isTest static void testAddNewsletterAccount() {
        
		List<Account> accounts = [SELECT Id, Name, Subscriber_Number__c, PersonMailingPostalCode, Guid__c FROM Account];

		Test.startTest();

		DefaultNewsletterUtility.addDefaultNewsletter(accounts[0].Id);
        
        Test.stopTest();
	}
}