src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>Grouping object for Price Plans.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populate with the product that should be used for product validation (Product To) on related Print Price Plan records.</inlineHelpText>
        <label>Destination Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>HND</fullName>
                </value>
                <value>
                <fullName>OTC</fullName>
                <default>true</default>
                    <label>OTC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MPP_CC_Frequency__c</fullName>
        <label>MPP CC Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_DD_Frequency__c</fullName>
        <label>MPP DD Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutStage__c</fullName>
        <label>MppDDCalloutStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>UserManage</fullName>
                </value>
                <value>
                <fullName>UserManage-Failed</fullName>
                </value>
                <value>
                <fullName>DirectDebit</fullName>
                </value>
                <value>
                <fullName>DirectDebit-Failed</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule-Failed</fullName>
                </value>
                <value>
                <fullName>Failed</fullName>
                </value>
                <value>
                <fullName>GetPayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Sub_Duration__c</fullName>
        <formula>IF(Subscription_Duration_Number__c == 26, 26, 52)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Sub Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <description>1 or 15 of each month</description>
        <label>Payment Date</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Price_Override__c</fullName>
        <description>If populated, defines a price that will be used with the next subscription renewal.</description>
        <inlineHelpText>If populated, defines a price that will be used with the next subscription renewal.</inlineHelpText>
        <label>Renewal Price Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renewal_Product_Override__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Product Override</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions (Renewal Product Override)</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Please select a retailer that has not closed.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Retailer Account</value>
            </filterItems>
            <filterItems>
                <field>Account.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, TMG System</value>
            </filterItems>
            <infoMessage>Closed retailers are still valid accounts for System Administrator and TMG System profiles.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Number_Override__c</fullName>
        <label>Subscription Duration (Weeks) Override</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Number__c</fullName>
        <formula>IF(Subscription_Duration_Number_Override__c = 0, CASE(Subscription_Duration_Picklist__c, &quot;6&quot;, 6, &quot;10&quot;, 10, &quot;12&quot;, 12, &quot;13&quot;, 13, &quot;24&quot;, 24, &quot;26&quot;, 26, &quot;36&quot;, 36, &quot;39&quot;, 39, &quot;40&quot;, 40, &quot;44&quot;, 44, &quot;48&quot;, 48, &quot;52&quot;, 52, &quot;96&quot;, 96, &quot;156&quot;, 156, 0), Subscription_Duration_Number_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Duration (Weeks) - Hidden</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Picklist__c</fullName>
        <label>Subscription Duration (Weeks)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>26</fullName>
                </value>
                <value>
                <fullName>52</fullName>
                <default>true</default>
                    <label>52</label>
                </value>
                <value>
                <fullName>13</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weekly_Price__c</fullName>
        <label>Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionInRenewalCreationTest.cls
/**
* @author Pawel Chrzanowski
* @date 04/04/2016
* @description Test class for SubscriptionInRenewalCreation
#############Change Log#############
Modified by     Version     Change Date
Michal Szewczyk  1.1         04/07/2016  - fixed test methods
Wiktor Czykin    1.2         13/07/2016  - modified handleRenewedSubscriptionsTestPositive()
Wiktor Czykin    1.3         27/09/2016  - modified handleRenewedSubscriptionsTestPositive()
**/
@isTest
private class SubscriptionInRenewalCreationTest {
    private static final Double INCENTIVE_DISCOUNT = 4.50;
    private static final Double INCENTIVE_DISCOUNT_2 = 5.50;
    private static final Double RENEWAL_PRICE_OVERRIDE = 7.50;
    private static final Double HIGHER_THAN_HIGH_PRICE = 250;

    /***************************************************************************************
    Developer - Pawel Chrzanowski
    Date - 04/04/2016
    Version - 1.1
    Function - test method for handleRenewedSubscriptions() negative scenario - no Tcode
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk  1.1         04/07/2016  - uncommented
    ****************************************************************************************/
    static testMethod void handleRenewedSubscriptionsTestNoTcode(){
        Map<Id, Id> subIdsMap = new Map<Id, Id>();
        Map<Id, Subscription__c> inRenewalSubsMap = new Map<Id, Subscription__c>();

        TestDataUtility td = new TestDataUtility(1);
        td.createSubscriptions();
        inRenewalSubsMap.put(td.lstSubscriptions[0].Id, td.lstSubscriptions[0]);

        Test.startTest();
            try{
                subIdsMap = subscriptionInRenewalCreation.handleRenewedSubscriptions(inRenewalSubsMap, '');
            }catch(Exception e){
                System.assert(e.getMessage().contains('Unable to find a renewal TCode'));
            }
        Test.stopTest();
    }

    /***************************************************************************************
    Developer - Pawel Chrzanowski
    Date - 04/04/2016
    Version - 1.1
    Function - test method for handleRenewedSubscriptions() negative scenario - no Product linked to subscription
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk  1.1         04/07/2016  - uncommented and fixed
    ******************************************************************************************/
    static testMethod void handleRenewedSubscriptionsTestNoProduct(){
        Map<Id, Id> subIdsMap = new Map<Id, Id>();
        Map<Id, Subscription__c> inRenewalSubsMap = new Map<Id, Subscription__c>();

        TestDataUtility td = new TestDataUtility(1);
        td.loadCountryCodes();
        td.createTCodeManagement();
        td.createSubscriptions();

        td.lstTCodeManagement[0].Name = 'RNWL';
        td.lstTCodeManagement[0].Type__c = 'Renewal';
        update td.lstTCodeManagement[0];
        String subId = td.lstSubscriptions[0].Id;
        String sQuery = 'select ' + GlobalQueries.generateFieldsListForQuery(Subscription__c.class.getName(), new Set<String>{'Subscriber__r.RecordTypeId'}, null) + ' from Subscription__c where Id =:subId';
        List<Subscription__c> lstSubscription = Database.query(sQuery);
        inRenewalSubsMap.put(lstSubscription[0].Id, lstSubscription[0]);

        Test.startTest();

            try{
                subIdsMap = subscriptionInRenewalCreation.handleRenewedSubscriptions(inRenewalSubsMap, '');
            }catch(Exception e){
                System.assert(e.getMessage().contains('Subscription has no related Product.'));
            }

        Test.stopTest();
    }

    /***************************************************************************************
    Developer - Pawel Chrzanowski
    Date - 04/04/2016
    Version - 1.3
    Function - test method for handleRenewedSubscriptions() positive scenario
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk  1.1         04/07/2016  - uncommented and fixed
    Wiktor Czykin    1.2         13/07/2016  - added assertions for Plan__c
    Wiktor Czykin    1.3         27/09/2016  - modified plan logic and assertions because of plan based on product logic
    ******************************************************************************************/
    static testMethod void handleRenewedSubscriptionsTestPositive(){
        List<Subscription__c> lstSubscriptions;
        Map<Id, Id> subIdsMapFromButton = new Map<Id, Id>();
        Map<Id, Id> subIdsMapFromTrigger = new Map<Id, Id>();
        Map<Id, Subscription__c> inRenewalSubsMapFromTrigger = new Map<Id, Subscription__c>();
        Map<Id, Subscription__c> inRenewalSubsMapFromButton = new Map<Id, Subscription__c>();

        TestDataUtility td = new TestDataUtility(8);
        td.createTCodeManagement();
        td.createSubscriptions();
        td.createZProduct();
        td.createPricePlans();

        td.lstTCodeManagement[0].Name = Constants.TCODE_DEFAULT_RENEWAL_RECORD_NAME;
        td.lstTCodeManagement[0].Type__c = Constants.TCODE_TYPE_RENEWAL;
        update td.lstTCodeManagement[0];

        td.lstPricePlans[1].Product_From__c = td.lstZproducts[1].Id;
        td.lstPricePlans[1].Product_To__c = td.lstZproducts[5].Id;
        td.lstPricePlans[1].Incentive_Discount__c = INCENTIVE_DISCOUNT;
        td.lstPricePlans[2].Product_From__c = td.lstZproducts[2].Id;
        td.lstPricePlans[2].Product_To__c = td.lstZproducts[6].Id;
        td.lstPricePlans[3].Product_From__c = td.lstZproducts[3].Id;
        td.lstPricePlans[3].Product_To__c = td.lstZproducts[3].Id;
        update td.lstPricePlans;

        td.lstZproducts[5].Default_Plan__c = td.lstPlans[5].Id;
        update td.lstZProducts;

        //refetch subscriptions to populate formula fields
        lstSubscriptions = [select Discount__c, Plan__c, Product__c, Renewal_Price_Override__c, Renewal_Product_Override__c, Subscription_Status__c, Weekly_Price__c,
                            Subscription_Duration_Number_Override__c, Subscription_Duration_Picklist__c, Subscription_Duration_Number__c, New_Sub_Duration__c,
                            Subscriber__c, Retailer__c, End_Date__c, Delivery_Type__c, Payment_Type__c, PaymentDate__c, IsContinuous__c,
                            MPP_CC_Frequency__c, MPP_DD_Frequency__c, MppDDCalloutStage__c from Subscription__c];

        //Product - Id override, Weekly Price - value override
        lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
        lstSubscriptions[0].Product__c = td.lstZproducts[0].Id;
        lstSubscriptions[0].Renewal_Product_Override__c = td.lstZproducts[4].Id;
        lstSubscriptions[0].Renewal_Price_Override__c = RENEWAL_PRICE_OVERRIDE;
        lstSubscriptions[0].IsContinuous__c = true;
        inRenewalSubsMapFromButton.put(lstSubscriptions[0].Id, lstSubscriptions[0]);

        //Product - Id override, Weekly Price - trigger override success
        lstSubscriptions[1].Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
        lstSubscriptions[1].Product__c = td.lstZproducts[1].Id;
        lstSubscriptions[1].Renewal_Product_Override__c = td.lstZproducts[5].Id;
        lstSubscriptions[1].Renewal_Price_Override__c = null;
        lstSubscriptions[1].Plan__c = td.lstPlans[1].Id;
        lstSubscriptions[1].Weekly_Price__c = (td.lstPricePlans[1].Low_Price__c + td.lstPricePlans[1].High_Price__c)/2;
        inRenewalSubsMapFromButton.put(lstSubscriptions[1].Id, lstSubscriptions[1]);

        //Product - Id override, Weekly Price - trigger negative scenario
        lstSubscriptions[2].Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
        lstSubscriptions[2].Product__c = td.lstZproducts[2].Id;
        lstSubscriptions[2].Renewal_Product_Override__c = td.lstZproducts[6].Id;
        lstSubscriptions[2].Renewal_Price_Override__c = null;
        lstSubscriptions[2].Plan__c = td.lstPlans[2].Id;
        lstSubscriptions[2].Weekly_Price__c = HIGHER_THAN_HIGH_PRICE;
        lstSubscriptions[2].Discount__c = INCENTIVE_DISCOUNT_2;
        inRenewalSubsMapFromTrigger.put(lstSubscriptions[2].Id, lstSubscriptions[2]);

        //Product - trigger override, Weekly Price - trigger override success
        lstSubscriptions[3].Subscription_Status__c = Constants.SSTATUS_IN_RENEWAL;
        lstSubscriptions[3].Product__c = td.lstZproducts[3].Id;
        lstSubscriptions[3].Renewal_Product_Override__c = null;
        lstSubscriptions[3].Renewal_Price_Override__c = null;
        lstSubscriptions[3].Plan__c = td.lstPlans[3].Id;
        lstSubscriptions[3].Weekly_Price__c = (td.lstPricePlans[3].Low_Price__c + td.lstPricePlans[3].High_Price__c)/2;
        inRenewalSubsMapFromButton.put(lstSubscriptions[3].Id, lstSubscriptions[3]);

        Test.startTest();

            //map containing InRenewal Ids => Offered Ids
            subIdsMapFromButton = subscriptionInRenewalCreation.handleRenewedSubscriptions(inRenewalSubsMapFromButton, 'button');
            subIdsMapFromTrigger = subscriptionInRenewalCreation.handleRenewedSubscriptions(inRenewalSubsMapFromTrigger, 'trigger');

            //button logic
            if(!subIdsMapFromButton.isEmpty()){
                Map<Id, Subscription__c> offeredSubsMapFromButton = new Map<Id, Subscription__c>([select Id, Plan__c, Discount__c, MppDDCalloutStage__c, Product__c, Subscription_Status__c, Weekly_Price__c from Subscription__c where Id in :subIdsMapFromButton.values()]);

                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[0].Id)).Subscription_Status__c, Constants.SSTATUS_OFFERED);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[0].Id)).Product__c, td.lstZproducts[4].Id);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[0].Id)).Weekly_Price__c, RENEWAL_PRICE_OVERRIDE);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[0].Id)).Discount__c, 0);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[0].Id)).MppDDCalloutStage__c, Constants.MPP_MANUALRENEWAL_STAGE);

                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).Subscription_Status__c, Constants.SSTATUS_OFFERED);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).Product__c, td.lstZproducts[5].Id);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).Weekly_Price__c, td.lstPricePlans[1].Renewal_Price__c);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).Discount__c, INCENTIVE_DISCOUNT);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).MppDDCalloutStage__c, null);
                System.assertEquals(td.lstPlans[1].Id, offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[1].Id)).Plan__c);


                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[3].Id)).Subscription_Status__c, Constants.SSTATUS_OFFERED);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[3].Id)).Product__c, td.lstZproducts[3].Id);
                System.assertEquals(offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[3].Id)).Weekly_Price__c, td.lstPricePlans[3].Renewal_Price__c);
                System.assertEquals(td.lstPlans[3].Id, offeredSubsMapFromButton.get(subIdsMapFromButton.get(lstSubscriptions[3].Id)).Plan__c);

            }

            //trigger logic
            //if Price Plan not found and source is trigger - don't create an offered subscription
            System.assert(subIdsMapFromTrigger.isEmpty());
        Test.stopTest();
    }
}