src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Within 14 days</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Serious illness</fullName>
                </value>
                <value>
                <fullName>Poor eyesight</fullName>
                </value>
                <value>
                <fullName>Gone Away</fullName>
                </value>
                <value>
                <fullName>Review of personal finances/cannot afford</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Editorial Issues</fullName>
                </value>
                <value>
                <fullName>Too much to read.</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Unpaid Cheque</fullName>
                </value>
                <value>
                <fullName>Duplicate File</fullName>
                </value>
                <value>
                <fullName>Dislike Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Fears Commitment</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved to Care Home</fullName>
                </value>
                <value>
                <fullName>Moving House (UK)</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
                <value>
                <fullName>Unknown</fullName>
                </value>
                <value>
                <fullName>Prefers online content</fullName>
                </value>
                <value>
                <fullName>Independent i</fullName>
                </value>
                <value>
                <fullName>DD Refer to Payer</fullName>
                </value>
                <value>
                <fullName>DD Cancelled by Payer</fullName>
                </value>
                <value>
                <fullName>DD No Instruction</fullName>
                </value>
                <value>
                <fullName>DD Account Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MPP_DD_Frequency__c</fullName>
        <label>MPP DD Frequency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MppDDCalloutStage__c</fullName>
        <label>MppDDCalloutStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>UserManage</fullName>
                </value>
                <value>
                <fullName>UserManage-Failed</fullName>
                </value>
                <value>
                <fullName>DirectDebit</fullName>
                </value>
                <value>
                <fullName>DirectDebit-Failed</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule</fullName>
                </value>
                <value>
                <fullName>PaymentSchedule-Failed</fullName>
                </value>
                <value>
                <fullName>Failed</fullName>
                </value>
                <value>
                <fullName>GetPayment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <description>1 or 15 of each month</description>
        <label>Payment Date</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pricing Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
	<fields>
        <fullName>Subscription_Product__c</fullName>
        <formula>IF(OR(RecordType.Name=&apos;Schools&apos;, RecordType.Name=&apos;School&apos;), &apos;Schools&apos;,IF(AND(TEXT(Gift_Pack_Book__c)!=&apos;&apos;,TEXT(Gift_Box_Recipient__c)!=&apos;&apos;,NOT(ISBLANK(Gift_Donor__c))),&apos;7 Day - Gift&apos;, IF(Product__r.Name == null, &apos;7 Day - Standard&apos;, Product__r.Name)))</formula>
        <label>Subscription Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Calc__c</fullName>
        <formula>IF(LEN( Previous_Subscription__c)=0,
  IF(MOD(Today() - DATE(1900, 1, 7), 7) = 1, Today() + VALUE(Product__r.LeadDays__c) + 5, 
    IF(MOD(Today() - DATE(1900, 1, 7), 7) = 2, Today() + VALUE(Product__r.LeadDays__c) + 4, 
      IF(MOD(Today() - DATE(1900, 1, 7), 7) = 3, Today() + VALUE(Product__r.LeadDays__c) + 3, 
        IF(MOD(Today() - DATE(1900, 1, 7), 7) = 4, Today() + VALUE(Product__r.LeadDays__c) + 2, 
          IF(MOD(Today() - DATE(1900, 1, 7), 7) = 5, Today() + VALUE(Product__r.LeadDays__c) +1, 
            IF(MOD(Today() - DATE(1900, 1, 7), 7) = 6, Today() + VALUE(Product__r.LeadDays__c), 
        Today() + VALUE(Product__r.LeadDays__c) + 6)))))),
        
  IF(MOD(Today() - DATE(1900, 1, 7), 7) = 1, Today() + VALUE(Product__r.LeadDays__c)+ 19, 
    IF(MOD(Today() - DATE(1900, 1, 7), 7) = 2, Today() + VALUE(Product__r.LeadDays__c) + 18, 
      IF(MOD(Today() - DATE(1900, 1, 7), 7) = 3, Today() + VALUE(Product__r.LeadDays__c) + 17, 
        IF(MOD(Today() - DATE(1900, 1, 7), 7) = 4, Today() + VALUE(Product__r.LeadDays__c) + 16, 
          IF(MOD(Today() - DATE(1900, 1, 7), 7) = 5, Today() + VALUE(Product__r.LeadDays__c) + 15, 
            IF(MOD(Today() - DATE(1900, 1, 7), 7) = 6, Today() + VALUE(Product__r.LeadDays__c) + 14, 
  Today() + VALUE(Product__r.LeadDays__c) + 13)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Earliest Subscription Start Calc</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TCodeManagement__c.object
<CustomObject>
    <description>This details the t-code, description, price, if the t-code is still valid and incentive related to the t-code</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Campaign</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Low Start</fullName>
                </value>
                <value>
                <fullName>Open Offer</fullName>
                </value>
                <value>
                <fullName>Registered Interest</fullName>
                </value>
                <value>
                <fullName>POC</fullName>
                </value>
                <value>
                <fullName>MGM</fullName>
                </value>
                <value>
                <fullName>Staff Offer</fullName>
                </value>
                <value>
                <fullName>Renewal</fullName>
                </value>
                <value>
                <fullName>MIS</fullName>
                </value>
                <value>
                <fullName>Other</fullName>
                </value>
                <value>
                <fullName>POC-DM</fullName>
                </value>
                <value>
                <fullName>POC-EM</fullName>
                </value>
                <value>
                <fullName>POC-OBTM</fullName>
                </value>
                <value>
                <fullName>Promotional</fullName>
                </value>
                <value>
                <fullName>SELF</fullName>
                </value>
                <value>
                <fullName>UKN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked then the t-code is available for selection</description>
        <inlineHelpText>If checked then the t-code is available for selection</inlineHelpText>
        <label>Valid</label>
        <type>Checkbox</type>
    </fields>
    <label>TCodeManagement</label>
    <nameField>
        <label>TCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCodesManagement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSubscriptionInRenewal.cls
/**
* @author Unknown
* @date Unknown
* @description Test class for subscriptionInRenewalCreation and subscriptionInRenewalButton classes
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         30/07/2015  //introduced new init() method, restored assertions, replaced lock flag with SubscriptionTriggerHandler one, added testRaiseError()
Cristina Anghenie 1.2       14/09/2015  //test MppDDCalloutStage__c id set to manualRenewal only when renewal button is clicked on the subscription page
Wiktor Czykin   1.3         30/09/2015  //removed Discount__c references
Pawel Chrzanowski   1.4     07/04/2016  //updated for new data model
Michal Szewczyk 1.5         11/05/2016  //removed Subscription_Product__c from code
Gavin Palmer    1.6         02/06/2016  // modified TestSubscriptionInRenewalTrigger3()
**/
@isTest(SeeAllData=false)
private class TestSubscriptionInRenewal {        
    
    /*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/07/2015
    Version - 1.0
    Function - test init for all methods
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    @testSetup static void init(){
        TCodeManagement__c renewalTCode = TestDataUtility.newTCodeManagement('RNWL');
        renewalTCode.Type__c = 'Renewal';
        renewalTCode.Valid__c = true;
        insert renewalTCode;
    }
     
    /*************************************************************************************** 
    Developer - unknown
    Date - unknown
    Version - 1.1
    Function -  Assert that a new subscription is NOT created when current subscription status becomes
                'In Renewal' BUT the weekly price is not within a priceband. Also, tests to ensure null fields
                do not throw an exception.      
    #############Change Log#############
    Modified by     Version     Change Date
    Wiktor Czykin   1.1         19/08/2015  //update test class to check if certain fields got populated
    Lynette Lim     1.2         06/04/2016  //update test class to reflect new data model changes with Unbundling
    Gavin Palmer    1.3         02/06/2016  // modified the subscription status so that additional renewal subs arent created
    ****************************************************************************************/    
    static testMethod void TestSubscriptionInRenewalTrigger3 () {
        TestDataUtility td = new TestDataUtility(5);
        td.loadEntitlementsSettings();
        td.loadEntitlementsMappingSettings();
        td.loadSAMHTTPSettings();
        td.loadGeneral();
        td.loadPlaneURL();
        td.createRetailers();
        td.createZProductFeatures();
        td.createTCodeManagement();
        td.createSubscriptions();

        Integer countBefore = [SELECT count() FROM Subscription__c];
        Test.startTest();
            SubscriptionTriggerHandler.getInstance().bDeferredCalculationSkip = false;
            td.lstSubscriptions[0].Subscription_Status__c = 'hi';      
            td.lstSubscriptions[0].Product__c = td.lstZproducts[0].Id;
            update td.lstSubscriptions[0];
            
            Integer countAfter = [select count() from Subscription__c];
            System.assertEquals(countAfter, countBefore);
            
            Subscription__c Sub = [select Pricing_Error__c from subscription__c where Id = :td.lstSubscriptions[0].Id];
            System.assertEquals(false, Sub.Pricing_Error__c);
        Test.stopTest();
    }
    
    /*************************************************************************************** 
    Developer - unknown
    Date - unknown
    Version - 1.0
    Function - test new renewal button for cancelled or withdrawn subscriptions 
    #############Change Log#############
    Modified by         Version     Change Date
    Cristina Anghenie   1.1         19/08/2015  //update test class to check if certain fields got populated
    Pawel Chrzanowski   1.2         07/04/2016  //updated for new data model
    ****************************************************************************************/    
    static testMethod void TestSubscriptionInRenewalButton1 () {
        TestDataUtility tdu = new TestDataUtility(1);
        tdu.createRetailers();
        tdu.createZProductFeatures();
        tdu.createTCodeManagement();
        tdu.createSubscriptions();

        tdu.lstSubscriptions[0].Start_Date__c = Date.newInstance(2015,8,25);
        tdu.lstSubscriptions[0].Subscription_Status__c = 'Cancelled';
        tdu.lstSubscriptions[0].Cancellation_Date__c = Date.newInstance(2015,9,1);
        tdu.lstSubscriptions[0].Cancellation_Reason__c = 'Failed payment';
        tdu.lstSubscriptions[0].Cancellation_Method__c = 'Failed payment';
        tdu.lstSubscriptions[0].PaymentDate__c = '15';
        tdu.lstSubscriptions[0].MPP_DD_Frequency__c = 'Monthly';
        tdu.lstSubscriptions[0].isContinuous__c = true;
        tdu.lstSubscriptions[0].Product__c = tdu.lstZproducts[0].Id;
        update tdu.lstSubscriptions[0];
        
        Integer countBefore = [SELECT count() FROM Subscription__c WHERE Subscriber__c =: tdu.lstIndividualSubscribers[0].Id];
        
        Test.startTest();   
            String returnID = subscriptionInRenewalButton.subInRenewal(tdu.lstSubscriptions[0].Id);
        Test.stopTest();
        
        Id returnIDvalue = [select Id from subscription__c where previous_subscription__c =:tdu.lstSubscriptions[0].Id].Id;     
        Integer countAfter = [SELECT count() FROM Subscription__c WHERE Subscriber__c =: tdu.lstIndividualSubscribers[0].Id];
        System.assertEquals(returnIDvalue, returnID);
        System.assertEquals(countAfter, countBefore+1);
        
        Subscription__c renewedSub = [SELECT Subscription_Start_Calc__c, Price_Plan__c, New_Sub_Duration__c, Subscription_Status__c, Subscriber__c,
                                           Subscriber__r.RecordTypeId, Start_Date__c, End_Date__c, Previous_Subscription__c, Retailer__c, 
                                           Delivery_Type__c, Subscription_Duration_Picklist__c, Subscription_Duration_Number__c, 
                                           Weekly_Price__c, Previous_Price__c, Discount__c, payment_type__c, isContinuous__c, MPP_CC_Frequency__c, 
                                           RecordTypeId, PaymentDate__c, MPP_DD_Frequency__c, Order_Taken_Method__c, MppDDCalloutStage__c 
                                      FROM subscription__c WHERE previous_subscription__c =: tdu.lstSubscriptions[0].Id];
        System.assertEquals(tdu.lstSubscriptions[0].MPP_CC_Frequency__c,renewedSub.MPP_CC_Frequency__c);
        System.assertEquals(tdu.lstSubscriptions[0].MPP_DD_Frequency__c,renewedSub.MPP_DD_Frequency__c);
        System.assertEquals(tdu.lstSubscriptions[0].PaymentDate__c,renewedSub.PaymentDate__c);
        System.assertEquals('Auto Renewal',renewedSub.Order_Taken_Method__c );
        System.assertEquals('ManualRenewal',renewedSub.MppDDCalloutStage__c );
    }
    
    /*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/07/2015
    Version - 1.0
    Function - Check error handling method 
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    private static testmethod void testRaiseError() {
        TestDataUtility td = new TestDataUtility(1);
        td.loadSAMHTTPSettings();
        td.loadGeneral();
        td.loadPlaneURL();
        td.createSubscriptions();
        String sError = 'serror';
        Test.startTest();
            Test.setCurrentPage(Page.SiteLogin);
            subscriptionInRenewalCreation.raiseError(td.lstSubscriptions[0], sError, 'trigger');
        Test.stopTest();
        System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(),sError));
        System.assert(td.lstSubscriptions[0].Pricing_Error__c);
    }
}