src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retailer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>SLP-43: New formula field for subscriber number</description>
        <formula>IF( LEN( SRN__c ) &gt;= 7,
&quot;TS&quot; &amp; SRN__c,
&quot;TS&quot; &amp; LPAD( SRN__c , 7 , &quot;0&quot;)
)</formula>
        <inlineHelpText>New subscriber number reference</inlineHelpText>
        <label>Subscriber Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Email__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by email regarding offers</description>
        <label>TMG_Promo_Email</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Phone__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by phone regarding offers</description>
        <label>TMG_Promo_Phone</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Post__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by post regarding offers</description>
        <label>TMG_Promo_Post</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_SMS__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by SMS regarding offers</description>
        <label>TMG_Promo_SMS</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>This is the Vanity title field. (Lord, Lady, Sir etc.)</inlineHelpText>
        <label>Given Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Home_Delivery_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings supporting Home Delivery Vouchers object related functionality.</description>
    <fields>
        <fullName>Offer_Description__c</fullName>
        <description>Defines Offer Description that should be auto assigned based on the record type.</description>
        <inlineHelpText>Defines Offer Description that should be auto assigned based on the record type.</inlineHelpText>
        <label>Offer Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <description>Defines Offer Name that should be auto assigned based on the record type.</description>
        <inlineHelpText>Defines Offer Name that should be auto assigned based on the record type.</inlineHelpText>
        <label>Offer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Home Delivery Settings</label>
</CustomObject>

src/objects/Home_Delivery_Voucher__c.object
<CustomObject>
    <description>Object that holds information about Deliver My Newspaper 3rd party platform usage or manual, call center defined home deliveries.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Link to account record.</description>
        <inlineHelpText>Link to account record.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Home Delivery Vouchers</relationshipLabel>
        <relationshipName>Home_Delivery_Vouchers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_Days__c</fullName>
        <description>Defines days at which the newspaper should be delivered.</description>
        <inlineHelpText>Defines days at which the newspaper should be delivered.</inlineHelpText>
        <label>Delivery Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thu</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
                <value>
                    <fullName>Sat</fullName>
                </value>
                <value>
                    <fullName>Sun</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Defines offer description. It is auto-populated based on the source of the record.</description>
        <inlineHelpText>Defines offer description. It is auto-populated based on the source of the record.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email - in some cases might be different to the email on the related account.</description>
        <inlineHelpText>Email - in some cases might be different to the email on the related account.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the subscriber using home delivery voucher.</description>
        <inlineHelpText>First name of the subscriber using home delivery voucher.</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the subscriber using home delivery voucher.</description>
        <inlineHelpText>Last name of the subscriber using home delivery voucher.</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address__c</fullName>
        <description>Address information - in some cases might be different to the address on the related account.</description>
        <inlineHelpText>Address information - in some cases might be different to the address on the related account.</inlineHelpText>
        <label>Mailing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_County__c</fullName>
        <description>County - in some cases might be different to the address on the related account.</description>
        <inlineHelpText>County - in some cases might be different to the address on the related account.</inlineHelpText>
        <label>Mailing County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code__c</fullName>
        <description>Post Code - in some cases might be different to the address on the related account.</description>
        <inlineHelpText>Post Code - in some cases might be different to the address on the related account.</inlineHelpText>
        <label>Mailing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Town__c</fullName>
        <description>Town - in some edge cases might be different to the address field on the related account.</description>
        <inlineHelpText>Town - in some edge cases might be different to the address field on the related account.</inlineHelpText>
        <label>Mailing Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Preference_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if subscriber agreed to being contacted by email.</description>
        <inlineHelpText>Defines if subscriber agreed to being contacted by email.</inlineHelpText>
        <label>Marketing Preference Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_Preference_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if subscriber agreed to being contacted by phone.</description>
        <inlineHelpText>Defines if subscriber agreed to being contacted by phone.</inlineHelpText>
        <label>Marketing Preference Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_Preference_Post__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if subscriber agreed to being contacted by post.</description>
        <inlineHelpText>Defines if subscriber agreed to being contacted by post.</inlineHelpText>
        <label>Marketing Preference Post</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_Preference_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if subscriber agreed to being contacted by texts.</description>
        <inlineHelpText>Defines if subscriber agreed to being contacted by texts.</inlineHelpText>
        <label>Marketing Preference SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <description>Defines offer name. It is auto-populated based on the source of the record.</description>
        <inlineHelpText>Defines offer name. It is auto-populated based on the source of the record.</inlineHelpText>
        <label>Offer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone number of the subscriber.</description>
        <inlineHelpText>Phone number of the subscriber.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product determined by the number of delivery days.</description>
        <inlineHelpText>Product determined by the number of delivery days.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Print products for home delivery.</errorMessage>
            <filterItems>
                <field>zqu__ZProduct__c.Print_Product__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Home Delivery Vouchers</relationshipLabel>
        <relationshipName>Home_Delivery_Vouchers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Retailer (Account)</description>
        <inlineHelpText>Link to Retailer (Account)</inlineHelpText>
        <label>Retailer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Not a valid Retailer.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Retailer Account</value>
            </filterItems>
            <filterItems>
                <field>Account.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, TMG System, Clock</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Home Delivery Vouchers (Retailer)</relationshipLabel>
        <relationshipName>Home_Delivery_Vouchers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <description>Subscriber number specified by customer on the registration form. Might not match the related account record.</description>
        <inlineHelpText>Subscriber number specified by customer on the registration form. Might not match the related account record.</inlineHelpText>
        <label>Subscriber Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Home Delivery Voucher</label>
    <nameField>
        <displayFormat>X-{000000}</displayFormat>
        <label>Home Delivery Voucher Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Delivery Vouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HomeDeliveryServiceControllerTest.cls
/**
* @author Wiktor Czykin 
* @date 24/07/2017
* @description  tests for HomeDeliveryServiceController
*#############Change Log#############
*Modified by     Change Date
*/
@isTest
public with sharing class HomeDeliveryServiceControllerTest {

    /***************************************************************************************
    Developer - Wiktor Czykin
    Date - 24/07/2017
    Function - just basic assertion of init
    #############Change Log#############
    Modified by     Change Date  
    ****************************************************************************************/
    private static testMethod void testInit(){
        Test.startTest();
            HomeDeliveryServiceController hds = new HomeDeliveryServiceController(new ApexPages.StandardController(new Account()));
        Test.stopTest();
        System.assertNotEquals(null, hds.accEditController);
        System.assertNotEquals(null, hds.homeDeliveryItem);
        System.assertEquals(RecordTypeUtility.getRecordTypeId(Home_Delivery_Voucher__c.SObjectType, Constants.HOMEDELIVERYVOUCHER_HOMEDELIVERYSERVICE_RECORD_TYPE_NAME, Home_Delivery_Voucher__c.class.getName()), hds.homeDeliveryItem.RecordTypeId);
    }

    /***************************************************************************************
    Developer - Wiktor Czykin
    Date - 24/07/2017
    Function - test successful creation of Account and related Home Delivery Service record 
    #############Change Log#############
    Modified by     Change Date  
    ****************************************************************************************/
    private static testMethod void testSaveAndNew(){
        TestDataUtility td = new TestDataUtility(1);
        td.checkAccountDependencies();
        td.loadCountryCodes();
        td.createZProductFeatures();
        td.lstZFeature[0].Active_Days__c = 'SAT-SUN';
        update td.lstZFeature;
        Map<String, Home_Delivery_Settings__c> mapSettings = td.createHomeDeliverySettings();
        
        td.createRetailers();

        Test.startTest();
            HomeDeliveryServiceController hds = new HomeDeliveryServiceController(new ApexPages.StandardController(new Account()));
            HomeDeliveryServiceController.bForceSamCreation = true;

            Account acc = hds.accEditController.getAccount();
            hds.accEditController.tmgPromoEmail = true;
            hds.accEditController.tmgPromoPhone = true;
            hds.accEditController.tmgPromoPost = true;
            hds.accEditController.tmgPromoSms = true;
            hds.accEditController.contact.FirstName = 'kot';
            hds.accEditController.contact.LastName = 'jaroslawa';
            hds.accEditController.contact.Salutation = 'mrs';
            acc.Title__c = 'kitka';
            acc.PersonMailingStreet = 'street1';
            acc.PersonMailingState = 'state1';
            acc.PersonMailingPostalCode = 'sw1w 0dt';
            acc.PersonMailingCity = 'London';
            acc.PersonHomePhone = '099999';
            acc.PersonMobilePhone = '088888';
            acc.PersonEmail = 'someemail@telegraph.co.uk';
            hds.homeDeliveryItem.Retailer__c = td.lstRetailers[0].Id;
            hds.homeDeliveryItem.Delivery_Days__c = 'Sat;Sun';
            PageReference pr = hds.saveDetailsAndNew(); 
        Test.stopTest();
        System.assertNotEquals(null, pr, ApexPages.getMessages());

        List<Account> lstAccount = [SELECT  Id, 
                                            Salutation,
                                            FirstName,
                                            LastName,
                                            Subscriber_Number__c,
                                            PersonMailingStreet,
                                            PersonMailingState,
                                            PersonMailingPostalCode,
                                            PersonMailingCity,
                                            TMG_Promo_Email__c,
                                            TMG_Promo_Phone__c,
                                            TMG_Promo_Post__c,
                                            TMG_Promo_SMS__c,
                                            PersonHomePhone,
                                            PersonEmail,
                                            Guid__c
                                        FROM Account 
                                        WHERE RecordTypeId = :RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.RECTYPE_PERSONACCOUNT_INDIVIDUAL_SUBSCRIBER, Account.class.getName())];
        System.assertEquals(1, lstAccount.size());
        Account a = lstAccount[0];
        System.assert(String.isNotBlank(a.Guid__c));
        System.assertEquals(acc.Title__c, a.Salutation);
        System.assertEquals(acc.PersonMailingStreet, a.PersonMailingStreet);
        System.assertEquals(acc.PersonMailingState, a.PersonMailingState);
        System.assertEquals(acc.PersonMailingPostalCode.toUpperCase(), a.PersonMailingPostalCode);
        System.assertEquals(acc.PersonMailingCity, a.PersonMailingCity);
        System.assertEquals(acc.PersonHomePhone, a.PersonHomePhone);
        System.assertEquals(acc.PersonEmail, a.PersonEmail);
        System.assertEquals(hds.accEditController.contact.FirstName, a.FirstName);
        System.assertEquals(hds.accEditController.contact.LastName, a.LastName);
        List<Home_Delivery_Voucher__c> lstHdv = [SELECT Id, 
                                                        Account__c, 
                                                        Delivery_Days__c, 
                                                        Description__c,
                                                        Email__c,
                                                        First_Name__c,
                                                        Last_Name__c,
                                                        Mailing_Address__c,
                                                        Mailing_County__c,
                                                        Mailing_Postal_Code__c,
                                                        Mailing_Town__c,
                                                        Marketing_Preference_Email__c,
                                                        Marketing_Preference_Phone__c,
                                                        Marketing_Preference_Post__c,
                                                        Marketing_Preference_SMS__c,
                                                        Offer_Name__c,
                                                        Phone__c,
                                                        Product__c,
                                                        Retailer__c,
                                                        Subscriber_Number__c
                                                    FROM Home_Delivery_Voucher__c
                                                    WHERE Id = :hds.homeDeliveryItem.Id];
        System.assertEquals(1, lstHdv.size());
        Home_Delivery_Voucher__c h = lstHdv[0];
        System.assertEquals(a.FirstName, h.First_Name__c);
        System.assertEquals(a.LastName, h.Last_Name__c);
        System.assert(String.isNotBlank(h.Delivery_Days__c));
        System.assertEquals(mapSettings.get(Constants.HOMEDELIVERYVOUCHER_HOMEDELIVERYSERVICE_RECORD_TYPE_NAME).Offer_Name__c, h.Offer_Name__c);
        System.assertEquals(mapSettings.get(Constants.HOMEDELIVERYVOUCHER_HOMEDELIVERYSERVICE_RECORD_TYPE_NAME).Offer_Description__c, h.Description__c);
        System.assertEquals(a.PersonEmail, h.Email__c);
        System.assertEquals(a.PersonMailingStreet, h.Mailing_Address__c);
        System.assertEquals(a.PersonMailingState, h.Mailing_County__c);
        System.assertEquals(a.PersonMailingPostalCode, h.Mailing_Postal_Code__c);
        System.assertEquals(a.PersonMailingCity, h.Mailing_Town__c);
        System.assertEquals(a.PersonHomePhone, h.Phone__c);
        System.assertEquals(td.lstZProducts[0].Id, h.Product__c);
        System.assertEquals(a.TMG_Promo_Email__c, h.Marketing_Preference_Email__c?1:0);
        System.assertEquals(a.TMG_Promo_Phone__c, h.Marketing_Preference_Phone__c?1:0);
        System.assertEquals(a.TMG_Promo_Post__c, h.Marketing_Preference_Post__c?1:0);
        System.assertEquals(a.TMG_Promo_SMS__c, h.Marketing_Preference_SMS__c?1:0);
        System.assertEquals(td.lstRetailers[0].Id, h.Retailer__c);
        System.assertEquals(a.Subscriber_Number__c, h.Subscriber_Number__c);
    }

    /***************************************************************************************
    Developer - Wiktor Czykin
    Date - 24/07/2017
    Function - test failure of insert of Home_Delivery_Voucher__c
    #############Change Log#############
    Modified by     Change Date  
    ****************************************************************************************/
    private static testMethod void testSaveFailure(){
        TestDataUtility td = new TestDataUtility(1);
        td.loadCountryCodes();
        td.createZProductFeatures();
        td.lstZFeature[0].Active_Days__c = 'SAT-SUN';
        update td.lstZFeature;
        td.createRetailers();
        Test.startTest();
            HomeDeliveryServiceController hds = new HomeDeliveryServiceController(new ApexPages.StandardController(new Account()));
            Account acc = hds.accEditController.getAccount();
            hds.accEditController.contact.FirstName = 'kot';
            hds.accEditController.contact.LastName = 'jaroslawa';
            hds.accEditController.contact.Salutation = 'mrs';
            acc.PersonMailingStreet = 'street1';
            acc.PersonMailingState = 'state1';
            acc.PersonMailingPostalCode = 'sw1w 0dt';
            acc.PersonMailingCity = 'London';
            acc.PersonHomePhone = '099999';
            hds.homeDeliveryItem.Retailer__c = td.lstRetailers[0].Id;
            hds.homeDeliveryItem.Delivery_Days__c = 'SatSun';
            PageReference pr = hds.saveDetails();
        Test.stopTest();
        System.assertEquals(null, pr);
        List<Account> lstAccount = [SELECT  Id FROM Account 
                                        WHERE RecordTypeId = :RecordTypeUtility.getRecordTypeId(Account.SObjectType, Constants.RECTYPE_PERSONACCOUNT_INDIVIDUAL_SUBSCRIBER, Account.class.getName())];
        System.assert(lstAccount.isEmpty());
    }
}