src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>

    <fields>
        <fullName>OC_Call_Stage__c</fullName>
        <description>Outbound call stage name</description>
        <inlineHelpText>Outbound call stage name</inlineHelpText>
        <label>Call Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>T2</fullName>
                </value>
                <value>
                    <fullName>T2 Catch Up</fullName>
                </value>
                <value>
                    <fullName>TL1</fullName>
                </value>
                <value>
                    <fullName>TL2</fullName>
                </value>
                <value>
                    <fullName>BR1</fullName>
                </value>
                <value>
                    <fullName>CCEX1</fullName>
                </value>
                <value>
                    <fullName>DD Winback</fullName>
                </value>
                <value>
                    <fullName>DDCX</fullName>
                </value>
                <value>
                    <fullName>T2 28Days</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Outcome__c</fullName>
        <description>The outcome of the outbound call</description>
        <inlineHelpText>Please specify the outcome of the outbound call</inlineHelpText>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Cheque Sales</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>NATC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Scheduled_Callback__c</fullName>
        <description>Date/Time field for new outbound call task filter logic. This field is auto-populated from controller.</description>
        <inlineHelpText>The field to hold the date and time when the callback need to be done. Enter the date and time when the call need to be rescheduled only if you want override standard rescheduling functionality.</inlineHelpText>
        <label>Scheduled Callback</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Subscription_Outstanding_Balance__c</fullName>
        <description>Outstanding Balance from related Print Subscription</description>
        <formula>ABS(Print_Subscription__r.Outstanding_Balance_to_from_Customer__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Outstanding Balance from related Print Subscription</inlineHelpText>
        <label>Subscription Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    
    <fields>
        <fullName>Print_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Subscription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subscription__c.Subscriber__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <inlineHelpText>Product Name is automatically populated with related Print Subscription&apos;s Product Name</inlineHelpText>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Zuora Subscription</description>
        <inlineHelpText>Lookup field to Zuora Subscription</inlineHelpText>
        <label>Zuora Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>




</CustomObject>

src/objects/Outbound_Call_Rule__c.object
<CustomObject>
    <description>Configuration object for record selection for different types of calls</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Rule is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Answered__c</fullName>
        <description>Number of minutes for the Answered call status</description>
        <inlineHelpText>Define the number of minutes before the Case is again ready for pick-up after call status is set to Answerphone</inlineHelpText>
        <label>Answerphone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Busy__c</fullName>
        <description>Number of minutes for the Busy call status</description>
        <inlineHelpText>Define the number of minutes before the Case is again ready for pick-up after call status is set to Busy</inlineHelpText>
        <label>Call Busy</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_No_Answer__c</fullName>
        <description>Number of minutes for the No Answer call status</description>
        <inlineHelpText>Define the number of minutes before the Case is again ready for pick-up after call status is set to No Answer</inlineHelpText>
        <label>Call No Answer</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Record_Entry__c</fullName>
        <description>Call Record Entry</description>
        <inlineHelpText>Defines by how many minutes record pickup is postponed when record is brought into context</inlineHelpText>
        <label>Call Record Entry</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outbound_Call_Setting__c</fullName>
        <description>Related Outbound Call Setting</description>
        <inlineHelpText>Define Outbound Call Setting Master</inlineHelpText>
        <label>Outbound Call Setting</label>
        <referenceTo>Outbound_Call_Setting__c</referenceTo>
        <relationshipLabel>Outbound Call Rules</relationshipLabel>
        <relationshipName>Outbound_Call_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Priority_Field__c</fullName>
        <description>Priority field API name</description>
        <inlineHelpText>Define the Priority field API name for the type of the call</inlineHelpText>
        <label>Priority Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outbound Call Rule</label>
    <nameField>
        <label>Outbound Call Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Call_Setting__c.object
<CustomObject>
    <description>Configuration object for Outbound Calling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Setting is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <description>Case record type label name. Settings are applied to all case records with specified record type</description>
        <inlineHelpText>Case record typelabel name. Settings are applied to all case records with specified record type</inlineHelpText>
        <label>Case Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Menu_Name__c</fullName>
        <description>Menu name</description>
        <inlineHelpText>Define menu name of the call</inlineHelpText>
        <label>Menu Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Order number</description>
        <inlineHelpText>Define in what order the outbound calling items are shown on the Outbound Calling page</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visualforce_Page__c</fullName>
        <description>Visualforce Page name</description>
        <inlineHelpText>Define the Visualforce page that serves the functionality</inlineHelpText>
        <label>Visualforce Page</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Outbound Call Setting</label>
    <nameField>
        <label>Outbound Call Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_to_from_Customer__c</fullName>
        <description>28/04/10 SB: Change as per Richard Harte request
Old: Astra_Migration_Balance__c + Liab_Calc__c -  Voucher_Amount_Used__c +  Revenue_Write_off_Amount__c</description>
        <formula>IF(End_Date__c&gt; DATE(2009,01,01), Astra_Migration_Balance__c + (Liab_Calc__c - Voucher_Amount_Used__c) + Revenue_Write_off_Amount__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If positive, outstanding balance is to customer. If negative, customer owes TMG.</inlineHelpText>
        <label>Outstanding Balance to/(from) Customer</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reltionship to the Tcode object</description>
        <label>TCodeManagement</label>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weekly_Price__c</fullName>
        <label>Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OutboundCallingCCExpiryCtrl.cls
/**
* Author:       Michal Szewczyk
* Date:         27/07/2016
* Description:  CC Expiry Date page controller
*
* ******************* Change Log *******************
* Modified by       Change Date
**/
public with sharing class OutboundCallingCCExpiryCtrl {
    
    public Case selectedCase {get;set;}
    public String casesTotal {get;set;}
    public Integer casesTotalCount {get;set;}
    public Boolean hasCustomer {get;set;}
    public Boolean hasPayments {get;set;}
    public Boolean hasVoucherActivities {get;set;}
    public Boolean isLastCustomer {get;set;}
    public Boolean isSaveButtonEnabled {get;set;}
    public Subscription__c customerSubscription {get;set;}

    public String stageName {get;set;}
    public String outcome {get;set;}
    public String callDateTime {get;set;}
    public String priorityField {get;set;}
    public Integer offset {get;set;}
    public Id recordTypeId {get;set;}
    public Integer callRecordEntry {get;set;}
    public MPPInterfaceHTTP mpp {get;set;}

    @testVisible private List<Case> lstCases;
    @testVisible private static Integer initialCaseLimit = 200;
    @testVisible private static Integer caseLimit = 100;

    
    /*************************************************************************************** 
    Developer - Michal Szewczyk
    Date - 27/07/2016
    Version - 1.0 
    Function - Constructor
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    public OutboundCallingCCExpiryCtrl() {
        
        hasCustomer = false;
        hasPayments = false;
        hasVoucherActivities = false;
        isLastCustomer = false;
        casesTotalCount = 0;
        casesTotal = '0';

        mpp = new MPPInterfaceHTTP();

        //get related Outbound Call Setting
        List<Outbound_Call_Setting__c> lstOcs = [SELECT Case_Record_Type__c, Menu_Name__c, Order__c FROM Outbound_Call_Setting__c WHERE Active__c = true AND Visualforce_Page__c = :Constants.OC_CREDIT_CARD_EXPIRY_VF_PAGE_NAME];
        if(lstOcs.isEmpty() || String.isBlank(lstOcs[0].Case_Record_Type__c)){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.OC_OCS_Incomplete));
            return;
        }
        recordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, lstOcs[0].Case_Record_Type__c, Case.class.getName());

        //parse related Outbound Call Setting's Parameters
        List<OutboundCallingBean.CallStageMapping> lstCsm;
        try{
            lstCsm = OutboundCallingUtils.getCallStageParametersByOCsettingId(lstOcs[0].Id);
            stageName = lstCsm[0].stagename;
            outcome = lstCsm[0].outcome;
            callDateTime = lstCsm[0].calldatetime;
            offset = lstCsm[0].offset;            
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.OC_OCS_Parameters_Error + ' ' + e.getMessage()));
            return;
        }

        //get related Outbound Call Rule
        List<Outbound_Call_Rule__c> lstOcr = [SELECT Call_Answered__c, Call_Busy__c, Call_No_Answer__c, Call_Record_Entry__c, Priority_Field__c FROM Outbound_Call_Rule__c WHERE Active__c = true AND Outbound_Call_Setting__c = :lstOcs[0].Id];
        if(!lstOcr.isEmpty()){
            callRecordEntry = (Integer)lstOcr[0].Call_Record_Entry__c;
            if(String.isNotBlank(lstOcr[0].Priority_Field__c)){
                priorityField = lstOcr[0].Priority_Field__c;
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.OC_OCR_Not_Found));
            return;
        }

        //initial query to count available Cases
        getAvailableCases(true, initialCaseLimit);
    }

    /*************************************************************************************** 
    Developer - Michal Szewczyk
    Date - 27/07/2016
    Version - 1.0 
    Function - method to run dynamic SOQL on Case
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk  1.1        27/09/2016  // changed CASE_STATUS_CLOSED to CASE_STATUS_COMPLETED
    ****************************************************************************************/
    private void getAvailableCases(Boolean isCount, Integer limitAmount){
        DateTime dateTimeNow = Datetime.now();
        String orderSegment = 'ORDER BY ' + (String.isNotBlank(priorityField) ? priorityField + ' DESC, ' : '') + callDateTime + ' DESC, OC_Subscription_Outstanding_Balance__c DESC NULLS LAST ';
        String query = 'SELECT ' + (isCount ? 'count()' : 'Id') + ' FROM Case ' + 
                        'WHERE RecordTypeId = \'' + recordTypeId + '\' ' + 
                        'AND Status != \'' + Constants.CASE_STATUS_COMPLETED + '\' ' + 
                        'AND OC_Call_Stage__c = \'' + stageName + '\' ' + 
                        'AND ' + callDateTime + ' <= :dateTimeNow ' + 
                        (isCount ? '' : orderSegment) + 
                        'LIMIT ' + limitAmount;
        System.debug('### query: ' + query);

        if(isCount){
            casesTotalCount = Database.countQuery(query);
        }else{
            lstCases = Database.query(query);
            casesTotalCount = lstCases.size();
        }
        casesTotal = casesTotalCount == initialCaseLimit ? String.valueOf(initialCaseLimit) + '+' : String.valueOf(casesTotalCount);
    }

    /*************************************************************************************** 
    Developer - Michal Szewczyk
    Date - 14/07/2016
    Version - 1.0 
    Function - method to get customer
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk  1.1        16/11/2016 - Added try catch for mpp request
    ****************************************************************************************/
    public void getCustomer(){
        hasCustomer = false;
        hasPayments = false;
        hasVoucherActivities = false;
        isLastCustomer = false;
        selectedCase = null;
        isSaveButtonEnabled = false;
        customerSubscription = null;

        lstCases = null;
        getAvailableCases(false, caseLimit);

        if(casesTotalCount == 1){
            isLastCustomer = true;
        }

        //pick and lock one Case from the selected list
        for(Case c : lstCases){
            try{
                selectedCase = [select  CaseNumber, Status, OC_Outcome__c,OC_Scheduled_Callback__c,
                                        AccountId, Account.Name, Account.Subscriber_Number_Static__c, Account.PersonEmail, 
                                        Account.PersonMobilePhone, Account.PersonHomePhone, Account.PersonMailingPostalCode, 
                                        Account.PersonMailingCountry, Account.PersonMailingState, Account.PersonMailingStreet, Account.PersonMailingCity, 
                                        Print_Subscription__c, Print_Subscription__r.Name, Print_Subscription__r.Product__c, Print_Subscription__r.Weekly_Price__c, 
                                        Print_Subscription__r.TCode__c, Print_Subscription__r.Start_Date__c, Print_Subscription__r.End_Date__c 
                                    from Case 
                                    where Id = :c.Id for update];
            }catch(Exception e){
                continue;
            }
            break;
        }
        if(selectedCase == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.OC_Case_Not_Found));
            return;
        } 
        try{
            mpp.initialise(selectedCase.Account.Subscriber_Number_Static__c);
        }catch(Exception e){

        }

        hasCustomer = true;

        selectedCase.put(callDateTime, Datetime.now().addMinutes(callRecordEntry));
        update selectedCase;
    }

    /*************************************************************************************** 
    Developer - Michal Szewczyk
    Date - 02/08/2016
    Version - 1.0 
    Function - method to enable save button
    #############Change Log#############`
    Modified by     Version     Change Date
    ****************************************************************************************/
    public void enableSaveButton(){
        isSaveButtonEnabled = true;
    }

    /*************************************************************************************** 
    Developer - Michal Szewczyk
    Date - 02/08/2016
    Version - 1.0 
    Function - method to save selected customer
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    public void saveSelectedCustomer(){
        try{
            update selectedCase;
            isSaveButtonEnabled = false;
        }catch(DmlException e){
            ApexPages.addMessages(e);
        }
        List<Case> lstCases = [SELECT Status, Print_Subscription__r.Outstanding_Balance_to_from_Customer__c FROM Case WHERE Id = :selectedCase.Id];
        selectedCase.Status = lstCases[0].Status;
    }

}