src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Jira:PP-1294 Need to have the full country name, not the code.</description>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMG_Loyalty_Email__c</fullName>
        <description>SLP-50: New marketing permissions field</description>
        <label>TMG Loyalty Email</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Loyalty_Mail__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SLP-50: New marketing permissions field</description>
        <label>TMG Loyalty Mail</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Loyalty_Phone__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SLP-50: New marketing permissions field</description>
        <label>TMG Loyalty Phone</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Loyalty_SMS__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SLP-50: New marketing permissions field</description>
        <label>TMG Loyalty SMS</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Partner_Promo_Email__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG partner organisations can contact them by email regarding offers</description>
        <label>TMG_Partner_Promo_Email</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Email__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by email regarding offers</description>
        <label>TMG_Promo_Email</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Phone__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by phone regarding offers</description>
        <label>TMG_Promo_Phone</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_Post__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by post regarding offers</description>
        <label>TMG_Promo_Post</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMG_Promo_SMS__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Customer agrees that TMG can contact them by SMS regarding offers</description>
        <label>TMG_Promo_SMS</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>This is the Vanity title field. (Lord, Lady, Sir etc.)</inlineHelpText>
        <label>Given Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_ID__c</fullName>
        <defaultValue>&quot;535T&quot;</defaultValue>
        <label>Wave ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country Codes</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Method__c</fullName>
        <label>Cancellation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Phone</fullName>
                </value>
                <value>
                <fullName>Email</fullName>
                </value>
                <value>
                <fullName>Letter</fullName>
                </value>
                <value>
                <fullName>ADDACS Notification</fullName>
                </value>
                <value>
                <fullName>AUDDIS Notification</fullName>
                </value>
                <value>
                <fullName>DD Reject</fullName>
                </value>
                <value>
                <fullName>DDIC Report</fullName>
                </value>
                <value>
                <fullName>Task</fullName>
                </value>
                <value>
                <fullName>DD Migration Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Within 14 days</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Serious illness</fullName>
                </value>
                <value>
                <fullName>Poor eyesight</fullName>
                </value>
                <value>
                <fullName>Gone Away</fullName>
                </value>
                <value>
                <fullName>Review of personal finances/cannot afford</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Editorial Issues</fullName>
                </value>
                <value>
                <fullName>Too much to read.</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Unpaid Cheque</fullName>
                </value>
                <value>
                <fullName>Duplicate File</fullName>
                </value>
                <value>
                <fullName>Dislike Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Fears Commitment</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved to Care Home</fullName>
                </value>
                <value>
                <fullName>Moving House (UK)</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
                <value>
                <fullName>Unknown</fullName>
                </value>
                <value>
                <fullName>Prefers online content</fullName>
                </value>
                <value>
                <fullName>Independent i</fullName>
                </value>
                <value>
                <fullName>DD Refer to Payer</fullName>
                </value>
                <value>
                <fullName>DD Cancelled by Payer</fullName>
                </value>
                <value>
                <fullName>DD No Instruction</fullName>
                </value>
                <value>
                <fullName>DD Account Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>HND</fullName>
                </value>
                <value>
                <fullName>OTC</fullName>
                <default>true</default>
                    <label>OTC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Voucher_Pack_Duration__c</fullName>
        <defaultValue>13</defaultValue>
        <description>Used to record if the subscription has 12 or 13 week voucher packs</description>
        <label>Voucher Pack Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weekly_Price__c</fullName>
        <label>Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SAMUtilTest.cls
/**
* @author Unknown
* @date Unknown
* @description Test class for SAMUtil
#############Change Log#############
Modified by     	Version     Change Date
Pawel Chrzanowski   1.1         14/03/2016  //modified setupSAMData_Digital(), setupSAMData_Premium() to test email update only
Pawel Chrzanowski   1.2         01/04/2016  //removed setupSAMData_Digital() and setupSAMData_Premium(), added setupSAMDataTest()
Michal Szewczyk     1.3         20/04/2016  //added setEntitlemetMapping to init()
**/
@isTest(SeeAllData=false)
private class SAMUtilTest {
    private static Account a;
    private static void init(){
        TestDataUtility tdu = new TestDataUtility();
        tdu.loadSAMHTTPSettings();
        tdu.loadGeneral();
        tdu.loadPlaneURL();
        tdu.setEntitlemetMapping();
    }
    
    
    /*  Setup the Test Account (it doesnt matter if Premium or Digital for this test)
    */
    private static String setupAccountData(){
        a = new Account();
        a.Title__c = 'Mr.';
        a.Guid__c = 'GUIDTestMethodData' + Math.random();
        a.Wave_ID__c = '445T'; 
        a.PersonTitle = 'Mr';
        a.FirstName = 'Testio';
        a.LastName = 'Testev';
        a.PersonEmail= DateTime.now().getTime() + 'testio@test.com';
        a.PersonMailingStreet = 'Cannon Street';
        a.PersonMailingCity = 'Reading';
        a.PersonMailingPostalCode = 'RG1';
        a.PersonMailingCountry = 'GB';
        a.PersonHomePhone = '077777777777';
        a.Origin__c = 'Online';
        a.Email_Sent__c = false;
        a.TMG_Promo_Email__c = 1;
        a.TMG_Promo_Phone__c = 1;
        a.TMG_Promo_Post__c = 1;
        a.TMG_Promo_SMS__c = 1;
        a.TMG_Loyalty_Email__c = 1;
        a.TMG_Loyalty_Phone__c = 1;
        a.TMG_Loyalty_Mail__c = 1;
        a.TMG_Loyalty_SMS__c =1;
        insert a;
    
        if(Country_Codes__c.getInstance('GB') == null){
            Country_Codes__c cc = new Country_Codes__c( name='GB', Country_Name__c='United Kingdom');
            insert cc;
        }
        String TsNumber = [select Subscriber_Number_static__c from Account where id=:a.id].Subscriber_Number_static__c;
        return TsNumber;        
    }
    
	/*************************************************************************************** 
    Developer - Pawel Chrzanowski
    Date - 31/03/2016
    Version - 1.0
    Function - Test setupSAMData()
    #############Change Log#############
	Modified by    		Version     Change Date
    ****************************************************************************************/
	private static testMethod void setupSAMDataTest(){    	
    	init();
    	String tsNumber = setupAccountData();
    	Account acc = [SELECT Id, RecordTypeId, GUID__c, Salutation, FirstName, LastName, PersonEmail, PersonMailingStreet, PersonMailingCity,
               PersonMailingPostalCode, PersonMailingCountry, PersonMailingState,
               PersonHomePhone, Origin__c, Email_Sent__c,  TMG_Promo_Email__c,  TMG_Promo_Phone__c,
               TMG_Promo_Post__c, TMG_Promo_SMS__c, TMG_Loyalty_Email__c, TMG_Loyalty_SMS__c, 
               TMG_Partner_Promo_Email__c, Subscriber_Number_static__c, Subscriber_Digital_Status__c, Product__c From Account WHERE Subscriber_Number_Static__c=:tsNumber];
    	
		Id rt = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_DEFAULT, Subscription__c.class.getName());
		Date startDate = UtilitySelectOptionsSubscriptions.getFirstStartDate(5);
    	Subscription__c sub = new Subscription__c(Voucher_Pack_Duration__c=1, Cancellation_Date__c=null, Cancellation_Method__c=null, Cancellation_Reason__c=null, Start_Date__c=startDate, Payment_Type__c='Cheque', Delivery_Type__c='OTC', Weekly_Price__c=5, Subscription_Status__c=Constants.SSTATUS_ACTIVE, Subscription_Duration_Picklist__c='26', Subscriber__c=acc.Id, RecordTypeId=rt, Payment_Details_Received__c=true);
    	insert sub;

    	Test.startTest();
    		SAMUtil samUtil = new SAMUtil();
    		SubscriptionsSAMWebservices.commonRequest request = samUtil.setupSAMData(acc, tsNumber, 'digital');
        	System.assertEquals(acc.Salutation, request.title);
        	System.assertEquals(acc.LastName, request.lastname);
        	System.assertEquals(acc.FirstName, request.firstname);
        	System.assertEquals(acc.PersonEmail, request.email);
        	System.assertEquals(acc.PersonMailingStreet, request.street);
        	System.assertEquals(acc.PersonMailingCity, request.city);
        	System.assertEquals(acc.PersonMailingPostalCode, request.postcode);
        	System.assertEquals(acc.PersonMailingCountry, request.country);
        	System.assertEquals(acc.PersonMailingState, request.county);
        	System.assert(request.marketingEmailPref);
        	System.assert(request.marketingPhonePref);
        	System.assert(request.marketingPostPref);
        	System.assert(request.marketingSMSPref);
        	System.assert(!request.marketing3rdPref);
        	System.assert(request.subscribersOfferPref);        	
        	System.assertEquals(samUtil.SAMServiceKey, request.samServiceKey);
        	System.assertEquals(tsNumber, request.tsNumber);
        	System.assertEquals(SubscriberPortal.SEVENDAY_ENT_PREFIX + Constants.SSTATUS_ACTIVE.toUpperCase(), request.entitlements);
        Test.stopTest();
    }
    
    public static testMethod void testisExistingSamAccount(){
    	init();
    	SAMUtil samUtil = new SAMUtil();
    	
    	Exception ex;
    	try{
    		System.assertEquals(null, samUtil.isExistingSamAccount(''));
    	}
		catch(WebserviceUtil.NullParameterException e){
			ex = e;
		}
		System.assert(ex instanceof WebserviceUtil.NullParameterException);
		
		try{
    		System.assertEquals(null, samUtil.isExistingSamAccount(null));
    	}
		catch(WebserviceUtil.NullParameterException e){
			ex = e;
		}
		System.assert(ex instanceof WebserviceUtil.NullParameterException);
    	
        Test.startTest();
        
        String Guid = samUtil.isExistingSamAccount('test');
        Test.stopTest();
        System.assertEquals('GUID__TEST', Guid);
    }
    
    /*************************************************************************************** 
    Developer - Unknown
    Date - Unknown
    Version - 1.1
    Function -
    #############Change Log#############
    Modified by     Version     Change Date
    Wiktor Czykin   1.1         04/09/2015  //removed TestDataUtility.insertErrorMessage() call
    ****************************************************************************************/
    public static testMethod void testGetExistingSAMAccount(){
        init();
        SAMUtil samUtil = new SAMUtil();
        
        Exception ex;
        try{
            System.assertEquals('INACTIVE', samUtil.getExistingSAMAccount('').entitlementStatus);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        try{
            System.assertEquals('INACTIVE', samUtil.getExistingSAMAccount(null).entitlementStatus);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        SAMUtil.SAMAccountResult result;
        Test.startTest();
            result = samUtil.getExistingSAMAccount('test');
        Test.stopTest();
        
        System.assertEquals('GUID__TEST', result.guid);
        System.assertEquals('INACTIVE', result.entitlementStatus);

        // test criteria added for ACCOUNT_LOCKED scenario in response.status
        String errMessage = '';
        try{
            samUtil.getExistingSAMAccount('ACCOUNT_LOCKED@TEST');
        }
        catch(WebserviceUtil.SamException e){
            errMessage = e.getError().errorMessage;
            System.debug('ACCOUNT_LOCKED ERROR THROWN - ' + errMessage);
            System.debug(Label.SAM_Account_locked_error);
        }
        System.assert(errMessage.contains('ACCOUNT_LOCKED'));
    }
    
    public static testMethod void testupdateSamAccount(){
        init();
        String TsNumber = setupAccountData();
        System.debug('TsNumber: '+TsNumber);
        
        SAMUtil samUtil = new SAMUtil();
        
        Exception ex;
        try{
            samUtil.updateSamAccount(a, '', a.Guid__c, 'digital', true);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        try{
            samUtil.updateSamAccount(a, null, a.Guid__c, 'digital', true);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        Test.startTest();
        
        ex = null;
        try{
            samUtil.updateSamAccount(a, TsNumber, a.Guid__c, 'digital', true);
        }
        catch(Exception e){
            ex = e;
        }
        Test.stopTest();
        System.assertEquals(null, ex);
    }
    
    public static testMethod void testcreateSamAccount(){
        init();
        String TsNumber = setupAccountData();
        System.debug('TsNumber: '+TsNumber);
        
        SAMUtil samUtil = new SAMUtil();
        
        Exception ex;
        try{
            samUtil.createSamAccount(a, '', 'digital', true, false);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        try{
            samUtil.createSamAccount(a, null, 'digital', true, false);
        }
        catch(WebserviceUtil.NullParameterException e){
            ex = e;
        }
        System.assert(ex instanceof WebserviceUtil.NullParameterException);
        
        Test.startTest();
        
        ex = null;
        String Guid;
        try{
            Guid = samUtil.createSamAccount(a, TsNumber, 'digital', true, false);
        }
        catch(Exception e){
            ex = e;
        }
        Test.stopTest();
        System.assertEquals('GUID__TEST', Guid);
        System.assertEquals(null, ex);
    }
}