src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Jira:PP-1294 Need to have the full country name, not the code.</description>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Digital_Status__c</fullName>
        <defaultValue>&apos;Inactive&apos;</defaultValue>
        <label>Subscriber Digital Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <description>SLP-61: SB 23/02/10: Change logic on Subscriber Status</description>
        <formula>IF( (Subscription_Status_calc__c + Count_Pending_Cancel_Still_Active__c ) &gt; 0, &apos;Active&apos;, IF( Number_of_Pending_Subscriptions__c &gt; 0, &apos;Pending&apos;, &apos;Inactive&apos; ))</formula>
        <label>Print Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EU</label>
        <type>Checkbox</type>
    </fields>
    <label>Country Codes</label>
</CustomObject>

src/objects/MPP_Transaction_History__c.object
<CustomObject>
    <fields>
        <fullName>DD_Transaction_Type__c</fullName>
        <label>DD Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>AUDDIS</fullName>
                </value>
                <value>
                <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_status__c</fullName>
        <label>Payment status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Failed</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Refund</fullName>
                </value>
                <value>
                <fullName>Success</fullName>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscriber Account</description>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MPP Transaction Histories</relationshipLabel>
        <relationshipName>MPP_Transaction_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <formula>Subscription__r.Start_Date__c</formula>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>MPP Transaction Histories</relationshipLabel>
        <relationshipName>MPP_Transaction_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Country__c</fullName>
        <label>VAT Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VAT_Type__c</fullName>
        <label>VAT Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>UK Standard</fullName>
                <default>true</default>
                    <label>UK Standard</label>
                </value>
                <value>
                <fullName>EU Standard</fullName>
                </value>
                <value>
                <fullName>UK Zero</fullName>
                </value>
                <value>
                <fullName>Non EU Exempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MPP Transaction History</label>
    <nameField>
        <displayFormat>MPP-{0000}</displayFormat>
        <label>MPP Transaction History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPP Transaction Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Digital_VAT_Rate__c</fullName>
        <label>Digital VAT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Start_Date__c + ((Subscription_Duration_Number__c * 7)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IF_11_Week_Renewal_Update_Date_Hidden__c</fullName>
        <formula>End_Date__c -78</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IF 11 Week Renewal Update Date Hidden</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IF_DD_D03_Extraction_Date__c</fullName>
        <description>Shows the D03 extraction date for subs paid by DD.</description>
        <formula>IF(ISPICKVAL(Payment_Type__c,&apos;Direct Debit&apos;), End_Date__c - 43,null)</formula>
        <label>D03 Extraction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_One_Off_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is used to check the in the trigger to see whether subscription status need to be updated to Pending or not</description>
        <label>Is One Off Payment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Details_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Details Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total price for the subscription.</description>
        <formula>IF(
   Subscription_Duration_Number__c == 13, 
   IF(
      TCode_Product__r.X13_Week_Price__c == 0, 
      Weekly_Price__c * 13,
      TCode_Product__r.X13_Week_Price__c
   ),
   (Subscription_Duration_Number__c * Weekly_Price__c  - IF(
                                                            NOT(ISNULL(Low_Start_Weekly_Price__c)),
                                                            Low_Start_Period__c * (Weekly_Price__c - Low_Start_Weekly_Price__c),
                                                            0
                                                           )
   )
   )*MAX(Quantity__c, 1)
</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total price for the subscription.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WeeklyDigitalVAT__c</fullName>
        <label>Weekly Digital VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WeeklyPrintPrice__c</fullName>
        <label>Weekly Print Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weekly_Price__c</fullName>
        <label>Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VAT__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EU_Standard_VAT_Rate__c</fullName>
        <label>EU Standard VAT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UK_Standard_VAT_Rate__c</fullName>
        <label>UK Standard VAT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vat_rate__c</fullName>
        <label>Vat_rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>VAT</label>
</CustomObject>

src/objects/Voucher_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Voucher Activities</relationshipLabel>
        <relationshipName>Voucher_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Voucher Activity</label>
    <nameField>
        <displayFormat>VA-{0000000000}</displayFormat>
        <label>Voucher Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MPPTransactionHistoryTriggerHandler.cls
/**
* @author Unknown
* @date Unknown
* @description Handler class for MPPTransactionHistoryTrigger trigger
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         29/07/2015  //added singleton pattern, moved action methods from MPPTransactionHistoryTriggerActions
**/
public class MPPTransactionHistoryTriggerHandler {

	private static MPPTransactionHistoryTriggerHandler instance;
    public Boolean isExecuting = false;
				
    public static MPPTransactionHistoryTriggerHandler getInstance() {
        if (instance == null) instance = new MPPTransactionHistoryTriggerHandler();
        return instance; 
    }

	public void OnBeforeInsert(MPP_Transaction_History__c[] newMPPTransactionHistories){
		 if (!this.isExecuting){
            this.isExecuting = true;

		 	this.CalculateVAT(newMPPTransactionHistories);

		  	this.isExecuting = false;        
        }
	}
	
	public void OnAfterInsert(MPP_Transaction_History__c[] newMPPTransactionHistories){
		if (!this.isExecuting) {
        	this.isExecuting = true;
			
			this.UpdateDeferredRevenue(newMPPTransactionHistories);
			this.UpdateSubscriptionDetails(newMPPTransactionHistories);

			this.isExecuting = false;        
        }
	}
	
	public void OnBeforeUpdate(MPP_Transaction_History__c[] oldMPPTransactionHistories, MPP_Transaction_History__c[] updatedMPPTransactionHistories, Map<ID, MPP_Transaction_History__c> MPPTransactionHistoryMap){
		if (!this.isExecuting) {
        	this.isExecuting = true;

			this.CalculateVAT(updatedMPPTransactionHistories);

			this.isExecuting = false;        
        }
	}
	
	public void OnAfterUpdate(MPP_Transaction_History__c[] oldMPPTransactionHistories, MPP_Transaction_History__c[] updatedMPPTransactionHistories, Map<ID, MPP_Transaction_History__c> OldMPPTransactionHistoryMap, Map<ID, MPP_Transaction_History__c> NewMPPTransactionHistoryMap){
		if (!this.isExecuting) {
        	this.isExecuting = true;

			this.UpdateDeferredRevenue(updatedMPPTransactionHistories);
			this.UpdateSubscriptionDetails(updatedMPPTransactionHistories);

			this.isExecuting = false;        
        }
	}
	
	public void OnBeforeDelete(MPP_Transaction_History__c[] MPPTransactionHistoriesToDelete, Map<ID, MPP_Transaction_History__c> MPPTransactionHistoryMap){}
	
	public void OnAfterDelete(MPP_Transaction_History__c[] deletedMPPTransactionHistories, Map<ID, MPP_Transaction_History__c> MPPTransactionHistoryMap){
		if (!this.isExecuting) {
        	this.isExecuting = true;

			this.UpdateDeferredRevenue(deletedMPPTransactionHistories);

			this.isExecuting = false;        
        }
	}
	
	
	public void OnUndelete(MPP_Transaction_History__c[] restoredMPPTransactionHistories){
		if (!this.isExecuting) {
        	this.isExecuting = true;

			this.UpdateDeferredRevenue(restoredMPPTransactionHistories);

			this.isExecuting = false;        
        }
	}
	
	/*************************************************************************************** 
	Developer - Unknown
	Date - Unknown
	Version - 1.1
	Function - Update the deferred revenue for the premium subscriptions that these transactions relate to
	#############Change Log#############
	Modified by     Version     Change Date
	Wiktor Czykin   1.1         18/06/2015  //modified the way how DeferredCalculation is called 
	****************************************************************************************/
	public void UpdateDeferredRevenue(List<MPP_Transaction_History__c> MPPTransactionHistories){
	
		if (DeferredCalculation.isTestScenario == null) {DeferredCalculation.isTestScenario = false;}
		if (DeferredCalculation.inDeferredCalc == null) {DeferredCalculation.inDeferredCalc = false;}
		
		if (DeferredCalculation.isTestScenario || DeferredCalculation.inDeferredCalc) 
			return;
	
		DeferredCalculation.inDeferredCalc = true;
		DeferredCalculation.DeferredRevenueCalc calc = new DeferredCalculation.DeferredRevenueCalc();
	
		Set<Id> subIds = new Set<Id>();
		for (MPP_Transaction_History__c txn : MPPTransactionHistories) {
			if(txn.Subscription__c != null && !subIds.contains(txn.Subscription__c)) {
				subIds.add(txn.Subscription__c);
			}
		}	
		
		calc.addSubsForProcessing(subIds);
		calc.GetSubData();
		calc.Calculate();
		calc.UpdateValues();
		DeferredCalculation.inDeferredCalc = false;
	}		
	
	/*************************************************************************************** 
	Developer - Unknown
	Date - Unknown
	Version - 1.1
	Function - Manage the changing of the subscription state (premium and digital) based on the status of the 
		transaction being written
	#############Change Log#############
	Modified by     Version     Change Date
	Wiktor Czykin   1.1         30/07/2015  //modified so that accounts updated based on nested method calls are unique (previously list uniqueness error)
	****************************************************************************************/
	public void UpdateSubscriptionDetails(List<MPP_Transaction_History__c> MPPTransactionHistories){

		Set<MPP_Transaction_History__c> digiOK = new Set<MPP_Transaction_History__c>();
		Set<MPP_Transaction_History__c> digiFail = new Set<MPP_Transaction_History__c>();
		Set<MPP_Transaction_History__c> premOK = new Set<MPP_Transaction_History__c>();
		Set<MPP_Transaction_History__c> premFail = new Set<MPP_Transaction_History__c>();
		
		for(MPP_Transaction_History__c txn : MPPTransactionHistories){

			if(txn.DD_Transaction_Type__c == 'AUDDIS')
				continue;
				
			// Digital subscribers don't have subscription records
			if(txn.Subscription__c == null){
				if(txn.Payment_status__c == 'failed')
					digiFail.add(txn);
				if(txn.Payment_status__c == 'success' || txn.Payment_status__c == 'pending' )
					digiOK.add(txn);
			} else {
				if(txn.Payment_status__c == 'failed')
					premFail.add(txn);
				if(txn.Payment_status__c == 'success')
					premOK.add(txn);
			}
		}
		
		Map<Id, Account> mapUpdateSubscribers = new Map<Id, Account>();
		List<Subscription__c> updateSubscriptionsNoLock = new List<Subscription__c>();
		List<Subscription__c> updateSubscriptionsWithLock = new List<Subscription__c>();
		Set<Id> subscriptionIdsToUpdate = new Set<Id>();
		
		if(!digiFail.isEmpty()){
			processDigitalFailures(digiFail, mapUpdateSubscribers);
		}
		
		if(!digiOK.isEmpty()){
			processDigitalSuccesses(digiOK, mapUpdateSubscribers);
		}
		
		if(!premFail.isEmpty()){
			processPremiumFailures(premFail, updateSubscriptionsNoLock);
		}
				
		if(!premOK.isEmpty()){
			processPremiumSuccesses(premOK, updateSubscriptionsNoLock, updateSubscriptionsWithLock);
		}

		// Actually do the updates
		update mapUpdateSubscribers.values();
		update updateSubscriptionsNoLock;
		
		SubscriptionTriggerHandler.getInstance().bDeferredCalculationSkip = true;
		update updateSubscriptionsWithLock;
		SubscriptionTriggerHandler.getInstance().bDeferredCalculationSkip = false;

	}
	
	/** Calculate the VAT due on each transaction
	 ** Added Change for PP-1317 
	*/
	public void CalculateVAT(List<MPP_Transaction_History__c> MPPTransactionHistories){
		VAT__c vat = VAT__c.getInstance('VAT');
		List<MPP_Transaction_History__c> premiumTxns = new List<MPP_Transaction_History__c>();
		List<MPP_Transaction_History__c> digitalTxns = new List<MPP_Transaction_History__c>();
		List<MPP_Transaction_History__c> failedTXns = new List<MPP_Transaction_History__c>();
		Set<Id> subscriptionIds = new Set<Id>();
		Set<Id> subscriberIds = new Set<Id>();
		// Change start for PP-1317
		// Find All Failed and Cancelled Tarnsaction
		for(MPP_Transaction_History__c txn : MPPTransactionHistories){
			if(txn.DD_Transaction_Type__c == 'AUDDIS'){
				continue;
			}

			if(txn.Payment_status__c == 'Failed' || txn.Payment_status__c == 'Cancelled')	{
				failedTXns.add(txn);
			} else {
				subscriberIds.add(txn.Subscriber__c);
				if(txn.Subscription__c != null){
					premiumTxns.add(txn);
					subscriptionIds.add(txn.Subscription__c);
				}else {
					digitalTxns.add(txn);
				}
		  	}
		}
		
		Map<Id, Subscription__c> subscriptions = new Map<Id, Subscription__c>([SELECT Id, WeeklyDigitalVAT__c, WeeklyPrintPrice__c, Weekly_Price__c, Digital_VAT_Rate__c FROM Subscription__c WHERE Id IN :subscriptionIds]);
		Map<Id, Account> subscribers = new Map<Id, Account>([SELECT Id, PersonMailingCountry FROM Account WHERE Id IN :subscriberIds]); 
		
		for(MPP_Transaction_History__c txn : failedTXns){
			txn.Total_Price__c=0;
			txn.Net_Amount__c = 0;
			txn.VAT_Amount__c = 0;
			
		}
		
		//End Change PP-1317
		
		for(MPP_Transaction_History__c txn : premiumTxns){
			if(Trigger.isBefore && Trigger.isInsert){
				String country = subscribers.get(txn.subscriber__c).PersonMailingCountry;
				String isoCode = (TMGUtil.isDataValid(country) ? country.toUpperCase() : null);
				Boolean hasCountryMap = Country_Codes__c.getAll().containsKey(isoCode);
				
				if(hasCountryMap){
					Country_Codes__c c = Country_Codes__c.getInstance(isoCode);
					txn.VAT_Country__c = c.Country_Name__c;
				}
			}
			txn.VAT_Type__c = 'UK Zero';
			txn.VAT_Rate__c = 0;
			txn.Net_Amount__c = txn.Total_Price__c - txn.VAT_Rate__c;
			txn.VAT_Amount__c = txn.Total_Price__c * txn.VAT_Rate__c;
		}
		
		for(MPP_Transaction_History__c txn : digitalTxns){
			/* For digital subscriptions the VAT is calculated based on the
				prevailing VAT rates at the time the transaction is taken
			*/
			// get country and vat rate
			if(!subscribers.containsKey(txn.Subscriber__c))
				continue;
			
			Decimal vatRate;
			String country = subscribers.get(txn.subscriber__c).PersonMailingCountry;
			String isoCode = (TMGUtil.isDataValid(country) ? country.toUpperCase() : null);
			Boolean hasCountryMap = Country_Codes__c.getAll().containsKey(isoCode);
			
			if(hasCountryMap){
				Country_Codes__c c = Country_Codes__c.getInstance(isoCode);
				if(Trigger.isBefore && Trigger.isInsert){
					txn.VAT_Country__c = c.Country_Name__c;
				}
				
				if(c.Name == 'GB'){
					vatRate = vat.UK_Standard_VAT_Rate__c;
					txn.VAT_Type__c = 'UK Standard';
				} else if(c.EU__c){
					vatRate = vat.EU_Standard_VAT_Rate__c;
					txn.VAT_Type__c = 'EU Standard';
				} else{
					vatRate = 0;
					txn.VAT_Type__c = 'Non EU Exempt';
				}
			}else{
				vatRate = 0;
				txn.VAT_Type__c = 'Non EU Exempt';
			}

			txn.VAT_Rate__c = vatRate;
			if( txn.Total_Price__c != null ){
				txn.Net_Amount__c = TMGUtil.decimalRound(txn.Total_Price__c / (1+(vatRate/100)), 2);
				txn.VAT_Amount__c = txn.Total_Price__c - txn.Net_Amount__c;
			}
		}
	}
	
	/** Process the failed transactions for digital accounts
	*/
	private void processDigitalFailures(Set<MPP_Transaction_History__c> transactions, Map<Id, Account> mapUpdateSubscribers){
		for(MPP_Transaction_History__c txn : transactions){
			if(!mapUpdateSubscribers.containsKey(txn.Subscriber__c)){
				mapUpdateSubscribers.put(txn.Subscriber__c, new Account( Id = txn.Subscriber__c, Subscriber_Digital_Status__c = 'Inactive'));
				System.debug('### Failed MPP Transaction: ' + txn.Subscriber__c);
			}
		}
	}

	/** Process the successful transactions for digital accounts
	*/
	private void processDigitalSuccesses(Set<MPP_Transaction_History__c> transactions, Map<Id, Account> mapUpdateSubscribers){
		for(MPP_Transaction_History__c txn : transactions){
			mapUpdateSubscribers.put(txn.Subscriber__c, new Account( Id = txn.Subscriber__c, Subscriber_Digital_Status__c = 'Active' ));
			System.debug('### Success MPP Transaction: ' + txn.Subscriber__c);
		}
	}
	
	/** Process the failed transactions for premium accounts
	*/
	private void processPremiumFailures(Set<MPP_Transaction_History__c> transactions, List<Subscription__c> updateSubscriptions){
		Set<Id> subs = new Set<id>();	
		for(MPP_Transaction_History__c txn : transactions){
			subs.add(txn.Subscription__c);
		}
		
		List<Voucher_Adjustment__c> vouchers = [SELECT Id, Subscription__c, End_Date__c FROM Voucher_Adjustment__c WHERE Subscription__c IN :subs ORDER BY End_Date__c];
		Map<Id, Date> endDates = new Map<Id, Date>();
		for(Voucher_Adjustment__c voucher : vouchers){
			if(endDates.keySet().contains(voucher.Subscription__c) && voucher.End_Date__c > endDates.get(voucher.Subscription__c)){
				endDates.remove(voucher.Subscription__c);
			}
			
			endDates.put(voucher.Subscription__c, voucher.End_Date__c);
		}

		for(MPP_Transaction_History__c txn : transactions){
			updateSubscriptions.add(new Subscription__c( Id = txn.Subscription__c, 
														 payment_details_received__c = true, 
														 Subscription_Status__c = 'Pending Cancellation',
														 Cancellation_Date__c = (endDates.keySet().contains(txn.Subscription__c) ? endDates.get(txn.Subscription__c) : txn.Subscription_Start_Date__c/*date.today()*/)));

		}
	}
	
	/** Process the successful transactions for premium accounts
	*/
	private void processPremiumSuccesses(Set<MPP_Transaction_History__c> transactions, List<Subscription__c> updateSubscriptionsNoLock, List<Subscription__c> updateSubscriptionsWithLock){

		Set<Id> subscriptionIdsToUpdate = new Set<Id>();
		// Successful transaction for premium subscriber
		for(MPP_Transaction_History__c txn : transactions){
			subscriptionIdsToUpdate.add(txn.Subscription__c);
		}
		
		//PP-1631
		// Subscriptions that are in Offered move to Pending
		List<Subscription__c> offeredSubs = [SELECT Id, Subscription_Status__c, payment_details_received__c,Is_One_Off_Payment__c FROM Subscription__c WHERE Id IN :subscriptionIdsToUpdate AND Subscription_Status__c = 'Offered'];
		for(Subscription__c sub : offeredSubs){
			
			System.debug('processPremiumSuccesses one of payment status is '+sub.Is_One_Off_Payment__c);
			if (sub.Is_One_Off_Payment__c != true){ 
				sub.Subscription_Status__c = 'Pending';
			}
			updateSubscriptionsNoLock.add(sub);
		}
				
		// Subscriptions that in pending cancellation, can go to Active, InRenewal (no Trigger) or InRenewal (with Trigger)
		List<Subscription__c> pendingCancellationSubs = [SELECT Id, Subscription_Status__c, payment_details_received__c, End_Date__c, IF_11_Week_Renewal_Update_Date_Hidden__c, IF_DD_D03_Extraction_Date__c, Is_One_Off_Payment__c FROM Subscription__c WHERE Id IN :subscriptionIdsToUpdate AND Subscription_Status__c = 'Pending Cancellation'];
		List<Subscription__c> newSubs = [SELECT Id, Previous_Subscription__c FROM Subscription__c WHERE Previous_Subscription__c IN :subscriptionIdsToUpdate];

		// Create a set of subs that have had new subs created by renewal
		Set<Id> renewed = new Set<Id>();
		for(Subscription__c sub : newSubs){
			renewed.add(sub.Previous_Subscription__c);
		}

		for(Subscription__c sub : pendingCancellationSubs){

			//RW310712 to resolve pending cancellation issue
			System.debug('processPremiumSuccesses one of payment status is '+sub.Is_One_Off_Payment__c);
			if (sub.Is_One_Off_Payment__c == true){ 
				sub.Subscription_Status__c = 'Pending Cancellation';
			}
			
			if(sub.Is_One_Off_Payment__c != true){
			Date renewalDate = (sub.IF_DD_D03_Extraction_Date__c != null) ? sub.IF_DD_D03_Extraction_Date__c :  sub.IF_11_Week_Renewal_Update_Date_Hidden__c;
			if(sub.Is_One_Off_Payment__c != true && Date.today() < renewalDate){
				// The subscription hasn't reached renewal so set back to active
				sub.Subscription_Status__c = 'Active';
				updateSubscriptionsNoLock.add(sub);
			} else{
				// The In Renewal date has past, so set the state to In Renewal
				sub.Subscription_Status__c = 'In Renewal';
				
				// Has a new sub already been created for this renewal?
				// If it has disable the trigger with the 'lock'
				// Otherwise we want the trigger to fire
				if(renewed.contains(sub.Id)){
					updateSubscriptionsNoLock.add(sub);
				} else{
					updateSubscriptionsWithLock.add(sub);					
				}
			}
		}
	}
}	


}