src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Guid__c</fullName>
        <description>Unique identifier for this subscriber with the SAM system.</description>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subscriber_Number_static__c</fullName>
        <description>This is the static (field value is not calculated using formula) version of the Subscriber Number field</description>
        <externalId>true</externalId>
        <label>Subscriber Number (static)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMG_Model_Score_Img__c</fullName>
        <formula>CASE(TMG_Model_Score__c , 
     &apos;0&apos;, &apos;/resource/0/LowScoreImage&apos;,
     &apos;1&apos;, &apos;/resource/0/MediumScoreImage&apos;,
     &apos;2&apos;, &apos;/resource/0/HighScoreImage&apos;,
     &apos;3&apos;, &apos;/resource/0/HighestScoreImage&apos;,
     &apos;/resource/0/LowScoreImage&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TMG Model Score Img</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMG_Model_Score__c</fullName>
        <label>TMG Model Score</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutoSubscriberSearchComponentController.cls
/*
 * File Name   : AutoSubscriberSearchComponentController
 * Description : Controller for Visualforce Page AutoSubscriberSearchComponent 
 *
 * Modification Log
 * ======================================================== 
 * Ver Date       Author         Modification
 * --- ---------- -------------- --------------------------
 * 1.0 30/01/2014 IVAN ALMEIDA	 Initial Version 
 */ 
global with sharing class AutoSubscriberSearchComponentController {
	
	/**
	 * Remote Method that's called from javascript remoting and searches subscribers byt their TSNumbers
	 * given a search term.
	 * 
	 * @param searchTopic Search term for the SOQL query.
	 */
	@RemoteAction
	global static List<Account> doAutoCompleteSearch(String searchTopic){
		List<Account> resultAccounts = new List<Account>();
		searchTopic = searchTopic.trim();
		if(searchTopic != null && searchTopic.length() >= 4) {
			// Trim the searchtopic
			string tempWhere = '%' + searchTopic.replace(' ', '%') + '%';
			string tempFind = '*' + searchTopic.replace(' ', '*') + '*';
			//Do the search.
			resultAccounts = [FIND :tempFind
								IN all Fields
								RETURNING account 
									(Id, Name, Subscriber_Number_static__c, PersonMailingPostalCode, RecordType.Name, PersonEmail, PersonHomePhone, TMG_Model_Score_Img__c 
								where 
									(RecordType.Name = :Constants.RECTYPE_INDIVSUB
									or RecordType.Name = :Constants.RECTYPE_DIGISUB)
									and
									(Subscriber_Number_static__c like :tempWhere 
									or name like :tempWhere 
									or PersonMailingPostalCode like :tempWhere
									or GUID__c like :tempWhere
									or PersonEmail like :tempWhere)
								order by TMG_Model_Score__c desc) 
								limit 20][0];
		}
		if (resultAccounts == null || resultAccounts.isEmpty())
			return null;
		return resultAccounts;
	}
}