src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Restricted_Offer_Usage__c.object
<CustomObject>
    <description>Stores information about Restricted Offers used by the subscriber</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Restricted_Offer_Usage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ignore_Lock_in_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignore Lock-in Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock_in_Expiry_Date__c</fullName>
        <formula>DATE(
	YEAR(Subscription__r.Zuora__SubscriptionEndDate__c) + FLOOR( ( MONTH (Subscription__r.Zuora__SubscriptionEndDate__c) + VALUE(Product__r.RestrictedOfferLockinPeriod__c) - 1 ) / 12 ),
	MOD( MONTH (Subscription__r.Zuora__SubscriptionEndDate__c) + VALUE(Product__r.RestrictedOfferLockinPeriod__c) - 1, 12 ) + 1,
	IF( DAY(Subscription__r.Zuora__SubscriptionEndDate__c) &gt; CASE( MOD( MONTH(Subscription__r.Zuora__SubscriptionEndDate__c) + VALUE(Product__r.RestrictedOfferLockinPeriod__c) - 1, 12 ) + 1,
							2, 28,
							4, 30,
							6, 30,
							9, 30,
							11, 30,
							31 ),
		CASE( MOD( MONTH(Subscription__r.Zuora__SubscriptionEndDate__c) + VALUE(Product__r.RestrictedOfferLockinPeriod__c) - 1, 12 ) + 1,
							2, 28,
							4, 30,
							6, 30,
							9, 30,
							11, 30,
							31 ), 
		DAY(Subscription__r.Zuora__SubscriptionEndDate__c)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lock-in Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipName>Restricted_Offer_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Restricted Offer Usage</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Restricted Offer Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Offer Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <pluralLabel>Quotes</pluralLabel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <fields>
        <fullName>RestrictedOfferLockinPeriod__c</fullName>
        <inlineHelpText>Period of time (in months) for which a Subscriber should be locked if this Product was sold with a Restricted Offer.</inlineHelpText>
        <label>Restricted Offer Lock-in Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <pluralLabel>Products</pluralLabel>    
</CustomObject>

src/classes/QuoteRestrictedOfferWarningExtension.cls
/**
* @author Pawel Chrzanowski
* @date 13/01/2017
* @description  Quote Restricted Offer Warning Extension
#############Change Log#############
Modified by     Change Date
Wiktor Czykin   31/05/2017  //modified constructor
**/
public class QuoteRestrictedOfferWarningExtension {

    public String warningVisibility {get;set;}
    public String lockPeriod {get;set;}
    private Id quoteId;

    /***************************************************************************************
    Developer   Pawel Chrzanowski
    Date        13/01/2017
    Function    Constructor
    ******************* Change Log *******************
    Modified by     Change Date
    Wiktor Czykin   31/05/2017  //replace visibility css with display  
    ****************************************************************************************/
    public QuoteRestrictedOfferWarningExtension(ApexPages.StandardController stdController){
        warningVisibility = 'none';
        quoteId = stdController.getId();
        
        //get related Account
        List<zqu__Quote__c> lstQuotes = [SELECT zqu__Account__c FROM zqu__Quote__c WHERE zqu__Status__c = :Constants.QUOTE_STATUS_NEW_VALUE AND Id = :quoteId];
        if(lstQuotes.isEmpty() || lstQuotes[0].zqu__Account__c == null) return;
        
        //get related Quote Rate Plan
        String discountRatePlanName='%'+Constants.DISCOUNT_RATE_PLAN_NAME.tolowerCase()+'%';
        List<zqu__QuoteRatePlan__c> lstQRP = [SELECT zqu__QuoteProductName__c FROM zqu__QuoteRatePlan__c WHERE zqu__Quote__c = :quoteId AND (NOT zqu__ProductRatePlan__r.Name LIKE :discountRatePlanName)];
        if(lstQRP.isEmpty() || lstQRP[0].zqu__QuoteProductName__c == null) return;
        
        //get related Product
        List<zqu__ZProduct__c> lstProduct = [SELECT Id FROM zqu__ZProduct__c WHERE Name = :lstQRP[0].zqu__QuoteProductName__c];
        if(lstProduct.isEmpty()) return;
        
        //get related ROU
        List<Restricted_Offer_Usage__c> lstROU = [SELECT Lock_in_Expiry_Date__c, Ignore_Lock_in_Period__c, Product__r.RestrictedOfferLockinPeriod__c FROM Restricted_Offer_Usage__c WHERE Account__c = :lstQuotes[0].zqu__Account__c AND Product__c = :lstProduct[0].Id ORDER BY CreatedDate DESC];
        if(lstROU.isEmpty() || lstROU[0].Lock_in_Expiry_Date__c == null || (lstROU[0].Ignore_Lock_in_Period__c != null && lstROU[0].Ignore_Lock_in_Period__c)){
            return;
        }else if(Date.today() <= lstROU[0].Lock_in_Expiry_Date__c){
            warningVisibility = 'block';
            lockPeriod = lstROU[0].Product__r.RestrictedOfferLockinPeriod__c != null ? lstROU[0].Product__r.RestrictedOfferLockinPeriod__c : '0';
        }
    }
}