src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duplicate_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This account is marked as duplicate of the specified account</description>
        <inlineHelpText>This account is marked as duplicate of the specified account</inlineHelpText>
        <label>Duplicate Of</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Duplicate Accounts</relationshipLabel>
        <relationshipName>DuplicateAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The custom setting object to hold all TMG Application static settings</description>
    <fields>
        <fullName>Core_Api_App_Id_Value__c</fullName>
        <label>Core Api App Id Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Core_Api_App_Id__c</fullName>
        <label>Core Api App Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Core_Api_App_Key_Value__c</fullName>
        <label>Core Api App Key Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Core_Api_App_Key__c</fullName>
        <label>Core Api App Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Holiday_Voucher_Cheque_Refund_Report_Id__c</fullName>
        <description>Voucher Activity Holiday Return Cheque Refunds Report Id. Requires 15 characters report id.</description>
        <inlineHelpText>Voucher Activity Holiday Return Cheque Refunds Report Id. Requires 15 characters report id.</inlineHelpText>
        <label>Holiday Voucher Cheque Refund Report Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPP_Refund_Email_Template_Name__c</fullName>
        <description>API name of email template used for MPP refund notification in holiday return voucher activities functionality.</description>
        <inlineHelpText>API name of email template used for MPP refund notification in holiday return voucher activities functionality.</inlineHelpText>
        <label>MPP Refund Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visualforce_Base_Url__c</fullName>
        <description>The url address used to redirect to the pages that are using Zuora visual force components. This setting can be inserted/updated by calling DefaultSettings.ORG_LEVEL_CONFIGURATION</description>
        <inlineHelpText>The url address used to redirect to the pages that are using Zuora visual force components. This setting can be inserted/updated by calling DefaultSettings.ORG_LEVEL_CONFIGURATION</inlineHelpText>
        <label>Visualforce Base Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Voucher_Refund_Threshold_Amount__c</fullName>
        <description>Custom setting to hold Voucher Refund Thresholds. Used for refund of holiday voucher on Voucher Adjustment record</description>
        <inlineHelpText>Custom setting to hold Voucher Refund Thresholds. Used for refund of holiday voucher on Voucher Adjustment record</inlineHelpText>
        <label>Voucher Refund Threshold Amount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Application Configurations</label>
</CustomObject>

src/objects/Notification_Banner_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The settings that are used in NotificationBanner component</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Activate/Deactivate notification banner</description>
        <inlineHelpText>Activate/Deactivate notification banner</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <description>API name of the field(s) that values are required to be displayed in notification message. Multiple fields must be separated by comma.</description>
        <inlineHelpText>API name of the field(s) that values are required to be displayed in notification message. Multiple fields must be separated by comma.</inlineHelpText>
        <label>Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message that need to be displayed on the banner. This message can contain HTML and String formatting to display values from the fields specified in Field .</description>
        <inlineHelpText>The message that need to be displayed on the banner. This message can contain HTML and String formatting to display values from the fields specified in Field .</inlineHelpText>
        <label>Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>The API name of the object for which the notification is displayed</description>
        <inlineHelpText>The API name of the object for which the notification is displayed</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Use one of the key words ERROR, WARNING, INFO, SUCCESS</description>
        <inlineHelpText>Use one of the key words ERROR, WARNING, INFO, SUCCESS</inlineHelpText>
        <label>Severity</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Notification Banner Settings</label>
</CustomObject>

src/classes/DefaultSettings.cls
/************************************************************************************
Class Name   : DefaultSettings
Author       : Mantas Grigaliunas
Created Date : 16/10/2016
Function     : The class to hold methods that are used to insert the post deployment configurations to org
Change Log:
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
* Developer             Date        Description
* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
* Mantas Grigaliunas    25/10/2016  Added defineNotificationBannerSettings() method
* Vishant Shah          02/11/2016  Added Voucher_Refund_Threshold_Amount__c
* Pawel Chrzanowski     28/11/2016  Added Core Api Custom Settings
* Mantas Grigaliunas    08/12/2016  Added getHolidayVoucherChequeRefundRepiortId()
* Mantas Grigaliunas    10/02/2017  Added MPP_Refund_Email_Template_Name__c field
*************************************************************************************/
public class DefaultSettings {

    private static Configuration__c config = Configuration__c.getInstance();

    public static Configuration__c APPLICATION_CONFIGURATIONS {
        get {
            Configuration__c c = new Configuration__c();
            c.Visualforce_Base_Url__c = getVisualforceBaseUrl();
            c.Voucher_Refund_Threshold_Amount__c = Constants.VOUCHER_REFUND_THRESHOLD_CUSTOM_SETTING_AMOUNT;
            c.Holiday_Voucher_Cheque_Refund_Report_Id__c = getHolidayVoucherChequeRefundReportId(Constants.HOLIDAY_VOUCHER_REFUND_CHEQUE_REPORT_NAME);
            c.MPP_Refund_Email_Template_Name__c = Constants.MPP_REFUND_EMAIL_TEMPLATE_NAME;
			return c;
		}
	}

    public static List<Notification_Banner_Setting__c> NOTIFICATION_BANNER_SETTINGS {
        get {
            return defineNotificationBannerSettings(); 
        }
    }

    public static String CORE_API_APP_ID {
        get {
			return (config.Core_Api_App_Id__c == null && Test.isRunningTest() ? 'app_id' : config.Core_Api_App_Id__c);
        }
    }

    public static String CORE_API_APP_ID_VALUE {
        get {
            return (config.Core_Api_App_Id_Value__c == null && Test.isRunningTest() ? '00000001' : config.Core_Api_App_Id_Value__c);
        }
    }

    public static String CORE_API_APP_KEY {
        get {
            return (config.Core_Api_App_Key__c == null && Test.isRunningTest() ? 'app_key' : config.Core_Api_App_Key__c);
        }
    }

    public static String CORE_API_APP_KEY_VALUE {
        get {
            return (config.Core_Api_App_Key_Value__c == null && Test.isRunningTest() ? '00000000000000000000000000000001' : config.Core_Api_App_Key_Value__c);
        }
    }

    //number of setting records created
    @TestVisible private static final Integer NOTIFICATION_BANNER_SETTINGS_SIZE = 1;

    /************************************************************************************
    Method Name  : getVisualforceBaseUrl
    Created by   : Mantas Grigaliunas
    Date         : 16/10/2016
    Function     : Builds the base visualforce url which is used to access pages that are packaged or using the packaged components
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer         Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
    private static String getVisualforceBaseUrl(){
        String instance = [ SELECT InstanceName FROM Organization LIMIT 1 ].InstanceName;
        return String.format(Label.Configuration_Visualforce_Base_Url, new List<String>{instance.toLowerCase()});
    }

    /************************************************************************************
    Method Name  : getHolidayVoucherChequeRefundRepiortId
    Created by   : Mantas Grigaliunas
    Change Date  : 08/12/2016
    Function     : Get id of the report
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer         Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
    public static String getHolidayVoucherChequeRefundReportId(String reportName){
        List<Report> reports = new List<Report>([ SELECT Id FROM Report WHERE DeveloperName = :reportName LIMIT 1]);
        if(reports.size() > 0){
            String reportId = reports[0].Id;
            return reportId.substring(0, 15);
        } else {
            return null;
        }
    }

    /************************************************************************************
    Method Name  : defineNotificationBannerSettings
    Created by   : Mantas Grigaliunas
    Change Date  : 24/10/2016
    Function     : Creates the list of Notification Banner Settings custom settings
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer         Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
    private static List<Notification_Banner_Setting__c> defineNotificationBannerSettings(){

        List<Notification_Banner_Setting__c> lstBannerSettings = new List<Notification_Banner_Setting__c>();
        Notification_Banner_Setting__c  accountDuplicationNotification = new Notification_Banner_Setting__c(
            Name = 'Account Duplication Notification',
            Active__c = true,
            Fields__c = 'Duplicate_Of__c,Duplicate_Of__r.Name',
            Message__c = 'This account is duplicate of <a href="/{0}" target="_blank">{1}</a>',
            Object__c = 'Account',
            Severity__c = 'WARNING'
        );
        lstBannerSettings.add(accountDuplicationNotification);
        return lstBannerSettings;
    }
}