src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DD_Cancellation_Call_Date_Time__c</fullName>
        <label>DD Cancellation Call Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DD_Winback_Call_Date_Time__c</fullName>
        <label>DD Winback Call Date &amp; Time</label>
        <type>DateTime</type>
    </fields>

    <fields>
        <fullName>OC_Call_Stage__c</fullName>
        <description>Outbound call stage name</description>
        <inlineHelpText>Outbound call stage name</inlineHelpText>
        <label>Call Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>T2</fullName>
                </value>
                <value>
                    <fullName>T2 Catch Up</fullName>
                </value>
                <value>
                    <fullName>TL1</fullName>
                </value>
                <value>
                    <fullName>TL2</fullName>
                </value>
                <value>
                    <fullName>BR1</fullName>
                </value>
                <value>
                    <fullName>CCEX1</fullName>
                </value>
                <value>
                    <fullName>DD Winback</fullName>
                </value>
                <value>
                    <fullName>DDCX</fullName>
                </value>
                <value>
                    <fullName>T2 28Days</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Outcome__c</fullName>
        <description>The outcome of the outbound call</description>
        <inlineHelpText>Please specify the outcome of the outbound call</inlineHelpText>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Cheque Sales</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>NATC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Scheduled_Callback__c</fullName>
        <description>Date/Time field for new outbound call task filter logic. This field is auto-populated from controller.</description>
        <inlineHelpText>The field to hold the date and time when the callback need to be done. Enter the date and time when the call need to be rescheduled only if you want override standard rescheduling functionality.</inlineHelpText>
        <label>Scheduled Callback</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_1_Call_Date_Time__c</fullName>
        <description>The time call was made at the first stage</description>
        <inlineHelpText>The time call was made at the first stage</inlineHelpText>
        <label>T2 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_1_No_Sale_Reason__c</fullName>
        <description>The no sale reason of the first call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The no sale reason of the first call stage. This field is auto-populated from the selected outcome on the first call stage.</inlineHelpText>
        <label>T2 No Sale Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_1_Outcome__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>The outcome of the first call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The outcome of the first call stage. This field is auto-populated from the selected outcome on the first call stage.</inlineHelpText>
        <label>T2 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_2_Call_Date_Time__c</fullName>
        <description>The time call was made at the second stage</description>
        <inlineHelpText>The time call was made at the second stage</inlineHelpText>
        <label>T2 Catch Up Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_2_No_Sale_Reason__c</fullName>
        <description>The no sale reason of the second call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The no sale reason of the second call stage. This field is auto-populated from the selected outcome on the first call stage.</inlineHelpText>
        <label>T2 Catch Up No Sale Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_2_Outcome__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>The outcome of the second call stage. This field is auto-populated from the selected outcome on the second call stage.</description>
        <inlineHelpText>The outcome of the second call stage. This field is auto-populated from the selected outcome on the second call stage.</inlineHelpText>
        <label>T2 Catch Up Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_3_Call_Date_Time__c</fullName>
        <description>The time call was made at the third stage</description>
        <inlineHelpText>The time call was made at the third stage</inlineHelpText>
        <label>TL1 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_3_No_Sale_Reason__c</fullName>
        <description>No sale reason of the third call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>No sale reason of the third call stage. This field is auto-populated from the selected outcome on the first call stage.</inlineHelpText>
        <label>TL1 No Sale Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_3_Outcome__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>The outcome of the third call stage. This field is auto-populated from the selected outcome on the third call stage.</description>
        <inlineHelpText>The outcome of the third call stage. This field is auto-populated from the selected outcome on the third call stage.</inlineHelpText>
        <label>TL1 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_4_Call_Date_Time__c</fullName>
        <description>The time call was made at the fourth stage</description>
        <inlineHelpText>The time call was made at the fourth stage</inlineHelpText>
        <label>TL2 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_4_No_Sale_Reason__c</fullName>
        <description>No sale reason of the fourth call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>No sale reason of the fourth call stage. This field is auto-populated from the selected outcome on the first call stage.</inlineHelpText>
        <label>TL2 No Sale Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_4_Outcome__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>The outcome of the fourth call stage. This field is auto-populated from the selected outcome on the fourth call stage.</description>
        <inlineHelpText>The outcome of the fourth call stage. This field is auto-populated from the selected outcome on the fourth call stage.</inlineHelpText>
        <label>TL2 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_5_Call_Date_Time__c</fullName>
        <description>Date and time call was made at the fith stage</description>
        <inlineHelpText>Date and time call was made for BR1</inlineHelpText>
        <label>BR1 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_5_Outcome__c</fullName>
        <description>The outcome of the fifth call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The outcome of the BR1 call.</inlineHelpText>
        <label>BR1 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Stage_6_Call_Date_Time__c</fullName>
        <description>Date and time call was made at the sixth  stage</description>
        <inlineHelpText>CCEX1 call date and time</inlineHelpText>
        <label>CCEX1 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_6_Outcome__c</fullName>
        <description>The outcome of the sixth call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The outcome of CCEX1 call</inlineHelpText>
        <label>CCEX1 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    




</CustomObject>

src/classes/OutboundCaseRequeueBatch.cls
/**
* @author Michal Szewczyk
* @date 07/09/2016
* @description  Batch class for processing Cases to change Scheduled Callback date
*#############Change Log#############
* Modified by        Change Date
* Michal Szewczyk    6/10/2016   - changed execute() 
* Vishant Shah       09/06/2017  - added DDWinback and DDCX fields to query
**/
global class OutboundCaseRequeueBatch implements Database.Batchable<sObject> {
	
	private final List<String> queryStatusParams;
	private final List<String> queryStageParams;
	private final String caseRecTypeId;
	
	/***************************************************************************************
    Developer - Michal Szewczyk
    Date - 05/09/2016
    Version - 1.0
    Function - Batch class constructor with params
    #############Change Log#############
    Modified by     Change Date
    ****************************************************************************************/
	global OutboundCaseRequeueBatch(List<String> statuses,List<String> stages,String buttonSource) {
		queryStatusParams = statuses;
		queryStageParams  = stages; 	

		if(queryStatusParams.isEmpty()) {
			throw new TMGUtil.GenericException('Outcome status was not selected. Please select at least one');
		}

		if(queryStageParams.isEmpty()) {
			throw new TMGUtil.GenericException('Case stage was not selected. Please select at least one');
		}

		caseRecTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType,buttonSource, Case.class.getName());
		
		if (caseRecTypeId==null || caseRecTypeId ==''){
			throw new TMGUtil.GenericException('buttonSource is not valid');
		}
	}
	
	/***************************************************************************************
    Developer - Michal Szewczyk
    Date - 05/09/2016
    Version - 1.0
    Function - start method of batch - scope definition
    #############Change Log#############
    Modified by     Change Date
    ****************************************************************************************/
	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([SELECT Id,OC_Outcome__c,OC_Scheduled_Callback__c,
												OC_Stage_1_Call_Date_Time__c,OC_Stage_2_Call_Date_Time__c,
												OC_Stage_2_No_Sale_Reason__c,OC_Stage_2_Outcome__c,
												OC_Stage_1_No_Sale_Reason__c,OC_Stage_1_Outcome__c,
												OC_Stage_3_Call_Date_Time__c,OC_Stage_3_No_Sale_Reason__c,
												OC_Stage_3_Outcome__c,OC_Stage_4_Call_Date_Time__c,
												OC_Stage_4_No_Sale_Reason__c,OC_Stage_4_Outcome__c,
												OC_Stage_6_Call_Date_Time__c,OC_Stage_6_Outcome__c,
												OC_Stage_5_Call_Date_Time__c,OC_Stage_5_Outcome__c,
												OC_Call_Stage__c,RecordTypeId,DD_Winback_Call_Date_Time__c,
                                                DD_Cancellation_Call_Date_Time__c
										 FROM Case 
										 WHERE RecordTypeId =:caseRecTypeId 
										 AND OC_Outcome__c IN :queryStatusParams
										 AND OC_Call_Stage__c IN :queryStageParams]);
	}
    
    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 05/09/2016
    Version - 1.0
    Function - batch execution logic
    #############Change Log#############
    Modified by     Change Date
    Michal Szewczyk 1.1         6/10/2016 - clear OC_Scheduled_Callback__c field
    ****************************************************************************************/
   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<Case> casesForUpdate = new List<Case>();

		OutboundCallingUtils.defineOutboundCallSettingParameters();
        for(Case thisCase : (List<Case>) scope){
            List<OutboundCallingBean.CallStageMapping> thisParamList = OutboundCallingUtils.getCallStageParametersByRecordTypeId(thisCase.RecordTypeId);
            for(OutboundCallingBean.CallStageMapping thisParam : thisParamList){

                if(thisParam.stagename.equals(thisCase.OC_Call_Stage__c) && (Datetime) thisCase.get(thisParam.calldatetime) > Datetime.now()) {
                    thisCase.put(thisParam.calldatetime, Datetime.now());
                    thisCase.OC_Scheduled_Callback__c = null;
                    casesForUpdate.add(thisCase);
                }
            }
        }

	    try{
	          Database.update(casesForUpdate,false);
    	} catch (Exception e){
    		
    	}
	}
	
	/***************************************************************************************
    Developer - Michal Szewczyk
    Date - 05/09/2016
    Version - 1.0
    Function - finish method of the batch
    #############Change Log#############
    Modified by     Change Date
    ****************************************************************************************/
	global void finish(Database.BatchableContext BC) {
		
        String mailBody = Label.OC_Batch_Requeue_Body_Msg;
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setSubject(Label.OC_Batch_Requeue_Subject);
        email.setTargetObjectId(System.UserInfo.getUserId());
        email.setHTMLBody(mailBody);
        email.setSaveAsActivity(false);
        if(!Test.isRunningTest()){
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
        }
	}
	
}