src/objects/Case.object
<CustomObject>

    <fields>
        <fullName>Digital_Details_2__c</fullName>
        <label>Case Detail 3</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Digital_Details__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Subs</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Acq Offer</fullName>
                </value>
                <value>
                    <fullName>Acquisition</fullName>
                </value>
                <value>
                    <fullName>Acquisition Offer</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Against</fullName>
                </value>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Already Receives Internal Offers</fullName>
                </value>
                <value>
                    <fullName>Answers &amp; Winners</fullName>
                </value>
                <value>
                    <fullName>App Install</fullName>
                </value>
                <value>
                    <fullName>App performance</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Availablity</fullName>
                </value>
                <value>
                    <fullName>Broken links</fullName>
                </value>
                <value>
                    <fullName>Browser</fullName>
                </value>
                <value>
                    <fullName>Browser issues</fullName>
                </value>
                <value>
                    <fullName>Buy Edition</fullName>
                </value>
                <value>
                    <fullName>Cannot get through</fullName>
                </value>
                <value>
                    <fullName>Cartoons</fullName>
                </value>
                <value>
                    <fullName>Callback</fullName>
                </value>
                <value>
                    <fullName>Columnists</fullName>
                </value>
                <value>
                    <fullName>Comments</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Competitor Offer</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Contact Details</fullName>
                </value>
                <value>
                    <fullName>Content</fullName>
                </value>
                <value>
                    <fullName>Content Quality</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Digital_Details_3__c</fullName>
        <label>Case Detail 4</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Digital_Details_2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Access Issues</fullName>
                </value>
                <value>
                    <fullName>Account Locked</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Adverts</fullName>
                </value>
                <value>
                    <fullName>Against</fullName>
                </value>
                <value>
                    <fullName>App Performance</fullName>
                </value>
                <value>
                    <fullName>Appearance</fullName>
                </value>
                <value>
                    <fullName>Article Updates</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Availablity</fullName>
                </value>
                <value>
                    <fullName>Black Hands</fullName>
                </value>
                <value>
                    <fullName>Black Pages</fullName>
                </value>
                <value>
                    <fullName>Blank Pages</fullName>
                </value>
                <value>
                    <fullName>Blurred</fullName>
                </value>
                <value>
                    <fullName>Broken Links</fullName>
                </value>
                <value>
                    <fullName>Cannot Afford</fullName>
                </value>
                <value>
                    <fullName>Cartoons</fullName>
                </value>
                <value>
                    <fullName>Colour</fullName>
                </value>
                <value>
                    <fullName>Commenting</fullName>
                </value>
                <value>
                    <fullName>Content</fullName>
                </value>
                <value>
                    <fullName>Content Quality</fullName>
                </value>
                <value>
                    <fullName>Content Quantity</fullName>
                </value>
                <value>
                    <fullName>Content Updates</fullName>
                </value>
                <value>
                    <fullName>Creased</fullName>
                </value>
                <value>
                    <fullName>Download</fullName>
                </value>
                <value>
                    <fullName>Editorial</fullName>
                </value>
                <value>
                    <fullName>Editorial Mistakes</fullName>
                </value>
                <value>
                    <fullName>Failed Download</fullName>
                </value>
                <value>
                    <fullName>Faint Print</fullName>
                </value>
                <value>
                    <fullName>Folding Issues</fullName>
                </value>
                <value>
                    <fullName>Leaderboard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Digital_Details__c</fullName>
        <label>Case Detail 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_Of_Issue__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Accessibility</fullName>
                </value>
                <value>
                    <fullName>Account Closed</fullName>
                </value>
                <value>
                    <fullName>Account transferred to new Bank</fullName>
                </value>
                <value>
                    <fullName>Account/instruction transferred to Different Branch</fullName>
                </value>
                <value>
                    <fullName>Advance Notice - Disputed</fullName>
                </value>
                <value>
                    <fullName>Advance Notice Disputed</fullName>
                </value>
                <value>
                    <fullName>Against</fullName>
                </value>
                <value>
                    <fullName>Already Set Up</fullName>
                </value>
                <value>
                    <fullName>Amazon Subs Info</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Amount Differs</fullName>
                </value>
                <value>
                    <fullName>Amount Not Yet Due</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>App Features</fullName>
                </value>
                <value>
                    <fullName>App performance</fullName>
                </value>
                <value>
                    <fullName>Apple News</fullName>
                </value>
                <value>
                    <fullName>Apple Subs Info</fullName>
                </value>
                <value>
                    <fullName>Article Copy</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Availablity</fullName>
                </value>
                <value>
                    <fullName>Bank will not accept DD on Account</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Blackberry &gt; Troubleshooting &gt; App Features</fullName>
                </value>
                <value>
                    <fullName>Blackberry &gt; Troubleshooting &gt; Speed &amp; Performance</fullName>
                </value>
                <value>
                    <fullName>Booking Amendment</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Branded good</fullName>
                </value>
                <value>
                    <fullName>Broken Link</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    
    <fields>
        <fullName>Type_Of_Issue__c</fullName>
        <label>Case Detail 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition</fullName>
                </value>
                <value>
                    <fullName>Amend Customer Details</fullName>
                </value>
                <value>
                    <fullName>Amendment to bank details</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Announcements</fullName>
                </value>
                <value>
                    <fullName>Apple News</fullName>
                </value>
                <value>
                    <fullName>Apple News App</fullName>
                </value>
                <value>
                    <fullName>Article Queries</fullName>
                </value>
                <value>
                    <fullName>Back Copy Request</fullName>
                </value>
                <value>
                    <fullName>Blackberry &gt; General information</fullName>
                </value>
                <value>
                    <fullName>Blackberry &gt; Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>Bookshop</fullName>
                </value>
                <value>
                    <fullName>Box Office</fullName>
                </value>
                <value>
                    <fullName>BR1</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>CC Payment Query</fullName>
                </value>
                <value>
                    <fullName>CCEX1</fullName>
                </value>
                <value>
                    <fullName>Change of voucher type</fullName>
                </value>
                <value>
                    <fullName>City Share</fullName>
                </value>
                <value>
                    <fullName>Clearing App</fullName>
                </value>
                <value>
                    <fullName>Code 0</fullName>
                </value>
                <value>
                    <fullName>Code 1</fullName>
                </value>
                <value>
                    <fullName>Code 2</fullName>
                </value>
                <value>
                    <fullName>Code 3</fullName>
                </value>
                <value>
                    <fullName>Code 4</fullName>
                </value>
                <value>
                    <fullName>Code 5</fullName>
                </value>
                <value>
                    <fullName>Code 6</fullName>
                </value>
                <value>
                    <fullName>Code 7</fullName>
                </value>
                <value>
                    <fullName>Code 8</fullName>
                </value>
                <value>
                    <fullName>Code 9</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>In-paper</fullName>
                </value>
                <value>
                    <fullName>Issue</fullName>
                </value>
                <value>
                    <fullName>Reader Relations</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>




</CustomObject>

src/objects/Custom_Validation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Custom Validation</label>
</CustomObject>

src/classes/CustomValidatorTest.cls
@isTest
private class CustomValidatorTest
{

	static final String RECORD_TYPE_NAME = 'Reader Relations';

	@testSetup
	static void createTestData(){
		TestDataUtility tdu = new TestDataUtility(10);
		tdu.createCustomValidationRules();

		List<Custom_Validation__c> customvalidations = [SELECT Id FROM Custom_Validation__c];
		System.assertNotEquals(0, customvalidations.size());
	}

	@isTest
	static void caseCreationSuccess(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Puzzles & Games';
		c.Type_Of_Issue__c = 'Website';
		c.Digital_Details__c = 'Issue';
		c.Digital_Details_2__c = 'Performance';
		c.Digital_Details_3__c = 'No Loading';

		Test.startTest();
		Insert c;
		Test.stopTest();
	}

	@isTest
	static void caseCreationFailDetails3(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Puzzles & Games';
		c.Type_Of_Issue__c = 'Website';
		c.Digital_Details__c = 'Issue';
		c.Digital_Details_2__c = 'Performance';
		c.Digital_Details_3__c = 'Leaderboard';

		Test.startTest();
		try{
			Insert c;
		} catch (Exception e){
			System.assertEquals(true, e.getMessage().contains(' Allowed values for Case Detail 4 are : {No loading}'));
		}
		Test.stopTest();
	}

	@isTest
	static void caseCreationFailDetails2(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Puzzles & Games';
		c.Type_Of_Issue__c = 'Website';
		c.Digital_Details__c = 'Issue';
		c.Digital_Details_2__c = 'Printing';

		Test.startTest();
		try{
			Insert c;
		} catch (Exception e){
			System.assertEquals(true, e.getMessage().contains('Allowed values for Case Detail 3 are : {Performance}'));
		}
		Test.stopTest();
	}

	@isTest
	static void caseCreationFailDetails1(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Puzzles & Games';
		c.Type_Of_Issue__c = 'Website';
		c.Digital_Details__c = 'Feedback';

		Test.startTest();
		try{
			Insert c;
		} catch (Exception e){
			System.assertEquals(true, e.getMessage().contains('Allowed values for Case Detail 2 are : {Issue}'));
		}
		Test.stopTest();
	}

	@isTest
	static void caseCreationFailDetails(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Puzzles & Games';
		c.Type_Of_Issue__c = 'In-paper';

		Test.startTest();
		try{
			Insert c;
		} catch (Exception e){
			System.assertEquals(true, e.getMessage().contains('Allowed values for Case Detail 1 are : {Website}'));
		}
		Test.stopTest();
	}

	@isTest
	static void caseCreationCaseReason(){
		Id caseRecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, RECORD_TYPE_NAME, Case.class.getName());
		Case c = new Case();
		c.RecordTypeId = caseRecordTypeId;
		c.Origin = 'Email';
		c.Priority = 'Normal';
		c.Reason = 'Rewards';

		Test.startTest();
		try{
			Insert c;
		} catch (Exception e){
			System.assertEquals(true, e.getMessage().contains('Allowed values for Case Reason are : {Puzzles & Games}'));
		}
		Test.stopTest();
	}
}