src/objects/Case.object
<CustomObject>

    <fields>
        <fullName>OC_Batch_Updated_Date__c</fullName>
        <description>Date the last time the outbound calling batch updated the record.</description>
        <inlineHelpText>Date the last time the outbound calling batch updated the record.</inlineHelpText>
        <label>Batch Updated Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>Print_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Subscription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subscription__c.Subscriber__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Zuora Subscription</description>
        <inlineHelpText>Lookup field to Zuora Subscription</inlineHelpText>
        <label>Zuora Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>




</CustomObject>

src/objects/Outbound_Call_Batch_Setting__c.object
<CustomObject>
    <description>Configuration object for batch jobs generating Cases for Outbound Calling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Batch Setting is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Class_Name__c</fullName>
        <description>Batch Class Name</description>
        <inlineHelpText>Define the name of the batch class that generates the Cases</inlineHelpText>
        <label>Batch Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Job_Notifications__c</fullName>
        <description>Batch job errors and notifications</description>
        <inlineHelpText>Stores batch job errors and notifications from last 2 executions</inlineHelpText>
        <label>Batch Job Notifications</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <description>Batch status</description>
        <formula>IMAGE(
     IF(
        ISBLANK(Job_Id__c),
        &quot;/img/samples/light_red.gif&quot;,
        IF(
           Last_Execution_Error__c,
           &quot;/img/samples/light_yellow.gif&quot;,
           &quot;/img/samples/light_green.gif&quot;
        )
     ), 
     &quot;status color&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display the status of related scheduled job</inlineHelpText>
        <label>Batch Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_String__c</fullName>
        <description>Cron String</description>
        <inlineHelpText>Cron string to be used by the scheduler. Cron string definition: Seconds Minutes Hours Day_of_month Month Day_of_week optional_year</inlineHelpText>
        <label>Cron String</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executions__c</fullName>
        <description>Number of executions</description>
        <inlineHelpText>Stores the number of executions</inlineHelpText>
        <label>Executions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <description>Scheduled job Id</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is populated with the job Id after Schedule Job button is clicked</inlineHelpText>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Execution_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Last Execution Error</description>
        <inlineHelpText>Stores information whether last execution had an error</inlineHelpText>
        <label>Last Execution Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outbound_Call_Setting__c</fullName>
        <description>Related Outbound Call Setting</description>
        <inlineHelpText>Define Outbound Call Setting Master</inlineHelpText>
        <label>Outbound Call Setting</label>
        <referenceTo>Outbound_Call_Setting__c</referenceTo>
        <relationshipLabel>Outbound Call Batch Settings</relationshipLabel>
        <relationshipName>Outbound_Call_Batch_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>Scope of records</description>
        <inlineHelpText>Define the scope of records to be picked up</inlineHelpText>
        <label>Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Batch Setting</label>
    <nameField>
        <label>Outbound Call Batch Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Batch Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Call_Setting__c.object
<CustomObject>
    <description>Configuration object for Outbound Calling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Setting is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Queue_Name__c</fullName>
        <description>Default queue name</description>
        <inlineHelpText>Define default queue name</inlineHelpText>
        <label>Default Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Setting</label>
    <nameField>
        <label>Outbound Call Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OutboundCallingBatchUtils.cls
/**
* Author:       Michal Szewczyk
* Date:
* Description:  Helper methods for Outbound Calling Batches
*
* ******************* Change Log *******************
* Modified by       Change Date
* Michal Szewczyk   10/10/2016  - changed getQueueId
* Vishant Shah      05/05/2017  - added createCaseRecord()
**/

public with sharing class OutboundCallingBatchUtils {

   private static Map<String,Id> queueMapping = new Map<String,Id>();  

    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 7/07/2016
    Version - 1.0
    Function -  Populate case fields based on json string input
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public static Case populateCaseValues(String jsonInput){
		  Case deserializedCase = (Case) JSON.deserialize(jsonInput, Case.class);
		  return deserializedCase;
	}

    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 7/07/2016
    Version - 1.0
    Function - Fetch confing records
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public static Outbound_Call_Batch_Setting__c fetchConfigRecord(String batchName){

		Outbound_Call_Batch_Setting__c configRecord;
		List<Outbound_Call_Batch_Setting__c> tmpRec = [	SELECT 	Id,
																Batch_Class_Name__c,
																Batch_Job_Notifications__c,
																Batch_Status__c,
																Cron_String__c,
																Executions__c,
																Last_Execution_Error__c,
																Job_Id__c,
																Outbound_Call_Setting__c,
																Outbound_Call_Setting__r.Default_Queue_Name__c,
																Parameters__c,
																Scope__c,
																Active__c
					 									FROM Outbound_Call_Batch_Setting__c
						 								WHERE Batch_Class_Name__c =:batchName AND Active__c = true];

		if(tmpRec.size() == 1){
			configRecord = tmpRec[0];
			return configRecord;
		} else if(tmpRec.size() > 1) {
			throw new TelegraphApplicationException('Active Outbound Calling Batch has more than one active config record');
		} else {
			throw new TelegraphApplicationException('Active Outbound Calling Batch config record was not found');
		}
	}

    /***************************************************************************************
    Developer - Michal Szewczyk
    Date - 7/07/2016
    Version - 1.0
    Function -
    #############Change Log#############
    Modified by     Version     Change Date
    Michal Szewczyk 1.1         10/10/2016  - changed to more static
    ****************************************************************************************/
    public static Id getQueueId (String queueName) {    

        if(queueMapping.size() == 0 ) {
            for(Group tmpGroup : [Select Id, Name, DeveloperName, Type from Group where Type = 'Queue']) {
                queueMapping.put(tmpGroup.Name,tmpGroup.Id);
            }
        }

    	if(queueMapping.size() > 0 && queueMapping.containsKey(queueName)) {
    		return queueMapping.get(queueName);
    	} else {
			throw new TelegraphApplicationException('The queue does not exist : ' + queueName);
    	}
    }

    /***************************************************************************************
    Developer - Vishant Shah
    Date - 05/05/2017
    Version - 1.0
    Function - to create a reusable CASE creation method
    #############Change Log#############
    Modified by     Version     Change Date 
    ****************************************************************************************/
    public static Case createCaseRecord(Case templateCase, Subscription__c sub, Id recordTypeId, Id  ownerId){
        Case newCase                     = templateCase.clone();
        newCase.OwnerId                  = ownerId;
        newCase.AccountId                = sub.Subscriber__c;
        newCase.Print_Subscription__c    = sub.Id;
        newCase.RecordTypeId             = recordTypeId;
        newCase.OC_Batch_Updated_Date__c = Date.today();
        return newCase;
    }

}