src/objects/Case.object
<CustomObject>

    <fields>
        <fullName>OC_Call_Stage__c</fullName>
        <description>Outbound call stage name</description>
        <inlineHelpText>Outbound call stage name</inlineHelpText>
        <label>Call Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>T2</fullName>
                </value>
                <value>
                    <fullName>T2 Catch Up</fullName>
                </value>
                <value>
                    <fullName>TL1</fullName>
                </value>
                <value>
                    <fullName>TL2</fullName>
                </value>
                <value>
                    <fullName>BR1</fullName>
                </value>
                <value>
                    <fullName>CCEX1</fullName>
                </value>
                <value>
                    <fullName>DD Winback</fullName>
                </value>
                <value>
                    <fullName>DDCX</fullName>
                </value>
                <value>
                    <fullName>T2 28Days</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Outcome__c</fullName>
        <description>The outcome of the outbound call</description>
        <inlineHelpText>Please specify the outcome of the outbound call</inlineHelpText>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Answerphone</fullName>
                </value>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>No Sale</fullName>
                </value>
                <value>
                    <fullName>Cheque Sales</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>NATC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OC_Stage_1_Call_Date_Time__c</fullName>
        <description>The time call was made at the first stage</description>
        <inlineHelpText>The time call was made at the first stage</inlineHelpText>
        <label>T2 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_6_Call_Date_Time__c</fullName>
        <description>Date and time call was made at the sixth  stage</description>
        <inlineHelpText>CCEX1 call date and time</inlineHelpText>
        <label>CCEX1 Call Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OC_Stage_6_Outcome__c</fullName>
        <description>The outcome of the sixth call stage. This field is auto-populated from the selected outcome on the first call stage.</description>
        <inlineHelpText>The outcome of CCEX1 call</inlineHelpText>
        <label>CCEX1 Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>Print_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Print Subscription</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subscription__c.Subscriber__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>




</CustomObject>

src/classes/OutboundCallingCCExpiryCtrlTest.cls
/**
* @author Michal Szewczyk
* @date 01/08/2016
* @description Test class for OutboundCallingCCExpiryCtrl
* #############Change Log#############
* Modified by           Version     Change Date
* Michal Szewczyk       1.1         2/8/2016    //changed outboundCallingBalanceReviewCtrl_GetCustomerTest method
* Mantas Grigaliunas    1.2         30/08/2016  //added constant string for outbound calling setting paramters
* Mantas Grigaliunas    1.2         30/08/2016 //renamed field OC_Stage_1_Call_Date_Time__c to OC_Stage_6_Call_Date_Time__c
**/
@isTest
private class OutboundCallingCCExpiryCtrlTest {

    private final static String PARAMETER = '{'
    +   '  "callStageParameters": [ {'
    +   '  "stagename": "CCEX1",'
    +   '  "outcome": "OC_Stage_6_Outcome__c",'
    +   '  "calldatetime": "OC_Stage_6_Call_Date_Time__c",'
    +   '  "nosalereason": "",'
    +   '  "tcode": "",'
    +   '  "offset": 0'
    +   '}] }';
    
    /************************************************************************************
    Developer - Michal Szewczyk
    Date - 01/08/2016
    Version - 1.0
    Function - method to test the Constructor
    #############Change Log#############
    Modified by         Version     Change Date
    *************************************************************************************/
    static testMethod void outboundCallingBalanceReviewCtrl_NoOCSetting(){
        TestDataUtility tdu = new TestDataUtility(1);

        OutboundCallingCCExpiryCtrl controller;
        PageReference pr = Page.OutboundCallingCCExpiry;
        Test.setCurrentPage(pr);

        Test.startTest();

            //no Outbound Call Setting
            tdu.createOutboundCallSetting();
            tdu.lstOutboundCallSetting[0].Visualforce_Page__c = Constants.OC_CREDIT_CARD_EXPIRY_VF_PAGE_NAME;
            update tdu.lstOutboundCallSetting[0];
            controller = new OutboundCallingCCExpiryCtrl();
            System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.OC_OCS_Incomplete));
            
            //No Outbound Call Setting Parameters
            tdu.lstOutboundCallSetting[0].Case_Record_Type__c = Constants.OC_CREDIT_CARD_EXPIRY_RECORD_TYPE_NAME;
            update tdu.lstOutboundCallSetting[0];
            controller = new OutboundCallingCCExpiryCtrl();
            System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.OC_OCS_Parameters_Error));
            System.assert(!controller.hasCustomer);
        Test.stopTest();
    }

    /************************************************************************************
    Developer - Michal Szewczyk
    Date - 01/08/2016
    Version - 1.0
    Function - method to test the Constructor
    #############Change Log#############
    Modified by         Version     Change Date
    *************************************************************************************/
    static testMethod void outboundCallingBalanceReviewCtrl_NoOCRule(){
        TestDataUtility tdu = new TestDataUtility(1);

        tdu.createOutboundCallSetting();
        tdu.lstOutboundCallSetting[0].Visualforce_Page__c = Constants.OC_CREDIT_CARD_EXPIRY_VF_PAGE_NAME;
        tdu.lstOutboundCallSetting[0].Case_Record_Type__c = Constants.OC_CREDIT_CARD_EXPIRY_RECORD_TYPE_NAME;
        tdu.lstOutboundCallSetting[0].Parameters__c = PARAMETER;
        update tdu.lstOutboundCallSetting[0];

        OutboundCallingCCExpiryCtrl controller;
        PageReference pr = Page.OutboundCallingCCExpiry;
        Test.setCurrentPage(pr);

        Test.startTest();

            controller = new OutboundCallingCCExpiryCtrl();
            System.assert(TestDataUtility.checkIfMessageExists(ApexPages.getMessages(), Label.OC_OCR_Not_Found));

        Test.stopTest();
    }

    /************************************************************************************
    Developer - Michal Szewczyk
    Date - 01/08/2016
    Version - 1.0
    Function - method to test the Constructor
    #############Change Log#############
    Modified by         Version     Change Date
    Michal Szewczyk     1.1         2/08/2016  // added tests for save
    *************************************************************************************/
    static testMethod void outboundCallingBalanceReviewCtrl_GetCustomerTest(){
        TestDataUtility tdu = new TestDataUtility(1);

        tdu.createOutboundCallSetting();
        tdu.lstOutboundCallSetting[0].Visualforce_Page__c = Constants.OC_CREDIT_CARD_EXPIRY_VF_PAGE_NAME;
        tdu.lstOutboundCallSetting[0].Case_Record_Type__c = Constants.OC_CREDIT_CARD_EXPIRY_RECORD_TYPE_NAME;
        tdu.lstOutboundCallSetting[0].Parameters__c = PARAMETER;
        update tdu.lstOutboundCallSetting[0];

        tdu.createOutboundCallRule();
        tdu.lstOutboundCallRule[0].Priority_Field__c = 'Priority';
        update tdu.lstOutboundCallRule[0];

        tdu.createSubscriptions();

        tdu.createCase();
        tdu.lstCases[0].Status = Constants.UPGRADE_IN_PROGRESS;
        tdu.lstCases[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Case.SObjectType, tdu.lstOutboundCallSetting[0].Case_Record_Type__c, Case.class.getName());
        tdu.lstCases[0].OC_Call_Stage__c = 'CCEX1';
        tdu.lstCases[0].OC_Stage_6_Call_Date_Time__c = DateTime.now().addYears(-1);
        tdu.lstCases[0].AccountId = tdu.lstIndividualSubscribers[0].Id;
        tdu.lstCases[0].Print_Subscription__c = tdu.lstSubscriptions[0].Id;
        update tdu.lstCases[0];

        OutboundCallingCCExpiryCtrl controller;
        PageReference pr = Page.OutboundCallingCCExpiry;
        Test.setCurrentPage(pr);

        Test.startTest();

        	controller = new OutboundCallingCCExpiryCtrl();
        	controller.getCustomer();
            controller.selectedCase.OC_Outcome__c = 'No response';
            controller.enableSaveButton();
            controller.saveSelectedCustomer();

        Test.stopTest();

        System.assertEquals(controller.selectedCase != null , true , 'Case was not found');
        System.assertEquals(controller.selectedCase.AccountId,tdu.lstCases[0].AccountId, 'Incorect subscriber related to the case');

        List<Case> queryCase = [SELECT OC_Outcome__c FROM Case WHERE Id =:controller.selectedCase.Id];
        System.assertEquals(queryCase[0].OC_Outcome__c, 'No response' , 'Case was not savd correctly');

    }
    
}