src/objects/Cheque__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_Banking_Status__c</fullName>
        <inlineHelpText>Status of a sub payment cheque</inlineHelpText>
        <label>Cheque Banking Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                <fullName>Banked</fullName>
                <default>true</default>
                    <label>Banked</label>
                </value>
                <value>
                <fullName>Returned</fullName>
                </value>
                <value>
                <fullName>Issued</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cheque_Refund_Reason__c</fullName>
        <inlineHelpText>Reason for a cheque refund being raised</inlineHelpText>
        <label>Cheque Refund Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                <fullName>14 Day Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled Sub</fullName>
                </value>
                <value>
                <fullName>Deceased</fullName>
                </value>
                <value>
                <fullName>DD error</fullName>
                </value>
                <value>
                <fullName>Emigration</fullName>
                </value>
                <value>
                <fullName>Holiday Refund</fullName>
                </value>
                <value>
                <fullName>Serious Illness</fullName>
                </value>
                <value>
                <fullName>Indemnity</fullName>
                </value>
                <value>
                <fullName>Newsagent problem</fullName>
                </value>
                <value>
                <fullName>Marketed price issue</fullName>
                </value>
                <value>
                <fullName>CC Error</fullName>
                </value>
                <value>
                <fullName>Good will</fullName>
                </value>
                <value>
                <fullName>Missing/Lost Vouchers</fullName>
                </value>
                <value>
                <fullName>Poor Eyesight</fullName>
                </value>
                <value>
                <fullName>Review Of Personal Finances</fullName>
                </value>
                <value>
                <fullName>Price Increase</fullName>
                </value>
                <value>
                <fullName>DM Mailing Error</fullName>
                </value>
                <value>
                <fullName>Competitor Offer</fullName>
                </value>
                <value>
                <fullName>Too Much To Read</fullName>
                </value>
                <value>
                <fullName>Extended Holiday</fullName>
                </value>
                <value>
                <fullName>Distribution Problems</fullName>
                </value>
                <value>
                <fullName>Duplicate Paper</fullName>
                </value>
                <value>
                <fullName>Dislikes Paper</fullName>
                </value>
                <value>
                <fullName>Salesforce Error</fullName>
                </value>
                <value>
                <fullName>Occasional Reader</fullName>
                </value>
                <value>
                <fullName>Moved To a Care Home</fullName>
                </value>
                <value>
                <fullName>Voucher Style</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Sub Payment</fullName>
                </value>
                <value>
                <fullName>Anomaly Cheque</fullName>
                </value>
                <value>
                <fullName>Refund</fullName>
                </value>
                <value>
                <fullName>Refund - awaiting approval</fullName>
                </value>
                <value>
                <fullName>Indemnity Cheque</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cheque</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cheque ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateChequesToIssued.cls
public class UpdateChequesToIssued {
//SMS-321 
public Boolean UpdateThisChequeStatus(){
	Boolean Success=false;
	String q;
	list<String> f = new list<String>(); 
	list<String> v=new list<String>(); 
	try {
		q = 'Select id From Cheque__c c where (c.Type__c = \'Refund\' or  c.Type__c = \'Refund - awaiting approval\' or c.Type__c = \'Indemnity Cheque\') ';   

		f.add('Cheque_Banking_Status__c');
		f.add('Cheque_Refund_Reason__c');		
		v.add('Issued');
		v.add('Unknown');
		id batchinstanceid = database.executeBatch(new UpdateChequeStatusBatch(q,f,v)); 		
	}
	catch(Exception e){
		//send email if fails
		String toAddress = 'teamsalesforce@telegraph.co.uk';
		String replyToAddress = 'steven.fouracre@telegraph.co.uk';
		List<String> toAddresses = new List<String> {toAddress};
		    //use the new util class to send an email
		    TMGUtil.EmailUtil emailUtil = new TMGUtil.EmailUtil(toAddresses);
		    emailUtil.plainTextBody('The batch apex is now complete.')
	        .senderDisplayName('Steve Fouracre')
	        .replyTo(replyToAddress)
	        .subject('Update Cheque To Issued Batch Apex Complete')
	        .build()
	        .sendEmail(); 	
	        	
			system.debug(e);
	}
	Success=true;
	return Success;
}

}