src/objects/Cheque__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_Banking_Status__c</fullName>
        <inlineHelpText>Status of a sub payment cheque</inlineHelpText>
        <label>Cheque Banking Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                <fullName>Banked</fullName>
                <default>true</default>
                    <label>Banked</label>
                </value>
                <value>
                <fullName>Returned</fullName>
                </value>
                <value>
                <fullName>Issued</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cheque_Batch__c</fullName>
        <label>Cheque Batch</label>
        <referenceTo>Cheque_Batch__c</referenceTo>
        <relationshipLabel>Cheques</relationshipLabel>
        <relationshipName>Cheques</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Voucher_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Voucher Activity cheque created for</description>
        <inlineHelpText>Voucher Activity cheque created for</inlineHelpText>
        <label>Voucher Activity</label>
        <referenceTo>Voucher_Adjustment__c</referenceTo>
        <relationshipLabel>Cheques</relationshipLabel>
        <relationshipName>Cheques</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cheque</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cheque ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cheque_Batch__c.object
<CustomObject>
    <description>This is an object to which many cheques are linked</description>
    <fields>
        <fullName>Batch_Closed_Date__c</fullName>
        <label>Batch Closed Date</label>
        <type>Date</type>
    </fields>
    <label>Cheque Batch</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Cheque Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheque Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Voucher_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Refund_Status__c</fullName>
        <description>Status of a refund</description>
        <inlineHelpText>Status of a refund</inlineHelpText>
        <label>Refund Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Processed</fullName>
                </value>
                <value>
                <fullName>Waiting For Approval</fullName>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Partially Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Voucher Activity</label>
    <nameField>
        <displayFormat>VA-{0000000000}</displayFormat>
        <label>Voucher Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChequeBatchTriggerHandler.cls
/************************************************************************************
Class Name   : ChequeBatchTriggerHandler
Author       : Mantas Grigaliunas
Created Date : 25/11/2016
Function     : ChequeBatchTrigger handler class
Change Log:
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
* Developer             Date         Description
* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
*************************************************************************************/
public class ChequeBatchTriggerHandler {

    private static ChequeBatchTriggerHandler instance;
    public Boolean isExecuting = false;

    public static ChequeBatchTriggerHandler getInstance() {
        if (instance == null) instance = new ChequeBatchTriggerHandler();
        return instance; 
    }

    /************************************************************************************
    Method Name  : OnAfterUpdate
    Developer    : Mantas Grigaliunas
    Created Date : 25/11/2016
    Function     : Method to hold all custom methods called after record update
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer         Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
    public void OnAfterUpdate(List<Cheque_Batch__c> updatedChequeBatches, Map<ID, Cheque_Batch__c> oldChequeBatchMap){
        if (!this.isExecuting) {
            this.isExecuting = true;
            updateVoucherActiviesWithStatusProcessed(updatedChequeBatches, oldChequeBatchMap);
            this.isExecuting = false;        
        }   
    }

    /************************************************************************************
    Method Name  : updateVoucherActiviesWithStatusProcessed
    Developer    : Mantas Grigaliunas
    Created Date : 25/11/2016
    Function     : Method to update all related Voucher Activities Refund Status to processed
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer         Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
    public void updateVoucherActiviesWithStatusProcessed(List<Cheque_Batch__c> updatedChequeBatches, Map<ID, Cheque_Batch__c> oldChequeBatchMap){

        Id chequeBatchRecordTypeId = RecordTypeUtility.getRecordTypeId(Cheque_Batch__c.sObjectType, 
                Constants.VOUCHER_REFUND_CHEQUE_BATCH_RECORD_TYPE_NAME, Cheque_Batch__c.class.getName());
        Set<Id> vaBatcheSet = new Set<Id>();
        //check if cheque batch close date changed
        for(Cheque_Batch__c cb : updatedChequeBatches){
            if(cb.RecordTypeId == chequeBatchRecordTypeId
                && oldChequeBatchMap.get(cb.Id).Batch_Closed_Date__c == null
                && cb.Batch_Closed_Date__c != null){
                vaBatcheSet.add(cb.Id);
            }
        }

        if(vaBatcheSet.size() > 0){
            List<Voucher_Adjustment__c> voucherActivitiesToUpdate = new List<Voucher_Adjustment__c>();
            for(Cheque__c cheque : [SELECT Id, Voucher_Activity__c, Voucher_Activity__r.Refund_Status__c FROM Cheque__c 
                                        WHERE Voucher_Activity__c != NULL 
                                        AND Cheque_Banking_Status__c = :Constants.CHEQUE_BANKINGSTATUS_ISSUED 
                                        AND Cheque_Batch__c IN :vaBatcheSet]){


                voucherActivitiesToUpdate.add(new Voucher_Adjustment__c(
                    Id = cheque.Voucher_Activity__c,
                    Refund_Status__c = Constants.VOUCHERADJUSTMENT_REFUND_STATUS_PROCESSED )
                );
            }

            if(voucherActivitiesToUpdate.size() > 0){
                update voucherActivitiesToUpdate;
            }
        }
    }
}