src/objects/Cheque__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cheque_Amount__c</fullName>
        <label>Cheque Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cheque_Batch__c</fullName>
        <label>Cheque Batch</label>
        <referenceTo>Cheque_Batch__c</referenceTo>
        <relationshipLabel>Cheques</relationshipLabel>
        <relationshipName>Cheques</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_on_Cheque__c</fullName>
        <label>Name on Cheque</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ref_Number_on_Cheque__c</fullName>
        <label>Ref Number on Cheque</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Code__c</fullName>
        <label>Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cheques</relationshipLabel>
        <relationshipName>Cheques</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cheque</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cheque ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cheque_Batch__c.object
<CustomObject>
    <description>This is an object to which many cheques are linked</description>
    <fields>
        <fullName>Batch_Closed_Date__c</fullName>
        <label>Batch Closed Date</label>
        <type>Date</type>
    </fields>
    <label>Cheque Batch</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Cheque Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheque Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Payment_Details_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Details Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_DD_Payment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gross Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChequeTriggerHandlerTest.cls
/**
* @author Unknown
* @date Unknown
* @description Test class for ChequeTriggerHanlder
#############Change Log#############
Modified by     Version     Change Date
Wiktor Czykin   1.1         16/10/2015  //moved here testNewCheque() from ChequeIntoClosedBatchTriggerTest class
                                        //quickly refactored all test methods to use TestDataUtility not old unrelated test data generation class
Wiktor Czykin   1.2         01/03/2017  //added testSchoolSubsUpdate()
**/
@isTest
private class ChequeTriggerHandlerTest {
    
    static testMethod void testSubsUpdate() {
        TestDataUtility td = new TestDataUtility(1);
        td.checkChequeDependencies();

        Test.startTest();
            td.createCheques();
            List<Subscription__c> sub = [select Payment_Details_Received__c, total_dd_payment__c from subscription__c where Id = :td.lstSubscriptions[0].Id];
            System.assert(!sub.isEmpty());
            System.assert(sub[0].Payment_Details_Received__c);
            System.assert(sub[0].total_dd_payment__c == td.lstCheques[0].Cheque_Amount__c);
        Test.stopTest();
    }

    /***************************************************************************************
    Developer - Wiktor Czykin 
    Date - 01/03/2017
    Version - 1.0
    Function - test change of sub status to pending on cheque insert - for school sub and not for others
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    static testMethod void testSchoolSubsUpdate() {
        TestDataUtility td = new TestDataUtility(2);
        td.checkChequeDependencies();

        for(Subscription__c sub : td.lstSubscriptions){
            td.lstSubscriptions[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.sObjectType, Constants.RECTYPE_SUBSCRIPTION_SCHOOLS, Subscription__c.class.getName());
            td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_OFFERED;
            td.lstSubscriptions[1].Subscription_Status__c = Constants.SSTATUS_OFFERED;
        }
        update td.lstSubscriptions;

        Test.startTest();
            td.createCheques();
        Test.stopTest();
        
        Map<Id, Subscription__c> lstRefetch = new Map<Id, Subscription__c>([select Id, Subscription_Status__c, Payment_Details_Received__c from Subscription__c where Id in :td.lstSubscriptions]);
        System.assert(!lstRefetch.isEmpty());
        
        for(Subscription__c s : lstRefetch.values()){
            System.assert(s.Payment_Details_Received__c);
        }
        System.assertEquals(Constants.SSTATUS_PENDING, lstRefetch.get(td.lstSubscriptions[0].Id).Subscription_Status__c);
        System.assertEquals(Constants.SSTATUS_OFFERED, lstRefetch.get(td.lstSubscriptions[1].Id).Subscription_Status__c);

    }
    
    static testMethod void testUpdateCheque() {
        TestDataUtility td = new TestDataUtility();
        td.createCheques();

        Test.startTest();
            update td.lstCheques;
            delete td.lstCheques;
            undelete td.lstCheques;
        Test.stopTest();
    }

    static testMethod void testNewCheque() {
        TestDataUtility td = new TestDataUtility(1);
        td.createSubscriptions();   

        Cheque_Batch__c closedBatch = TestDataUtility.newChequeBatch(0);
        closedBatch.batch_closed_date__c = Date.today();
        insert closedBatch; 
        
        Cheque__c cheque = new Cheque__c(subscription__c = td.lstSubscriptions[0].id,
                               cheque_amount__c = 250,
                               ref_number_on_cheque__c = '2',
                               cheque_batch__c = closedBatch.id,
                               name_on_cheque__c = 'Fred Bloggs',
                               sort_code__c = '000000',
                               account_number__c = '12345678');
        try {
          insert cheque;
        } catch (Exception ex) {
    }
  }

}