src/objects/FulfillmentPlan__c.object
<CustomObject>
    <description>Holds pricing option entitlements</description>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Digital</fullName>
                </value>
                <value>
                <fullName>Premium</fullName>
                </value>
                <value>
                <fullName>Webpack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment Plan</label>
    <nameField>
        <displayFormat>FP-{000}</displayFormat>
        <label>Fulfillment Plan Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricing_Options__c.object
<CustomObject>
    <description>Custom Object to hold Service Id &amp; Service Price Id</description>
    <fields>
        <fullName>FulfillmentPlanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FulfillmentPlanId</label>
        <referenceTo>FulfillmentPlan__c</referenceTo>
        <relationshipLabel>Pricing Options</relationshipLabel>
        <relationshipName>Pricing_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>premium</fullName>
                </value>
                <value>
                <fullName>digital</fullName>
                </value>
                <value>
                <fullName>webpack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Options</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Pricing Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PricingOptionTriggerHandler.cls
public with sharing class PricingOptionTriggerHandler {

	private boolean AlreadyProcessed = false;

	private static PricingOptionTriggerHandler instance = null;
	
	public static PricingOptionTriggerHandler getInstance(){
		
		if(instance == null){
			instance = new PricingOptionTriggerHandler();
		}
		
		return instance;
		
	}

	public void OnBeforeInsert(list<Pricing_Options__c> newPricingOptions){
		assignFulfillmentPlan(newPricingOptions);
	}

	public void OnBeforeUpdate(list<Pricing_Options__c> newPricingOptions){
		system.debug('***AlreadyProcessed: ' + AlreadyProcessed);
		assignFulfillmentPlan(newPricingOptions);
	}

	private void assignFulfillmentPlan(list<Pricing_Options__c> newPricingOptions){
		/*
		Because this uses the singleton pattern,  when you insert a record in a test,  you cannot 
		trigger the update code afterwards because this has already run(!)
		Therefore,  always run this code if a test is in progress
		*/
		if(!AlreadyProcessed || Test.isRunningTest()){
			//Get the FulfillmentPlans
			map<string, id> plans = new map<string, id>();
			for(FulfillmentPlan__c plan : [select Id, ProductType__c from FulfillmentPlan__c]){
				plans.put(plan.ProductType__c.toLowerCase(), plan.Id);
			}
			system.debug('***plans: ' + plans);
			
			//Use the product type on the pricing option to assign the fulfillment plan
			if(!plans.isEmpty()){
				for(Pricing_Options__c pricingOption : newPricingOptions){
					if(pricingOption.Product_Type__c != null){
						pricingOption.FulfillmentPlanId__c = plans.get(pricingOption.Product_Type__c.toLowerCase());
					}
				}
			}
			
			AlreadyProcessed = true;
		}
		
	}

}