src/objects/General__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Odd settings that don&apos;t fit into any of the existing objects.  Kept as generic as possible by using name value pair pattern.</description>
    <fields>
        <fullName>Value_Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value for the setting so that it is easier to use for true/false settings.</description>
        <inlineHelpText>Boolean value for the setting so that it is easier to use for true/false settings.</inlineHelpText>
        <label>Value Boolean</label>
        <type>Checkbox</type>
    </fields>
    <label>General</label>
</CustomObject>

src/classes/PostcodeLookupController.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        PostcodeLookupController.cls
   Description: Controller class for visualforce component 'PostcodeLookup'. 

   Date         Version Author                      Summary of Changes 
   -----------  ------- -----------------   ------------------------------------------------------------------------------
   07/09/2015		1.0			Cristina Anghenie	disable postcode lookup functionality from the sandboxes
------------------------------------------------------------------------------------------------------------------------ */
public with sharing class PostcodeLookupController {

	public Boolean isOn{
		get{
			if(this.isOn == null){
				this.isOn = false;
				General__c setting = General__c.getInstance(Constants.POSTCODE_LOOKUP_CUSTOMSETTINGS);
				if(setting != null && setting.Value_Boolean__c){
					this.isOn = true;
				}
			}
			return this.isOn;
		}
		set;
	}
}