src/objects/General__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Odd settings that don&apos;t fit into any of the existing objects.  Kept as generic as possible by using name value pair pattern.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>General</label>
</CustomObject>

src/classes/SubscriberPortalUtil.cls
public with sharing class SubscriberPortalUtil {

    
    public static void sendEmail(String cls, String msg, String subject){
    	// Create a new single email message object  
        General__c sp = General__c.getInstance('Batch Subscription Failure User Email');
        
        List<String> emailAddresses = sp.Value__c.split(';');  
            
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        // Strings to hold the email addresses to which you are sending the email.  
            
        String[] toAddresses = emailAddresses;    
        mail.setToAddresses(toAddresses);       
        
        // Specify the name used as the display name.  
            
        mail.setSenderDisplayName('Salesforce Support: ' + cls);            
        mail.setSubject('Error: ' + subject);      
        mail.setUseSignature(false);
        
        // Specify the text content of the email.  
            
        mail.setPlainTextBody(msg);
        //mail.setHtmlBody('Error message follows: <p> <pre> <code> '+ msg +'</code> </pre> </p>');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });	
    }
}