src/objects/General__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Odd settings that don&apos;t fit into any of the existing objects.  Kept as generic as possible by using name value pair pattern.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>General</label>
</CustomObject>

src/objects/PlaneURL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLs for Integration to the Plane Partners</description>
    <fields>
        <fullName>baseURL__c</fullName>
        <label>baseURL</label>
        <type>Url</type>
    </fields>
    <label>PlaneURL</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Low_Start_Amendment_TCode_Helper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to TCode management that is never persisted. Just used as a helper field to find different active low start tcode in the Amend Subscription flow for low start.</description>
        <inlineHelpText>Lookup field to TCode management that is never persisted. Just used as a helper field to find different active low start tcode in the Amend Subscription flow for low start.</inlineHelpText>
        <label>Low Start Amendment TCode Helper</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected tcode is either not Low Start or not a valid one.</errorMessage>
            <filterItems>
                <field>TCodeManagement__c.Type__c</field>
                <operation>equals</operation>
                <value>Low Start</value>
            </filterItems>
            <filterItems>
                <field>TCodeManagement__c.Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions (Low Start Amendment TCode Helper)</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Low_Start_Period__c</fullName>
        <description>Low Start Period from related TCode. Populated on subscription creation.</description>
        <inlineHelpText>Low Start Period from related TCode. Populated on subscription creation.</inlineHelpText>
        <label>Low Start Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Start_Weekly_Price__c</fullName>
        <description>Price used during low start period.</description>
        <inlineHelpText>Price used during low start period.</inlineHelpText>
        <label>Low Start Weekly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MPP_Premium_Subscription_ID__c</fullName>
        <description>External ID for premium subscriptions stored in MPP.</description>
        <externalId>true</externalId>
        <label>MPP Premium Subscription ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Taken_Method__c</fullName>
        <description>Method of order - populated from Synthesis</description>
        <inlineHelpText>Method of order - populated from Synthesis</inlineHelpText>
        <label>Order Taken Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Outbound</fullName>
                </value>
                <value>
                <fullName>Inbound</fullName>
                </value>
                <value>
                <fullName>Coupon</fullName>
                </value>
                <value>
                <fullName>Auto Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <description>1 or 15 of each month</description>
        <label>Payment Date</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Cheque</fullName>
                </value>
                <value>
                <fullName>Direct Debit</fullName>
                </value>
                <value>
                <fullName>Credit Card</fullName>
                </value>
                <value>
                <fullName>Debit Card</fullName>
                </value>
                <value>
                <fullName>Charge Card</fullName>
                </value>
                <value>
                <fullName>Credit/Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reltionship to the Tcode object</description>
        <label>TCodeManagement</label>
        <referenceTo>TCodeManagement__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isContinuous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Continuous Subscription</description>
        <inlineHelpText>Is it a Continuous Subscription</inlineHelpText>
        <label>isContinuous</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LowStartSubscriptionRestartControlerTest.cls
/**
* @author Wiktor Czykin
* @date 29/10/2015
* @description Test class for LowStartSubscriptionRestartController
#############Change Log#############
Modified by     Version     Change Date
Michal Szewczyk	1.1			//removed payment type checkboxes 
**/
@isTest
private class LowStartSubscriptionRestartControlerTest {
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 29/10/2015
    Version - 1.0
    Function - test failure where no Id in the request 
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testConstructorFailureNoId(){
		Test.startTest();
			ApexPages.StandardController std = new ApexPages.StandardController(new Subscription__c());
			LowStartSubscriptionRestartController lss;
			try{
				lss = new LowStartSubscriptionRestartController(std);
				System.assert(false, 'Exception not thrown where should be.');
			}catch(Exception e){
				System.assert(e.getMessage().contains(Label.Low_Start_Restart_feature_missing_subscription_id));
			}
		Test.stopTest();
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 29/10/2015
    Version - 1.0
    Function - test failure where id is present but record cannot be found for that Id
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testConstructorFailureNoRecordForId(){
		TestDataUtility td = new TestDataUtility(2);
		td.createSubscriptions();
		delete td.lstSubscriptions[1];
		Test.startTest();
			ApexPages.StandardController std = new ApexPages.StandardController(td.lstSubscriptions[1]);
			LowStartSubscriptionRestartController lss;
			try{
				lss = new LowStartSubscriptionRestartController(std);
				System.assert(false, 'Exception not thrown where should be.');
			}catch(Exception e){
				System.assert(e.getMessage().contains(Label.Low_Start_Restart_feature_no_subscription_based_on_id));
			}
		Test.stopTest();
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 29/10/2015
    Version - 1.0
    Function - test failure where subscription is found but it does not meet the criteria for processing
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testProcessFailureNotValidRecordForProcessing(){
		TestDataUtility td = new TestDataUtility(1);
		td.createSubscriptions();
		Test.startTest();
			ApexPages.StandardController std = new ApexPages.StandardController(td.lstSubscriptions[0]);
			LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
			System.assertEquals(td.lstSubscriptions[0].Id, lss.subscription.Id);
			System.assert(lss.sError.contains(Label.Low_Start_Feature_validation_required_status));
		Test.stopTest();
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 11/11/2015
    Version - 1.0
    Function - test warning when start date past extraction date
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testPastExtractionDateStartDateWarning(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkSubscriptionDependencies();
		Subscription__c sub = TestDataUtility.newSubscripiton(0, td.lstIndividualSubscribers[0].Id, td.lstRetailers[0].Id, null);
		sub.RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		sub.isContinuous__c = true; 
		sub.Subscription_Status__c = Constants.SSTATUS_PENDING;
		insert sub;
		sub.Start_Date__c = Date.today().addDays(2);
		SubscriptionTriggerHandler.getInstance().isExecuting = true;
		update sub;
		SubscriptionTriggerHandler.getInstance().isExecuting = false;
		
		Test.startTest();
			General__c g = General__c.getInstance(Constants.GENERAL_SUBSCRIPTION_STARTDATEVALIDATION);
			System.assertNotEquals(null, g);
			g.Value__c = 'test';
			update g;
			PageReference pr = Page.LowStartSubscriptionRestart;
			Test.setCurrentPage(pr);
			ApexPages.StandardController std = new ApexPages.StandardController(sub);
			LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
			System.assertEquals(sub.Id, lss.subscription.Id);
			System.assert(lss.bPastSubscriptionWarning);
		Test.stopTest();
	}

	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 29/10/2015
    Version - 1.0
    Function - test failure where mpp subscription id criteria is not met
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testProcessFailureMissingMPPSubscriptionId(){
		TestDataUtility td = new TestDataUtility(1);
		td.checkSubscriptionDependencies();
		Subscription__c sub = TestDataUtility.newSubscripiton(0, td.lstIndividualSubscribers[0].Id, td.lstRetailers[0].Id, null);
		sub.RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		sub.isContinuous__c = true; 
		sub.Subscription_Status__c = Constants.SSTATUS_PENDING;
		insert sub;
		Test.startTest();
			ApexPages.StandardController std = new ApexPages.StandardController(sub);
			LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
			System.assertEquals(sub.Id, lss.subscription.Id);
			System.assert(lss.sError.contains(Label.Low_Start_Feature_validation_MPP_Subscription_Id_mandatory));
		Test.stopTest();
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/10/2015
    Version - 1.0
    Function - test failure response from mpp request 
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testMPPFailure(){
		TestDataUtility td = new TestDataUtility(1);
		List<PlaneURL__c> lstPlaneUrl = td.loadPlaneURL();
		td.checkSubscriptionDependencies();
		Subscription__c sub = TestDataUtility.newSubscripiton(0, td.lstIndividualSubscribers[0].Id, td.lstRetailers[0].Id, null);
		sub.RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		sub.isContinuous__c = true; 
		sub.Subscription_Status__c = Constants.SSTATUS_PENDING;
		sub.MPP_Premium_Subscription_Id__c = 'abc123';
		insert sub;
		
		ApexPages.StandardController std = new ApexPages.StandardController(sub);
		LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mppMock = new MPPWebserviceMocks.MPPHttpResponseGenerator(lstPlaneUrl[0].baseURL__c, new Map<String,String>{MPPWebserviceMocks.PARAM_ISFAILURE => 'true'});
			Test.setMock(HttpCalloutMock.class, mppMock);
			lss.processRestart();
			System.assert(lss.sError.contains(Label.Low_Start_Restart_feature_MPP_call_failure));
		Test.stopTest();
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/10/2015
    Version - 1.0
    Function - test success with DD payment subscription
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testSuccessDD(){
		TestDataUtility td = new TestDataUtility(1);
		List<PlaneURL__c> lstPlaneUrl = td.loadPlaneURL();
		td.createSubscriptionIncentiveAssociation();
		td.createTCodemanagement();
		td.lstSubscriptions[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		td.lstSubscriptions[0].isContinuous__c = true; 
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING;
		td.lstSubscriptions[0].MPP_Premium_Subscription_Id__c = 'abc123';
		td.lstSubscriptions[0].TCode__c = td.lstTCodeManagement[0].Id;
		td.lstSubscriptions[0].Order_Taken_Method__c = 'otm';
		td.lstSubscriptions[0].PaymentDate__c = '1';
		update td.lstSubscriptions[0];
		
		ApexPages.StandardController std = new ApexPages.StandardController( td.lstSubscriptions[0]);
		LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mppMock = new MPPWebserviceMocks.MPPHttpResponseGenerator(lstPlaneUrl[0].baseURL__c, new Map<String,String>());
			Test.setMock(HttpCalloutMock.class, mppMock);
			PageReference pr = lss.processRestart();
			System.assertNotEquals(null, pr);
			System.assertEquals(td.lstTCodeManagement[0].Name, pr.getParameters().get('tcode'), pr.getParameters().get('tcode') );
			System.assertEquals(td.lstSubscriptions[0].Order_Taken_Method__c, pr.getParameters().get('orderMethod'));
			System.assertEquals('52'+Constants.KEY_CONTINUOUS, pr.getParameters().get('subscriptionType'));
			System.assertEquals('true',pr.getParameters().get('hasBack'));
			System.assertEquals( Constants.OFFER_LOWSTART, pr.getParameters().get('selectedOffer'));
			System.assertEquals(Constants.PRODUCT_PREMIUM, pr.getParameters().get('selectedProduct'));
			System.assert(String.isBlank(pr.getParameters().get('paymentFrequency')));
			System.assertEquals(Constants.SUB_ACQUISITION_PAYMENT_DD, pr.getParameters().get('paymentType'));
			System.assertEquals(td.lstSubscriptions[0].PaymentDate__c, pr.getParameters().get('paymentStartDate'));
			System.assertEquals(td.lstRetailers[0].RET_ID__c, pr.getParameters().get('retailerid'));
			System.assertEquals(td.lstIncentives[0].Id, pr.getParameters().get('incentiveId'));
		Test.stopTest();
		List<Subscription__c> lstSubscription = [select Id, Subscription_Status__c from Subscription__c where Id = :td.lstSubscriptions[0].Id];
		System.assert(!lstSubscription.isEmpty());
		System.assertEquals(Constants.SSTATUS_OFFERED, lstSubscription[0].Subscription_Status__c);
	}

	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/10/2015
    Version - 1.0
    Function - test success with CC payment subscription
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testSuccessCC(){
		TestDataUtility td = new TestDataUtility(1);
		List<PlaneURL__c> lstPlaneUrl = td.loadPlaneURL();
		td.createSubscriptions();
		td.lstSubscriptions[0].Payment_Type__c = Constants.SUB_PMETHOD_CC;
		td.lstSubscriptions[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		td.lstSubscriptions[0].isContinuous__c = true; 
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING;
		td.lstSubscriptions[0].MPP_Premium_Subscription_Id__c = 'abc123';
		update td.lstSubscriptions[0];
		
		ApexPages.StandardController std = new ApexPages.StandardController( td.lstSubscriptions[0]);
		LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mppMock = new MPPWebserviceMocks.MPPHttpResponseGenerator(lstPlaneUrl[0].baseURL__c, new Map<String,String>());
			Test.setMock(HttpCalloutMock.class, mppMock);
			PageReference pr = lss.processRestart();
			System.assertEquals(Constants.DIRECTION_INBOUND, pr.getParameters().get('orderMethod'));
			System.assertEquals('52'+Constants.KEY_CONTINUOUS, pr.getParameters().get('subscriptionType'));
			System.assertEquals('true', pr.getParameters().get('hasBack'));
			System.assertEquals( Constants.OFFER_LOWSTART, pr.getParameters().get('selectedOffer'));
			System.assertEquals(Constants.PRODUCT_PREMIUM, pr.getParameters().get('selectedProduct'));
			System.assert(String.isBlank(pr.getParameters().get('paymentFrequency')));
			System.assertEquals(Constants.SUB_ACQUISITION_PAYMENT_CC, pr.getParameters().get('paymentType'));
			System.assertEquals(td.lstSubscriptions[0].PaymentDate__c, pr.getParameters().get('paymentStartDate'));
			System.assertEquals(td.lstRetailers[0].RET_ID__c, pr.getParameters().get('retailerid'));
			System.assert(String.isBlank(pr.getParameters().get('incentiveId')));
		Test.stopTest();
		List<Subscription__c> lstSubscription = [select Id, Subscription_Status__c from Subscription__c where Id = :td.lstSubscriptions[0].Id];
		System.assert(!lstSubscription.isEmpty());
		System.assertEquals(Constants.SSTATUS_OFFERED, lstSubscription[0].Subscription_Status__c);
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 30/10/2015
    Version - 1.0
    Function - test simulated failure on dmls
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testFailureOnUpdate(){
		TestDataUtility td = new TestDataUtility(1);
		List<PlaneURL__c> lstPlaneUrl = td.loadPlaneURL();
		td.createSubscriptions();
		td.lstSubscriptions[0].Payment_Type__c = Constants.SUB_PMETHOD_CC;
		td.lstSubscriptions[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		td.lstSubscriptions[0].isContinuous__c = true; 
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING;
		td.lstSubscriptions[0].MPP_Premium_Subscription_Id__c = 'abc123';
		update td.lstSubscriptions[0];
		
		ApexPages.StandardController std = new ApexPages.StandardController( td.lstSubscriptions[0]);
		LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
		lss.bTestFail = true;
		Test.startTest();
			MPPWebserviceMocks.MPPHttpResponseGenerator mppMock = new MPPWebserviceMocks.MPPHttpResponseGenerator(lstPlaneUrl[0].baseURL__c, new Map<String,String>());
			Test.setMock(HttpCalloutMock.class, mppMock);
			PageReference pr = lss.processRestart();
		Test.stopTest();
		List<Subscription__c> lstSubscription = [select Id, Subscription_Status__c from Subscription__c where Id = :td.lstSubscriptions[0].Id];
		System.assert(!lstSubscription.isEmpty());
		System.assertNotEquals(Constants.SSTATUS_OFFERED, lstSubscription[0].Subscription_Status__c);
	}
	
	/*************************************************************************************** 
    Developer - Wiktor Czykin
    Date - 11/11/2015
    Version - 1.0
    Function - test success with DD payment subscription
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	private static testMethod void testSuccessDDWithTCodeChange(){
		TestDataUtility td = new TestDataUtility(2);
		List<PlaneURL__c> lstPlaneUrl = td.loadPlaneURL();
		td.createSubscriptionIncentiveAssociation();
		td.createTCodemanagement();
		td.checkSubscriptionDependencies();
		
		td.lstTCodeManagement[1].Type__c = Constants.TCODE_TYPE_LOWSTART;
		td.lstTCodeManagement[1].Low_Start_Period__c = '13';
		td.lstTCodeManagement[1].Low_Start_Weekly_Price__c = 9;
		td.lstTCodeManagement[1].Payment_Type__c =Constants.ALLOW_52_WEEK_DD;
		update td.lstTCodeManagement[1];
		
		td.lstSubscriptions[0].RecordTypeId = RecordTypeUtility.getRecordTypeId(Subscription__c.SObjectType, Constants.RECTYPE_SUBSCRIPTION_LOWSTART, Subscription__c.class.getName());
		td.lstSubscriptions[0].isContinuous__c = true; 
		td.lstSubscriptions[0].Subscription_Status__c = Constants.SSTATUS_PENDING;
		td.lstSubscriptions[0].MPP_Premium_Subscription_Id__c = 'abc123';
		td.lstSubscriptions[0].TCode__c = td.lstTCodeManagement[0].Id;
		td.lstSubscriptions[0].Order_Taken_Method__c = 'otm';
		td.lstSubscriptions[0].PaymentDate__c = '1';
		update td.lstSubscriptions[0];
		
		ApexPages.StandardController std = new ApexPages.StandardController( td.lstSubscriptions[0]);
		LowStartSubscriptionRestartController lss = new LowStartSubscriptionRestartController(std);
		Test.startTest();
			lss.bChangeOffer = true;
			lss.subscriptionTemp.Low_Start_Amendment_TCode_Helper__c = td.lstTCodeManagement[1].Id;
		
			MPPWebserviceMocks.MPPHttpResponseGenerator mppMock = new MPPWebserviceMocks.MPPHttpResponseGenerator(lstPlaneUrl[0].baseURL__c, new Map<String,String>());
			Test.setMock(HttpCalloutMock.class, mppMock);
			PageReference pr = lss.processRestart();
			System.assertNotEquals(null, pr);
			System.assertEquals(td.lstTCodeManagement[1].Name, pr.getParameters().get('tcode'), pr.getParameters().get('tcode') );
			System.assertEquals(td.lstSubscriptions[0].Order_Taken_Method__c, pr.getParameters().get('orderMethod'));
			System.assertEquals('52'+Constants.KEY_CONTINUOUS, pr.getParameters().get('subscriptionType'));
			System.assertEquals('true',pr.getParameters().get('hasBack'));
			System.assertEquals( Constants.OFFER_LOWSTART, pr.getParameters().get('selectedOffer'));
			System.assertEquals(Constants.PRODUCT_PREMIUM, pr.getParameters().get('selectedProduct'));
			System.assert(String.isBlank(pr.getParameters().get('paymentFrequency')));
			System.assertEquals(Constants.SUB_ACQUISITION_PAYMENT_DD, pr.getParameters().get('paymentType'));
			System.assertEquals(td.lstSubscriptions[0].PaymentDate__c, pr.getParameters().get('paymentStartDate'));
			System.assertEquals(td.lstRetailers[0].RET_ID__c, pr.getParameters().get('retailerid'));
			System.assertEquals(td.lstIncentives[0].Id, pr.getParameters().get('incentiveId'));
		Test.stopTest();
		List<Subscription__c> lstSubscription = [select Id, Subscription_Status__c from Subscription__c where Id = :td.lstSubscriptions[0].Id];
		System.assert(!lstSubscription.isEmpty());
		System.assertEquals(Constants.SSTATUS_OFFERED, lstSubscription[0].Subscription_Status__c);
	}
}