src/objects/Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Incentive_Description__c</fullName>
        <label>Incentive Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Incentive_Description__c</fullName>
        <description>Incentive Description for Adobe Campaign Welcome Email</description>
        <label>Incentive Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscriptionIncentiveAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Incentive_Description__c</fullName>
        <formula>Incentive__r.Incentive_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incentive Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incentive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select only valid incentives.</errorMessage>
            <filterItems>
                <field>Incentive__c.Validity_Status__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incentive__c</referenceTo>
        <relationshipLabel>Subscription Incentives</relationshipLabel>
        <relationshipName>SubscriptionIncentiveAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>SubscriptionIncentiveAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Incentive</label>
    <nameField>
        <displayFormat>SIA-{0000000000}</displayFormat>
        <label>SubscriptionIncentiveAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionIncentiveTriggerHandler.cls
/**
* @author Cristina Anghenie
* @date 25/09/2015
* @description Subscription Incentive Association trigger handler
#############Change Log#############
Modified by     Version     Change Date
**/
public with sharing class SubscriptionIncentiveTriggerHandler {
	
	public void OnAfterInsert(List<SubscriptionIncentiveAssociation__c> newSubIncentives){
		updateSubscriptionIncentiveDescription(newSubIncentives);
	}
	
	/*************************************************************************************** 
    Developer - Cristina Anghenie
    Date - 25/09/2015
    Version - 1.1
    Function - Populate Incentive_Description__c when a new incentive is added to a subscription
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
	public void updateSubscriptionIncentiveDescription(List<SubscriptionIncentiveAssociation__c> newSubIncentives){
		map<Id,SubscriptionIncentiveAssociation__c> subIncentivesDesc = new map<Id,SubscriptionIncentiveAssociation__c>();
		List<Subscription__c> subsToUpdate = new List<Subscription__c>();
		//create a map with all the subs that ne
		for(SubscriptionIncentiveAssociation__c sia : [SELECT Incentive__r.Incentive_Description__c, Subscription__r.Incentive_Description__c, Subscription__c 
													   FROM SubscriptionIncentiveAssociation__c 
													   WHERE Id IN: newSubIncentives
													   ORDER BY Subscription__c, CreatedDate desc]){
			if(sia.Subscription__c!=null && !subIncentivesDesc.keyset().contains(sia.Subscription__c)){
	    		subIncentivesDesc.put(sia.Subscription__c, sia);
	    	}
		}
		if(!subIncentivesDesc.isEmpty()){
			//populate the incentive description field if subs status moves to pending
	    	for (Id subId : subIncentivesDesc.keyset()){
	        	subsToUpdate.add(new Subscription__c( Id = subId, Incentive_Description__c = subIncentivesDesc.get(subId).Incentive__r.Incentive_Description__c));
	        }
		}
		//update subs but skip DeferredCalculation
		if(!subsToUpdate.isEmpty()){	
			SubscriptionTriggerHandler.getInstance().bDeferredCalculationSkip = true; 
			update subsToUpdate;
			SubscriptionTriggerHandler.getInstance().bDeferredCalculationSkip = false; 
		}
		 
	}
}