src/objects/MPP_Transaction_History__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>MPP Transaction Histories</relationshipLabel>
        <relationshipName>MPP_Transaction_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>MPP Transaction History</label>
    <nameField>
        <displayFormat>MPP-{0000}</displayFormat>
        <label>MPP Transaction History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPP Transaction Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>DD_Not_Completed_Payments_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of DD Payments that were made within last 5 days. This field is used in Paid Until date calculation.</description>
        <inlineHelpText>Sum of DD Payments that were made within last 5 days. This field is used in Paid Until date calculation.</inlineHelpText>
        <label>DD Not Completed Payments Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total price for the subscription.</description>
        <formula>IF(
   Subscription_Duration_Number__c == 13, 
   IF(
      TCode_Product__r.X13_Week_Price__c == 0, 
      Weekly_Price__c * 13,
      TCode_Product__r.X13_Week_Price__c
   ),
   (Subscription_Duration_Number__c * Weekly_Price__c  - IF(
                                                            NOT(ISNULL(Low_Start_Weekly_Price__c)),
                                                            Low_Start_Period__c * (Weekly_Price__c - Low_Start_Weekly_Price__c),
                                                            0
                                                           )
   )
   )*MAX(Quantity__c, 1)
</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total price for the subscription.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionPaymentsBalanceUpdateTest.cls
/************************************************************************************
Class Name   : SubscriptionPaymentsBalanceUpdateTest
Author       : Mantas Grigaliunas
Created Date : 16/01/2017
Function     : Unit Test class for SubscriptionPaymentsBalanceUpdateBatch and SubscriptionPaymentsBalanceUpdtScheduler
Change Log:
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
* Developer             Date         Description
* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
*************************************************************************************/
@isTest
private class SubscriptionPaymentsBalanceUpdateTest {
	
   	//CRON expression: midnight on March 15.
   	public static String CRON_EXP = '0 0 0 15 3 ? 2022';
   	public static Integer RECORDS_SIZE = 3;

    /************************************************************************************
    Method Name  : testSetup
    Author       : Mantas Grigaliunas
    Created Date : 16/01/2017
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer    Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
   	@testSetup static void testSetup(){
   		TestDataUtility td = new TestDataUtility(RECORDS_SIZE);
        td.createMPPTransactionHistory(TestDataUtility.PAYMENTMETHOD_DD);
   	}


    /************************************************************************************
    Method Name  : subscriptionPaymentBalanceUpdateTest
    Author       : Mantas Grigaliunas
    Created Date : 16/01/2017
    Change Log:
    -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
    * Developer    Date         Description
    * -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
    *************************************************************************************/
   	@isTest static void subscriptionPaymentBalanceUpdateTest(){

   		Test.startTest();

   		//check if MPP Historic Transaction records inserted
   		List<MPP_Transaction_History__c> lstMpp = [ SELECT Id, Payment_Date__c, Total_Price__c, Subscription__c FROM MPP_Transaction_History__c];
   		System.assertEquals(RECORDS_SIZE, lstMpp.size());

   		//declare subscription with mpp payment amount map
   		Map<Id, Decimal> totalPriceMap = new Map<Id, Decimal>();
   		for(MPP_Transaction_History__c mpp : lstMpp){
   			totalPriceMap.put(mpp.Subscription__c, mpp.Total_Price__c);
   			//set the payment day to five days back
   			mpp.Payment_Date__c = Date.today().addDays(-5);
   		}

      	//Verify subscriptions are updated with expected sums
   	    for(Subscription__c sub : [ SELECT Id, DD_Not_Completed_Payments_Sum__c FROM Subscription__c WHERE Id IN :totalPriceMap.keySet()]){
   			System.assertEquals(totalPriceMap.get(sub.Id), sub.DD_Not_Completed_Payments_Sum__c);
   		}

   		//update mpp payments with the new payment date so these records are picked up by batch job
   		update lstMpp;

	    //Schedule the test job
	    String jobId = System.schedule('SubscriptionPaymentsBalanceUpdtSchedulerTest', CRON_EXP, new SubscriptionPaymentsBalanceUpdtScheduler());

      	// Because this is a test, job executes immediately after Test.stopTest().
      	Test.stopTest();

      	//check if DD_Not_Completed_Payments_Sum__c was updated with a new balance
      	for(Subscription__c sub : [ SELECT Id, DD_Not_Completed_Payments_Sum__c FROM Subscription__c WHERE Id IN :totalPriceMap.keySet()]){
   			System.assertEquals(0, sub.DD_Not_Completed_Payments_Sum__c);
   		}
   	}
	
}