src/objects/Outbound_Call_Batch_Setting__c.object
<CustomObject>
    <description>Configuration object for batch jobs generating Cases for Outbound Calling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Batch Setting is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Class_Name__c</fullName>
        <description>Batch Class Name</description>
        <inlineHelpText>Define the name of the batch class that generates the Cases</inlineHelpText>
        <label>Batch Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Job_Notifications__c</fullName>
        <description>Batch job errors and notifications</description>
        <inlineHelpText>Stores batch job errors and notifications from last 2 executions</inlineHelpText>
        <label>Batch Job Notifications</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <description>Batch status</description>
        <formula>IMAGE(
     IF(
        ISBLANK(Job_Id__c),
        &quot;/img/samples/light_red.gif&quot;,
        IF(
           Last_Execution_Error__c,
           &quot;/img/samples/light_yellow.gif&quot;,
           &quot;/img/samples/light_green.gif&quot;
        )
     ), 
     &quot;status color&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display the status of related scheduled job</inlineHelpText>
        <label>Batch Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_String__c</fullName>
        <description>Cron String</description>
        <inlineHelpText>Cron string to be used by the scheduler. Cron string definition: Seconds Minutes Hours Day_of_month Month Day_of_week optional_year</inlineHelpText>
        <label>Cron String</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executions__c</fullName>
        <description>Number of executions</description>
        <inlineHelpText>Stores the number of executions</inlineHelpText>
        <label>Executions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <description>Scheduled job Id</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is populated with the job Id after Schedule Job button is clicked</inlineHelpText>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Execution_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Last Execution Error</description>
        <inlineHelpText>Stores information whether last execution had an error</inlineHelpText>
        <label>Last Execution Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outbound_Call_Setting__c</fullName>
        <description>Related Outbound Call Setting</description>
        <inlineHelpText>Define Outbound Call Setting Master</inlineHelpText>
        <label>Outbound Call Setting</label>
        <referenceTo>Outbound_Call_Setting__c</referenceTo>
        <relationshipLabel>Outbound Call Batch Settings</relationshipLabel>
        <relationshipName>Outbound_Call_Batch_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>Scope of records</description>
        <inlineHelpText>Define the scope of records to be picked up</inlineHelpText>
        <label>Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Batch Setting</label>
    <nameField>
        <label>Outbound Call Batch Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Batch Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Call_Setting__c.object
<CustomObject>
    <description>Configuration object for Outbound Calling</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active setting</description>
        <inlineHelpText>Define whether Setting is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <description>Setting parameters in json format</description>
        <inlineHelpText>Define Setting parameters in json format</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outbound Call Setting</label>
    <nameField>
        <label>Outbound Call Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Call Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OutboundCallManageJobExtension.cls
/**
* @author Pawel Chrzanowski
* @date 08/07/2016
* @description  Outbound Call Batch Setting's Manage Job Controller Extension
#############Change Log#############
**/
global class OutboundCallManageJobExtension {

    public Outbound_Call_Batch_Setting__c ocbs {get;set;}
    public CronTrigger ct {get;set;}
    public Boolean hasJob {get;set;}
    public Boolean hasJobId {get;set;}
    public Boolean hasBatchClassName {get;set;}
    public Boolean isActive {get;set;}
    public String errorMessage {get;set;}

    /*************************************************************************************** 
    Developer   Pawel Chrzanowski
    Date        08/07/2016
    Function    Constructor
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
    public OutboundCallManageJobExtension(ApexPages.StandardController stdController){
        Id ocbsId = stdController.getId();
        hasJob = false;
        hasJobId = false;
        hasBatchClassName = false;
        isActive = false;

        if(ocbsId != null){
            List<Outbound_Call_Batch_Setting__c> lstOcbs = [select Name, Active__c, Batch_Class_Name__c, Batch_Job_Notifications__c, Batch_Status__c, Cron_String__c, Executions__c, Job_Id__c, Last_Execution_Error__c, Outbound_Call_Setting__c, Parameters__c, Scope__c from Outbound_Call_Batch_Setting__c where Id = :ocbsId];
            if(!lstOcbs.isEmpty()){
                if(String.isNotBlank(lstOcbs[0].Batch_Class_Name__c) && String.isNotBlank(lstOcbs[0].Cron_String__c)){
                    ocbs = lstOcbs[0];
                    hasBatchClassName = true;
                    isActive = ocbs.Active__c;
                    checkJobStatus();
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Outbound_Call_Batch_Setting_Batch_Name_Not_Found));
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Outbound_Call_Batch_Setting_Not_Found));
            }
        }
    }

    /*************************************************************************************** 
    Developer   Pawel Chrzanowski
    Date        08/07/2016
    Function    Method to check job status
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
    public void checkJobStatus(){
        if(String.isNotBlank(ocbs.Job_Id__c)){
            hasJobId = true;
            List<CronTrigger> lstCt = [select CronExpression, TimesTriggered, NextFireTime, CronJobDetail.Name, CronJobDetail.JobType from CronTrigger where Id = :ocbs.Job_Id__c];
            if(!lstCt.isEmpty()){
                ct = lstCt[0];
                hasJob = true;
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Outbound_Call_Batch_Setting_Job_Not_Found));
            }
        }
    }

    /*************************************************************************************** 
    Developer   Pawel Chrzanowski
    Date        08/07/2016
    Function    Method for JS Remoting to schedule a job
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
    @RemoteAction
    global static String scheduleJob(String id){
        List<Outbound_Call_Batch_Setting__c> lstOcbs = [select Batch_Class_Name__c, Cron_String__c from Outbound_Call_Batch_Setting__c where Id = :id];
        if(!lstOcbs.isEmpty()){
            if(TMGUtil.isDataValid(lstOcbs[0].Batch_Class_Name__c) && TMGUtil.isDataValid(lstOcbs[0].Cron_String__c)){
                try{
                    Type t = Type.forName(lstOcbs[0].Batch_Class_Name__c);
                    String jobId = System.schedule('Outbound Call Batch (' + id + ')', lstOcbs[0].Cron_String__c, (Schedulable)t.newInstance());
                    lstOcbs[0].Job_Id__c = jobId;
                    update lstOcbs[0];
                    return 'success';
                }catch(Exception e){
                    System.debug('### OutboundCallManageJobExtension.scheduleJob -> Exception: ' + e.getMessage());
                    return Label.Outbound_Call_Batch_Setting_Error + ' ' + e.getMessage();
                }
            }else{
                System.debug('### OutboundCallManageJobExtension.scheduleJob -> Error: ' + Label.Outbound_Call_Batch_Setting_Batch_Name_Not_Found);
                return Label.Outbound_Call_Batch_Setting_Error + ' ' + Label.Outbound_Call_Batch_Setting_Batch_Name_Not_Found;
            }
        }else{
            System.debug('### OutboundCallManageJobExtension.scheduleJob -> Error: ' + Label.Outbound_Call_Batch_Setting_Not_Found);
            return Label.Outbound_Call_Batch_Setting_Error + ' ' + Label.Outbound_Call_Batch_Setting_Not_Found;
        }
    }

    /*************************************************************************************** 
    Developer   Pawel Chrzanowski
    Date        08/07/2016
    Function    Method for JS Remoting to unschedule a job
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
    @RemoteAction
    global static String unscheduleJob(String id){
        List<Outbound_Call_Batch_Setting__c> lstOcbs = [select Job_Id__c from Outbound_Call_Batch_Setting__c where Id = :id];
        if(!lstOcbs.isEmpty()){
            if(TMGUtil.isDataValid(lstOcbs[0].Job_Id__c)){
                try{
                    System.abortJob(lstOcbs[0].Job_Id__c);
                    lstOcbs[0].Job_Id__c = null;
                    update lstOcbs[0];
                    return 'success';
                }catch(Exception e){
                    System.debug('### OutboundCallManageJobExtension.unscheduleJob -> Exception: ' + e.getMessage());
                    return Label.Outbound_Call_Batch_Setting_Error + ' ' + e.getMessage();
                }
            }else{
                System.debug('### OutboundCallManageJobExtension.unscheduleJob -> Error: ' + Label.Outbound_Call_Batch_Setting_Job_Id_Not_Found);
                return Label.Outbound_Call_Batch_Setting_Error + ' ' + Label.Outbound_Call_Batch_Setting_Job_Id_Not_Found;
            }
        }else{
            System.debug('### OutboundCallManageJobExtension.unscheduleJob -> Error: ' + Label.Outbound_Call_Batch_Setting_Not_Found);
            return Label.Outbound_Call_Batch_Setting_Error + ' ' + Label.Outbound_Call_Batch_Setting_Not_Found;
        }
    }

    /*************************************************************************************** 
    Developer   Pawel Chrzanowski
    Date        08/07/2016
    Function    Method for Action Function to display Apex PageMessage
    ******************* Change Log *******************
    Modified by         Version     Change Date
    ****************************************************************************************/
    public void showErrorMessage(){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, this.errorMessage));
    }
}