src/objects/Plan__c.object
<CustomObject>
    <description>Grouping object for Price Plans.</description>
    <fields>
        <fullName>Days_Before__c</fullName>
        <label>Days Before</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populate with the product that should be used for product validation (Product To) on related Print Price Plan records.</inlineHelpText>
        <label>Destination Product</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Plan__c.object
<CustomObject>
    <description>Defines upgrade/downgrade options for products and pricing. Used for both old print world renewals and Zuora world flexible pricing.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Price Plans</relationshipLabel>
        <relationshipName>Price_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Plan__c</fullName>
        <label>Price Plan</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Plan 0</fullName>
                </value>
                <value>
                <fullName>Plan 1</fullName>
                </value>
                <value>
                <fullName>Plan 2</fullName>
                </value>
                <value>
                <fullName>Plan 3</fullName>
                </value>
                <value>
                <fullName>Plan 4</fullName>
                </value>
                <value>
                <fullName>Plan 5</fullName>
                </value>
                <value>
                <fullName>Plan S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Plan</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Price Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Plan_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Price_Plan__c</fullName>
        <label>Price Plan</label>
        <referenceTo>Price_Plan__c</referenceTo>
        <relationshipLabel>Price Plan Offers</relationshipLabel>
        <relationshipName>Price_Plan_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Price Plan Offer</label>
    <nameField>
        <displayFormat>PPO-{0000000000}</displayFormat>
        <label>Price Plan Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Plan Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PricePlanRulesCloneController.cls
/**
* Author:       Gavin Palmer (Accenture)
* Date:         21/04/2016
* Description:  The page is designed to override the standard clone functionality
*               so that it also brings back the child records.
* ******************* Change Log *******************
* Modified by       Change Date     Description
* Michal Szewczyk   11/11/2016      Changed saveClonedRecord();
* Michal Szewczyk   14/11/2016      Changed PricePlanRulesCloneController()
* Wiktor Czykin     17/05/2017      Changed saveClonedRecord()
**/
public class PricePlanRulesCloneController {

    private Id originalPlanId;
    public Plan__c planClone {get; set;}
    private Boolean isAllowedFullSave {get; set;}

    /**
    * Author:       Gavin Palmer (Accenture)
    * Date:         21/04/2016
    * Description:  a standard controller is implimented so that we can override 
    *               the standard clone functionality
    * ******************* Change Log *******************
    * Modified by       Change Date     Description
    * Michal Szewczyk   14/11/2016      Added Product__c to soql for clone 
    **/
    public PricePlanRulesCloneController(ApexPages.StandardController controller) {
        
        originalPlanId = controller.getId();
        List<Plan__c> planList = [
            SELECT Id, Name, Days_Before__c, Is_Valid__c, Description__c,Product__c
            FROM Plan__c
            WHERE Id = :originalPlanId
            LIMIT 1
        ];
        if(planList.isEmpty()) throw new TelegraphApplicationException(Label.Price_Plan_Retrieve_Records_Error);

        planClone = planList[0].clone(false, true);
       
        //by default do not allow full save
        isAllowedFullSave = false;
    }

    /**
    * Author:       Gavin Palmer (Accenture)
    * Date:         21/04/2016
    * Description:  Redirect to the original record
    *
    * ******************* Change Log *******************
    * Modified by       Change Date     Description
    **/
    public PageReference returnToOriginalPlanPage(){
        PageReference planRecordPage = new PageReference('/' + originalPlanId);
        planRecordPage.setRedirect(true);
        return planRecordPage;
    }

    /**
    * Author:       Gavin Palmer (Accenture)
    * Date:         21/04/2016
    * Description:  Validate that we can save child records and continue
    * ******************* Change Log *******************
    * Modified by       Change Date     Description
    **/
    public PageReference saveChildRecords(){
        //validate that the logged in user has the campaign offer code management permission set
        //if not, this user can't save the child records
        List<PermissionSetAssignment> lstAssignment = [
            SELECT PermissionSetId 
            FROM PermissionSetAssignment
            WHERE AssigneeId= :UserInfo.getUserId() 
            AND PermissionSet.Name = :Constants.TCODE_OFFER_CODE_MANAGEMENT_PERMISSION_SET
        ];
        
        // if the class is running in a test I want it to ignore the error message part
        if(lstAssignment.isEmpty() && !Test.isRunningTest()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Price_Plan_Insufficient_Privileges_2));
            return null;
        } else {
            isAllowedFullSave = true;
            return saveClonedRecord();
        }
    }

    /**
    * Author:       Gavin Palmer (Accenture)
    * Date:         21/04/2016
    * Description:  Save the record, and if allowed save the child records
    * ******************* Change Log *******************
    * Modified by       Change Date     Description
    * Michal Szewczyk   11/11/2016      Added cloning for childs Price_Plan_Offers records
    * Wiktor Czykin     17/05/2017      Changed SoqlUtility reference to GlobalQueries 
    **/
    public PageReference saveClonedRecord(){
        PageReference pageDestination;
        // Set a savepoint so that the parent record doesnt save if the children dont
        Savepoint sp = Database.setSavepoint();

        if(isValidPricePlan()){
            try{

                insert planClone;

            } catch (Exception exceptionToHandle){
                System.debug(loggingLevel.Error, 'An error has occured in: ' + exceptionToHandle);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Price_Plan_Clone_Save_Error));
                return null;
            }
        } else {
            return pageDestination;
        }

        if(isAllowedFullSave){
            try{
                // find the children price plan objects
                String whereClause = 'Plan__c = \'' + originalPlanId + '\'';
                String soqlQueryString = GlobalQueries.queryBuilderSelectAll(Price_Plan__c.class.getName(), null, whereClause, '', '');
                String soqlQueryOffersString = GlobalQueries.queryBuilderSelectAll(Price_Plan_Offer__c.class.getName(), null, '', '', '');
                soqlQueryOffersString = soqlQueryOffersString.replace('Price_Plan_Offer__c', 'Price_Plan_Offers__r');
                String soqlfinalQuery = soqlQueryString.replace('SELECT ', 'SELECT ('+soqlQueryOffersString+'),' );
                List<Price_Plan_Offer__c> pricePlansOffers = new List<Price_Plan_Offer__c>();
                List<Price_Plan__c> childrenPricePlans = Database.query(soqlfinalQuery);
                Price_Plan__c tmp = null;
                // clone the price plan objects and add the cloned plan as the new lookup
                List<Price_Plan__c> clonedPricePlans = new List<Price_Plan__c>();
                Map<Integer,List<Price_Plan_Offer__c>> pricePlanOfferMapping = new Map<Integer,List<Price_Plan_Offer__c>>();
                Integer i = 0;
                for(Price_Plan__c pricePlan : childrenPricePlans){

                    Price_Plan__c pricePlanClone = pricePlan.clone(false, true);
                    pricePlanClone.Plan__c = planClone.Id;
                    clonedPricePlans.add(pricePlanClone);
                    pricePlanOfferMapping.put(i,pricePlan.Price_Plan_Offers__r.deepClone(false,false,false));
                    i++;
                }
               insert clonedPricePlans;
               for(Integer j=0;j < clonedPricePlans.size();j++){
                    for(Price_Plan_Offer__c ppOffer: pricePlanOfferMapping.get(j)){
                        ppOffer.Price_Plan__c = clonedPricePlans[j].Id;
                        pricePlansOffers.add(ppOffer);
                    }
                }
                insert pricePlansOffers;
            } catch (Exception exceptionToHandle){
                Database.rollback(sp);
                // clear id if we roll back the save
                planClone.Id = null;
                System.debug(loggingLevel.Error, 'An error: ' + exceptionToHandle);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Price_Plan_Clone_Save_Error));
                return null;
            }
            // perhaps the page redirect will be set on the permission set check
            pageDestination = Page.PricePlanRulesSetup;
            pageDestination.getParameters().put('id', planClone.Id);  
        } else {
            pageDestination = new PageReference('/' + planClone.Id);
        }
        
        return pageDestination;
    }

    /**
    * Author:       Gavin Palmer (Accenture)
    * Date:         21/04/2016
    * Description:  Validate the required fields on the page
    *
    * ******************* Change Log *******************
    * Modified by       Change Date     Description
    **/
    private Boolean isValidPricePlan(){
        if(String.isEmpty(planClone.Name)){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Price_Plan_Name_Error));
        }
        if(ApexPages.hasMessages()){
            return false;
        }
        return true;
    }
}