src/objects/Quote_Offer_Code__c.object
<CustomObject>
    <fields>
        <fullName>Blling_Period__c</fullName>
        <label>Blling Period</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Periods__c</fullName>
        <label>Number of Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Code_Value__c</fullName>
        <description>save the offer code value enter by the agent (it will have value for acquisition)</description>
        <label>Offer Code Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Offer Codes</relationshipLabel>
        <relationshipName>Quote_Offer_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Discount</fullName>
                </value>
                <value>
                    <fullName>Mid Term Discount</fullName>
                </value>
                <value>
                    <fullName>Default Offer Code</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Offer Code</label>
    <nameField>
        <displayFormat>Offer-{0000000000}</displayFormat>
        <label>Quote Offer Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Offer Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <fields>
        <fullName>PromoCode__c</fullName>
        <label>Promo Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <pluralLabel>Quotes</pluralLabel>
</CustomObject>

src/classes/ZQuoteOfferCodeTriggerHandlerTest.cls
/**
* Author:       Sally ElGhoul (Accenture)
* Date:         29/01/2016
* Description:  this class for testing ZQuoteOfferCodeTrigger 
*
* ******************* Change Log *******************
* Modified by       Change Date
* Wiktor Czykin     06/06/2017  //simplified - removed usage of "invalid" test data generation method
**/
@isTest
private class ZQuoteOfferCodeTriggerHandlerTest {

    /***************************************************************************************
    Developer   Unknown
    Date        Unknown
    Function    test promo code update on quote
    ******************* Change Log *******************
    Modified by         Change Date
    Wiktor Czykin       08/06/2017 //refactored a bit
    ****************************************************************************************/
    private static testMethod void testTrigger() {
        TestDataUtility td = new TestDataUtility(4);
        td.createZQuotes();
        
        List<Quote_Offer_Code__c> lst = new List<Quote_Offer_Code__c>();
        for(zqu__Quote__c q : td.lstZQuotes){
            lst.add(new Quote_Offer_Code__c(
                                            Quote__c = q.id,
                                            Offer_Code_Value__c = 'TestingPromoCode',
                                            Name__c = 'PromoCodeTestName',
                                            Number_of_Periods__c = 1,
                                            Discount_Amount__c = 2,
                                            Blling_Period__c = Constants.OFFER_FREQUENCY_MONTH,
                                            Type__c = Constants.OFFER_CODE_DEFAULT_RATE_PLAN_DISCOUNT_TYPE
            ));
        }
        Test.startTest();
            insert lst;
        
            List<zqu__Quote__c> lstQuotes = [select Id, PromoCode__c from zqu__Quote__c where Id in :td.lstZQuotes];
            for(zqu__Quote__c q : lstQuotes){
                System.assertEquals('TestingPromoCode', q.PromoCode__c);
            }
            
            //check after deleting thw quote offer code the promo quote on quote is cleared
            delete lst;
            lstQuotes = [select id,PromoCode__c from zqu__Quote__c where id in :td.lstZQuotes];
            for(zqu__Quote__c q : lstQuotes){
                System.assertEquals(null, q.PromoCode__c);
            }
        Test.stopTest();
    }
}