src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Week_Position_Final__c</fullName>
        <label>Current Week Position Final</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Week_Position__c</fullName>
        <description>SB 27/11: Old:
CASE(Subscription_Status__c,
&quot;Offered&quot;, 0,
&quot;Pending&quot;, 0,
&quot;Withdrawn&quot;,0,
&quot;Declined&quot;,0,
IF(ISNULL(Current_Week_Position_Final__c), CEILING((Today() - Start_Date__c) / 7), Current_Week_Position_Final__c)
)</description>
        <formula>CASE(Subscription_Status__c, 
&quot;Offered&quot;, 0, 
&quot;Pending&quot;, 0,
&quot;Withdrawn&quot;,0,
&quot;Declined&quot;,0,
IF(ISNULL(Current_Week_Position_Final__c), CEILING((Today() - Start_Date__c + 1) / 7), Current_Week_Position_Final__c)
)</formula>
        <label>Current Week Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>For normal subscriptions.</description>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionsCancellationBatch.cls
/**
 * Ref:PP-1896
 *
 * A batch class to update the "Current_Week_Position_Final__c" field on Subscriptions which have status 'Pending Cancellation'
 * The batch picks up all such records from Subscriptions__c and updates those records satisfying the above condition.
 *
 * The batch is scheduled through the SubscriptionsCancellationScheduler scheduler class
 *
 * @see SubscriptionsCancellationScheduler
 */
global class SubscriptionsCancellationBatch implements Database.Batchable<sObject> {

    /** The query variable */
    global final String query;

    /** The place holder for any custom params being passed along with */
    global final Map<String, Object> customParams;

    
    /** 
     * Default constructor accepting the query to be executed to pick the scope objects
     * to be updated.
     *
     * @param query     the query to be executed
     */
    global SubscriptionsCancellationBatch(String query) {
        this.query = query; 
    }


    /** 
     * Overloaded constructor for any future modifications.
     * Accepts the query and any custom parameters required for any further modifications to the class.
     *
     * @param query     the query to be executed
     */
    global SubscriptionsCancellationBatch(String query, Map<String, Object> customParams) {
        this.query = query; 
        this.customParams = customParams;
    }


    /**
     * The default start() implementation
     *
     * @param BC    the Database.BatchableContext reference
     * @return the query locator for the query string as passed in the constructor
     */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }


    /** 
     * The default execute() implementation. This method updates the Current_Week_Position_Final__c field of the
     * records satisfying the criteria. 
     *
     * @param BC    the Database.BatchableContext reference
     * @param scope the list of scope objects as returned by the query
     */
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Subscription__c> updateList = new List<Subscription__c>();
        Date cancellationDate;
        Date startDate;
        Subscription__c sub;
        
        for(sObject s : scope) {
            sub = (Subscription__c) s;
            if(sub.Subscription_Status__c == 'Pending Cancellation') {
                cancellationDate = sub.Cancellation_Date__c;
                startDate = sub.Start_Date__c;
                sub.Current_Week_Position_Final__c = Math.ceil(cancellationDate.daysBetween(startDate) / 7);
                updateList.add(sub);
            }
            
            if(sub.Subscription_Status__c == 'Cancelled') {
                sub.Current_Week_Position_Final__c = sub.Current_Week_Position__c < 0 ? 0 : sub.Current_Week_Position__c;
                updateList.add(sub);
            } 
        }

        // only for testing fail conditions
        if(Test.isRunningTest()) {
            if(customParams != null && customParams.containsKey('TEST_EXCEPTION')) {
                throw new WebserviceUtil.NullParameterException('TESTING EXCEPTION', '');
            }
        }

        update updateList;
    }

   
    /** 
     * The default finish() implementation 
     */
    global void finish(Database.BatchableContext BC) {
    
    }
}