src/objects/Subscription__c.object
<CustomObject>
    <description>Represents a Subscription to The Daily Telegraph and Sunday Telegraph.</description>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Duration_Picklist__c</fullName>
        <label>Subscription Duration (Weeks)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>26</fullName>
                </value>
                <value>
                <fullName>52</fullName>
                <default>true</default>
                    <label>52</label>
                </value>
                <value>
                <fullName>13</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                <fullName>Active</fullName>
                </value>
                <value>
                <fullName>In Renewal</fullName>
                </value>
                <value>
                <fullName>Offered</fullName>
                <default>true</default>
                    <label>Offered</label>
                </value>
                <value>
                <fullName>Pending</fullName>
                </value>
                <value>
                <fullName>Withdrawn</fullName>
                </value>
                <value>
                <fullName>Declined</fullName>
                </value>
                <value>
                <fullName>Lapsed</fullName>
                </value>
                <value>
                <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                <fullName>Cancelled</fullName>
                </value>
                <value>
                <fullName>Temporary Suspension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionRenewalUtils.cls
public class SubscriptionRenewalUtils {

	public static String getSubscriptionType(Subscription__c sub){
		String sType;
		
		if(sub<>null){
			
			stype = sub.Subscription_Duration_Picklist__c + ' Week';
		}
		
		return sType;
	}
	
	public static boolean getShowStartDate(Subscription__c sub){
		/* Start date is shown for non-DD subs; or for DD-subs if status is pending and start-date is in future */
		if(sub <> null){
			
			if(sub.Subscription_Status__c == CONSTANTS.SSTATUS_PENDING &&
			   sub.Start_Date__c > date.today()){
			   	return true;
			}else if(sub.Subscription_Status__c == CONSTANTS.SSTATUS_IN_RENEWAL ||
						sub.Subscription_status__c == CONSTANTS.SSTATUS_ACTIVE){
				return true;
			}else{
				return false;
			}
		}
		
		return null;
	}	
	
	public static boolean getShowEndDate(Subscription__c sub){
		/* End date are shown if sub status is (active or pending) and payment method is not DD */		
		if(sub <> null){
			
			if((sub.subscription_status__c == CONSTANTS.SSTATUS_ACTIVE ||
				sub.subscription_status__c == CONSTANTS.SSTATUS_PENDING ||
				sub.subscription_status__c == CONSTANTS.SSTATUS_IN_RENEWAL ||
				sub.subscription_status__c == CONSTANTS.SSTATUS_PENDING_CANX ||
				sub.subscription_status__c == CONSTANTS.SSTATUS_CANX) ){
				return true;	
			}else{
				return false;
			}
			
		}
		
		return null;
	}	
	
	public static boolean getAllowRenewal(Subscription__c sub, Boolean hasOfferedSub){
		
		if(sub <> null){
			
			if( (sub.subscription_status__c == CONSTANTS.SSTATUS_IN_RENEWAL ||
					( (sub.subscription_status__c == CONSTANTS.SSTATUS_CANX || 
						sub.subscription_status__c == CONSTANTS.SSTATUS_PENDING_CANX) && 
						Date.today() <= sub.cancellation_date__c
					 )
			     )&&
			     hasOfferedSub
			   ){
				return true;
			}else{
				return false;
			}
			
		}
		
		return null;
	}  	
}